In [2]:
import pandas as pd
from plotnine import *
import re

In [3]:
df = pd.read_csv('data/df_filled.csv')

In [4]:
df.head()

,address,lat,lng,구,년도,업소명,업종명,업태명,영업자시작년도,영업자시작일,폐업년도,폐업일자
0,서울특별시 은평구 신사동 17번지 11호 2층,37.598980,126.910005,은평구,2014.0,2월7일,일반음식점,호프/통닭,2014.0,20140224.0,NaN,NaN
1,서울특별시 은평구 수색동 75번지 DMC 자이상가 1층108호,37.579561,126.898666,은평구,2014.0,오봉도시락,휴게음식점,일반조리판매,2014.0,20141010.0,NaN,NaN
2,서울특별시 은평구 대조동 185번지 16호,37.618575,126.921100,은평구,1999.0,명송회집,일반음식점,분식,2013.0,20130308.0,2013.0,20131220.0
3,"서울특별시 은평구 갈현동 506번지 9호 103,104호",37.616395,126.912951,은평구,2013.0,장충왕족발보쌈,일반음식점,호프/통닭,2013.0,20130808.0,2014.0,20141226.0
4,서울특별시 은평구 응암동 72번지 3호 1층,37.600772,126.929972,은평구,2016.0,예쁜 뽀들이 함바,일반음식점,한식,2016.0,20161129.0,NaN,NaN

In [5]:
df_seoul = df.copy(deep=True)

In [6]:
df_seoul = df_seoul.ix[(df_seoul['address'].str.contains('서울특별시'))]

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [7]:
df_seoul.loc[~(df_seoul['address'].str.contains('서울'))]

Empty DataFrame
Columns: [address, lat, lng, 구, 년도, 업소명, 업종명, 업태명, 영업자시작년도, 영업자시작일, 폐업년도, 폐업일자]
Index: []

In [8]:
df_seoul['area'] = df_seoul['address'].str.extract(r'([가-힣|0-9]+[동|가])[^종로구]')

In [9]:
df_seoul['area'][165426] = '개봉동'

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
df_seoul.loc[df_seoul['area'].isnull()]

,address,lat,lng,구,년도,업소명,업종명,업태명,영업자시작년도,영업자시작일,폐업년도,폐업일자,area
1065,서울특별시 종로구 세종로 157번지 4호 지상1층,37.571477,126.976313,종로구,2002.0,로즈버드(광화문),휴게음식점,다방,2008.0,20080128.0,2014.0,20141107.0,NaN
1220,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,스위토아이스크림,휴게음식점,기타 휴게음식점,2014.0,20140114.0,NaN,NaN,NaN
1221,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,라피아짜,일반음식점,경양식,2014.0,20140114.0,NaN,NaN,NaN
1222,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,설가온,일반음식점,기타,2014.0,20140114.0,NaN,NaN,NaN
1318,서울특별시 종로구 세종로 80번지 1호 지상1층,37.573397,126.975866,종로구,2011.0,뿌리깊은 나무,휴게음식점,커피숍,2012.0,20120119.0,2014.0,20140220.0,NaN
1465,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2006.0,월넛,휴게음식점,커피숍,2011.0,20111213.0,2012.0,20121231.0,NaN
1468,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,친니＆바심,일반음식점,중국식,2014.0,20140114.0,NaN,NaN,NaN
1502,서울특별시 종로구 세종로 155번지 4호,37.571478,126.976367,종로구,2014.0,엔제리너스 세종로점,휴게음식점,커피숍,2017.0,20170710.0,NaN,NaN,NaN
3343,서울특별시 종로구 세종로 157번지 4호,37.571477,126.976313,종로구,1998.0,하루코,일반음식점,분식,2009.0,20090316.0,2014.0,20140331.0,NaN
3744,서울특별시 종로구 세종로 100번지 지하2층,37.572163,126.977969,종로구,2004.0,광화문 KT,휴게음식점,일반조리판매,2008.0,20080204.0,NaN,NaN,NaN
3813,서울특별시 종로구 세종로 77번지 6호,37.575591,126.975615,종로구,2003.0,이씨엠디 휴게실,제과점영업,제과점영업,2010.0,20100423.0,NaN,NaN,NaN
3883,서울특별시 종로구 세종로 155번지 4호,37.571478,126.976367,종로구,1997.0,비알코리아(주) 던킨도너츠 광화문점,휴게음식점,패스트푸드,2010.0,20100316.0,2014.0,20140418.0,NaN
4276,서울특별시 종로구 세종로 100번지 1층,37.572163,126.977969,종로구,2010.0,아르디카페 광화문점,휴게음식점,커피숍,2012.0,20120903.0,2015.0,20150716.0,NaN
4547,서울특별시 종로구 세종로 81번지 3호 예술 1층,37.571881,126.976659,종로구,2013.0,셀란,휴게음식점,커피숍,2016.0,20160108.0,NaN,NaN,NaN
4780,서울특별시 종로구 세종로 80번지 1호,37.573397,126.975866,종로구,2013.0,세종,휴게음식점,일반조리판매,2013.0,20130412.0,NaN,NaN,NaN
5053,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2013.0,큐비드,휴게음식점,커피숍,2013.0,20130227.0,NaN,NaN,NaN
5119,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2017.0,쿡스테이크,휴게음식점,푸드트럭,2017.0,20170817.0,NaN,NaN,NaN
5150,서울특별시 종로구 세종로 81번지 3호 세종문화회관 지하2층,37.571881,126.976659,종로구,2010.0,샘이 깊은 물,휴게음식점,커피숍,2013.0,20130712.0,NaN,NaN,NaN
5202,서울특별시 종로구 세종로 200번지 지상2층,37.570691,126.976281,종로구,1989.0,할리스 에프앤비,일반음식점,경양식,2017.0,20170120.0,NaN,NaN,NaN
5203,서울특별시 종로구 세종로 200번지 0호,37.570691,126.976281,종로구,1989.0,할리스에프앤비 세종로점,일반음식점,경양식,2017.0,20170120.0,NaN,NaN,NaN
5255,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2013.0,빌리엔젤,휴게음식점,커피숍,2013.0,20130722.0,NaN,NaN,NaN
5644,서울특별시 종로구 세종로 166번지 1호,37.571543,126.976184,종로구,1997.0,커피티쳐,일반음식점,경양식,2011.0,20110117.0,NaN,NaN,NaN
5716,서울특별시 종로구 세종로 166번지 1호,37.571543,126.976184,종로구,1972.0,가봉루,일반음식점,중국식,2014.0,20140204.0,NaN,NaN,NaN
7013,서울특별시 종로구 세종로 80번지 1호 지상1층,37.573397,126.975866,종로구,2014.0,엔제리너스커피(Angelinus coffee) 세종로 티오(T/O),휴게음식점,커피숍,2014.0,20140421.0,2015.0,20150324.0,NaN
7014,서울특별시 종로구 세종로 80번지 1호 지상1층,37.573397,126.975866,종로구,2014.0,나뚜루팝(natuur-pop) 세종로 티오(T/O),휴게음식점,기타 휴게음식점,2014.0,20140421.0,NaN,NaN,NaN
7151,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,포77,일반음식점,분식,2014.0,20140114.0,NaN,NaN,NaN
7152,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,포77-1,일반음식점,분식,2014.0,20140114.0,NaN,NaN,NaN
7311,"서울특별시 종로구 세종대로 189, 1층 (세종로, 세종로공원내)",37.573430,126.975959,종로구,2014.0,맛있는 김치판,일반음식점,한식,2014.0,20141111.0,2014.0,20141118.0,NaN
7890,서울특별시 종로구 세종로 1번지 57호 국립고궁박물관,37.586606,126.976774,종로구,2007.0,고궁뜨락,일반음식점,경양식,2015.0,20150410.0,NaN,NaN,NaN
7980,서울특별시 종로구 세종로 100번지,37.572163,126.977969,종로구,2006.0,가온 웰빙부페&샤브,일반음식점,한식,2015.0,20150507.0,2017.0,20170801.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29716,서울특별시 종로구 세종로 82번지 1호,37.573922,126.977925,종로구,2012.0,씨제이프레시웨이(주) 국립중앙박물관점 카페황토마루,휴게음식점,커피숍,2017.0,20170302.0,NaN,NaN,NaN
40034,서울특별시 종로구 세종로 204번지 1호 지상2층,37.570459,126.976298,종로구,2007.0,본죽앤비빔밥 광화문점,일반음식점,일식,2016.0,20161223.0,NaN,NaN,NaN
40075,서울특별시 종로구 세종로 161번지 1호,37.571508,126.975965,종로구,1989.0,케이에프씨광화문매장,휴게음식점,패스트푸드,2016.0,20161220.0,2017.0,20170413.0,NaN
40091,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,1999.0,세종문화회관세종홀,일반음식점,뷔페식,2017.0,20170206.0,2017.0,20171013.0,NaN
40518,서울특별시 종로구 세종로 81번지 3호 1층,37.571881,126.976659,종로구,2017.0,세종투자개발(주) 세종문화회관 세종홀,일반음식점,기타,2017.0,20171017.0,NaN,NaN,NaN
40519,서울특별시 종로구 세종로 81번지 3호 1층,37.571881,126.976659,종로구,2017.0,세종문화회관 세종홀,일반음식점,기타,2017.0,20171017.0,NaN,NaN,NaN
40637,서울특별시 종로구 세종로 160번지 2호,37.571654,126.976109,종로구,2017.0,코코커피,휴게음식점,커피숍,2017.0,20171211.0,NaN,NaN,NaN
40746,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2017.0,헌터스 위크,휴게음식점,푸드트럭,2017.0,20170323.0,NaN,NaN,NaN
40747,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2017.0,새우고 먹는 i,휴게음식점,푸드트럭,2017.0,20170323.0,NaN,NaN,NaN
40836,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2017.0,Ya!먹자,휴게음식점,푸드트럭,2017.0,20170816.0,NaN,NaN,NaN
40864,서울특별시 종로구 세종로 161번지 1호 1~2층,37.571508,126.975965,종로구,2017.0,KFC 광화문매장,일반음식점,기타,2017.0,20170804.0,NaN,NaN,NaN
40917,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2017.0,코끼리떡볶기,휴게음식점,푸드트럭,2017.0,20170817.0,NaN,NaN,NaN
40918,서울특별시 종로구 세종로 1번지 68호,37.586606,126.976774,종로구,2017.0,쉬림프온더스트리트,휴게음식점,푸드트럭,2017.0,20170817.0,NaN,NaN,NaN
51027,서울특별시 종로구 세종로 173번지 1호 1~2층,37.571433,126.975956,종로구,1996.0,에스오,일반음식점,통닭(치킨),2016.0,20160308.0,NaN,NaN,NaN
51028,서울특별시 종로구 세종로 173번지 1호 1~2층,37.571433,126.975956,종로구,1996.0,에스오치킨 앤 키친,일반음식점,통닭(치킨),2016.0,20160308.0,NaN,NaN,NaN
51029,서울특별시 종로구 세종로 173번지 1호 1~2층,37.571433,126.975956,종로구,1996.0,에스오,일반음식점,통닭(치킨),2017.0,20171229.0,NaN,NaN,NaN
51030,서울특별시 종로구 세종로 173번지 1호 1~2층,37.571433,126.975956,종로구,1996.0,에스오치킨 앤 키친,일반음식점,통닭(치킨),2017.0,20171229.0,NaN,NaN,NaN
332490,서울특별시 종로구 세종로 81번지 3호,37.571881,126.976659,종로구,2011.0,명동 칼국수,일반음식점,한식,2014.0,20140114.0,NaN,NaN,NaN
332604,서울특별시 종로구 세종로 81번지 3호 지상1층,37.571881,126.976659,종로구,2007.0,카페테리아,휴게음식점,일반조리판매,2007.0,20070226.0,2011.0,20110708.0,NaN
332667,서울특별시 종로구 세종로 100번지 KT 광화문사옥 지상1층,37.572163,126.977969,종로구,2006.0,KT아트홀,휴게음식점,커피숍,2007.0,20070326.0,2010.0,20100524.0,NaN
333211,서울특별시 종로구 세종로 1번지 57호 국립고궁박물관,37.586606,126.976774,종로구,2007.0,국립고궁박물관 뮤지엄숍,휴게음식점,커피숍,2007.0,20071119.0,NaN,NaN,NaN
333367,서울특별시 종로구 세종로 77번지 6호 정부중앙청사 본관 지상1층,37.575591,126.975615,종로구,2008.0,(주)커피빈코리아 정부종합청사점,휴게음식점,커피숍,2008.0,20080529.0,2014.0,20140508.0,NaN
333580,서울특별시 종로구 세종로 1번지 (지상2층),37.586606,126.976774,종로구,2009.0,파랑가 by 콩두,휴게음식점,커피숍,2009.0,20090216.0,NaN,NaN,NaN
333679,서울특별시 종로구 세종로 1번지 1호 경복궁 복합편의시설 1층,37.586606,126.976774,종로구,2010.0,경복궁 버들마루,휴게음식점,전통찻집,2017.0,20171027.0,NaN,NaN,NaN
334013,서울특별시 종로구 세종로 1번지 1호 국립민속박물관 지상1층,37.586606,126.976774,종로구,2005.0,풀오브 빈스 느루,휴게음식점,일반조리판매,2015.0,20151002.0,NaN,NaN,NaN
334098,서울특별시 종로구 세종로 76번지 2호 광화문시민열린마당,37.575235,126.978345,종로구,2017.0,타파스트럭,휴게음식점,푸드트럭,2017.0,20170920.0,NaN,NaN,NaN
334190,서울특별시 종로구 세종로 139번지,37.569552,126.977677,종로구,2002.0,수래연,휴게음식점,다방,2010.0,20101223.0,NaN,NaN,NaN
334192,서울특별시 종로구 세종로 185번지 2호,37.571254,126.976308,종로구,2002.0,스타벅스광화문R점,휴게음식점,다방,2008.0,20080114.0,NaN,NaN,NaN
334193,서울특별시 종로구 세종로 185번지 2호,37.571254,126.976308,종로구,2002.0,스타벅스광화문점,휴게음식점,다방,2008.0,20080114.0,NaN,NaN,NaN
334202,서울특별시 종로구 세종로 202번지 1호 1~3,37.570611,126.976332,종로구,2013.0,고디바,휴게음식점,커피숍,2013.0,20131119.0,NaN,NaN,NaN

In [11]:
df_seoul['area'].isnull().sum()

62

In [ ]:
df_seoul = df_seoul.groupby('area').count()
df_seoul

In [12]:
seoul_area = {}

for area in df_seoul['area']:
    if area not in seoul_area.keys():
        seoul_area[area] = 1
    else:
        seoul_area[area] += 1
seoul_area

{'신사동': 6848,
 '수색동': 192,
 '대조동': 992,
 '갈현동': 1429,
 '응암동': 1492,
 '녹번동': 501,
 '역촌동': 810,
 '진관동': 593,
 '불광동': 947,
 '구산동': 273,
 '증산동': 300,
 '관훈동': 208,
 '부암동': 127,
 '창신동': 577,
 '명륜4가': 315,
 '계동': 108,
 '삼청동': 185,
 '명륜3가': 145,
 '익선동': 139,
 '종로3가': 108,
 '수송동': 173,
 '명륜2가': 292,
 '관철동': 589,
 '도렴동': 79,
 '숭인동': 419,
 '가회동': 48,
 '관수동': 146,
 '견지동': 50,
 '인사동': 198,
 '통의동': 130,
 '누하동': 78,
 '안국동': 70,
 '재동': 92,
 '평창동': 191,
 '와룡동': 50,
 '낙원동': 236,
 '원서동': 35,
 '명륜1가': 71,
 '신영동': 56,
 '혜화동': 145,
 '묘동': 97,
 '구기동': 105,
 '종로5가': 226,
 nan: 62,
 '평동': 38,
 '공평동': 33,
 '당주동': 226,
 '연지동': 104,
 '종로2가': 149,
 '신문로1가': 129,
 '돈의동': 135,
 '내수동': 221,
 '권농동': 25,
 '경운동': 30,
 '소격동': 84,
 '통인동': 118,
 '팔판동': 73,
 '동숭동': 455,
 '서린동': 91,
 '종로6가': 125,
 '인의동': 123,
 '교북동': 30,
 '체부동': 109,
 '종로4가': 40,
 '종로1가': 162,
 '필운동': 104,
 '사간동': 23,
 '청진동': 287,
 '장사동': 21,
 '효제동': 144,
 '원남동': 53,
 '적선동': 119,
 '홍지동': 73,
 '이화동': 68,
 '봉익동': 43,
 '무악동': 77,
 '교남동': 65,
 '화동': 63,
 '사직동': 83,
 '충신동': 48,
 '창성동': 31,
 '연건동': 109,
 '내자동': 123,
 '신문로2가': 93,
 '옥인동': 55,
 '운니동': 36,
 '누상동': 40,
 '청운동': 29,
 '중학동': 45,
 '홍파동': 11,
 '예지동': 18,
 '신교동': 21,
 '효자동': 28,
 '송현동': 3,
 '행촌동': 13,
 '1동': 2,
 '궁정동': 3,
 '역삼동': 9145,
 '문정동': 2412,
 '석촌동': 1499,
 '잠실동': 3600,
 '방이동': 2332,
 '삼전동': 1033,
 '마천동': 1010,
 '신천동': 1195,
 '가락동': 2547,
 '송파동': 1500,
 '장지동': 332,
 '거여동': 845,
 '오금동': 929,
 '풍납동': 767,
 '올림픽로35가': 1,
 '신정동': 3721,
 '목동': 4415,
 '신월동': 3026,
 '공항동': 932,
 '문래동2가': 150,
 '대림동': 2426,
 '양평동3가': 207,
 '양평동4가': 502,
 '여의도동': 4063,
 '영등포동': 574,
 '영등포동4가': 714,
 '당산동1가': 364,
 '문래동3가': 758,
 '영등포동7가': 278,
 '신길동': 2383,
 '당산동4가': 275,
 '영등포동3가': 686,
 '문래동6가': 148,
 '도림동': 418,
 '양평동5가': 155,
 '양평동1가': 339,
 '당산동3가': 667,
 '영등포동5가': 258,
 '양화동': 34,
 '영등포동1가': 86,
 '당산동5가': 254,
 '영등포동8가': 173,
 '양평동6가': 29,
 '문래동1가': 91,
 '양평동2가': 247,
 '문래동4가': 110,
 '문래동5가': 64,
 '당산동6가': 326,
 '당산동2가': 216,
 '영등포동2가': 277,
 '당산동': 132,
 '영등포동6가': 208,
 '양평동': 1,
 '선유동': 1,
 '101동': 3,
 '신내동': 647,
 '중화동': 849,
 '면목동': 2675,
 '망우동': 980,
 '묵동': 803,
 '상봉동': 1062,
 '삼성동': 5385,
 '논현동': 5883,
 '청담동': 2927,
 '대치동': 4753,
 '도곡동': 1772,
 '개포동': 1581,
 '세곡동': 149,
 '수서동': 549,
 '일원동': 674,
 '압구정동': 1170,
 '율현동': 60,
 '자곡동': 139,
 '영동': 7,
 '마곡동': 925,
 '등촌동': 2495,
 '방화동': 2507,
 '화곡동': 6764,
 '염창동': 766,
 '내발산동': 1252,
 '가양동': 809,
 '외발산동': 62,
 '과해동': 50,
 '개화동': 19,
 '오쇠동': 1,
 '미아동': 4688,
 '수유동': 3950,
 '번동': 1429,
 '우이동': 399,
 '도선동': 373,
 '명일동': 1690,
 '상일동': 675,
 '성내동': 3969,
 '둔촌동': 872,
 '길동': 2266,
 '천호동': 4319,
 '고덕동': 580,
 '암사동': 1788,
 '강일동': 225,
 '신림동': 9034,
 '봉천동': 7244,
 '남현동': 581,
 '신대방동': 1083,
 '을지로2가': 299,
 '남산동1가': 42,
 '신당동': 1484,
 '충무로5가': 68,
 '을지로5가': 44,
 '을지로6가': 609,
 '충무로1가': 498,
 '소공동': 456,
 '수하동': 85,
 '주교동': 66,
 '남창동': 165,
 '무학동': 71,
 '중림동': 282,
 '명동2가': 365,
 '북창동': 151,
 '쌍림동': 95,
 '초동': 128,
 '충무로2가': 219,
 '수표동': 71,
 '충무로4가': 140,
 '방산동': 11,
 '주자동': 3,
 '남대문로5가': 382,
 '장충동2가': 191,
 '태평로1가': 148,
 '순화동': 144,
 '남산동2가': 94,
 '무교동': 144,
 '회현동2가': 61,
 '저동2가': 97,
 '필동2가': 164,
 '봉래동2가': 191,
 '회현동1가': 172,
 '황학동': 363,
 '인현동1가': 44,
 '다동': 269,
 '태평로2가': 169,
 '을지로3가': 131,
 '명동1가': 133,
 '필동1가': 83,
 '남대문로4가': 56,
 '서소문동': 188,
 '필동3가': 87,
 '입정동': 18,
 '남대문로2가': 44,
 '충무로3가': 168,
 '을지로4가': 47,
 '예관동': 21,
 '오장동': 66,
 '인현동2가': 63,
 '남대문로3가': 43,
 '만리동1가': 30,
 '산림동': 23,
 '저동1가': 56,
 '만리동2가': 33,
 '흥인동': 121,
 '광희동1가': 141,
 '예장동': 29,
 '을지로1가': 97,
 '장교동': 37,
 '장충동1가': 47,
 '정동': 96,
 '남산동3가': 19,
 '묵정동': 35,
 '의주로1가': 11,
 '봉래동1가': 35,
 '충정로1가': 22,
 '남학동': 10,
 '광희동2가': 33,
 '삼각동': 11,
 '회현동3가': 24,
 '남대문로1가': 14,
 '을지로7가': 120,
 '개봉동': 1722,
 '구로동': 6390,
 '천왕동': 71,
 '온수동': 191,
 '신도림동': 963,
 '오류동': 960,
 '고척동': 1429,
 '가리봉동': 652,
 '궁동': 204,
 '항동': 24,
 '창동': 2449,
 '쌍문동': 1428,
 '도봉동': 1489,
 '방학동': 2084,
 '시흥동': 2857,
 '독산동': 3342,
 '가산동': 2495,
 '자양동': 3196,
 '화양동': 2054,
 '광장동': 651,
 '중곡동': 2345,
 '구의동': 2451,
 '군자동': 769,
 '능동': 355,
 '모진동': 1,
 '상계동': 4943,
 '월계동': 1307,
 '공릉동': 1947,
 '하계동': 544,
 '중계동': 1916,
 '동일로204가': 1,
 '201동': 1,
 '공릉로62가': 1,
 '동일로173가': 1,
 '의주로2가': 2,
 '한강로1가': 162,
 '갈월동': 193,
 '청파동2가': 229,
 '한남동': 1109,
 '효창동': 87,
 '용산동4가': 5,
 '후암동': 311,
 '원효로2가': 127,
 '이태원동': 1639,
 '한강로3가': 497,
 '한강로2가': 403,
 '용산동2가': 310,
 '보광동': 290,
 '남영동': 161,
 '서계동': 137,
 '원효로3가': 104,
 '청파동3가': 154,
 '용문동': 167,
 '용산동3가': 25,
 '동자동': 253,
 '이촌동': 366,
 '동빙고동': 53,
 '청파동1가': 63,
 '신계동': 96,
 '원효로1가': 188,
 '원효로4가': 49,
 '용산동1가': 13,
 '용산동6가': 26,
 '서빙고동': 12,
 '신창동': 17,
 '도원동': 18,
 '용산동5가': 40,
 '문배동': 72,
 '청암동': 3,
 '산천동': 26,
 '서교동': 5026,
 '제기동': 1128,
 '전농동': 1555,
 '장안동': 2741,
 '회기동': 1058,
 '답십리동': 1139,
 '이문동': 1243,
 '신설동': 536,
 '청량리동': 756,
 '용두동': 1107,
 '휘경동': 797,
 '사가': 1,
 '노량진동': 1474,
 '상도동': 1924,
 '사당동': 2662,
 '흑석동': 906,
 '대방동': 576,
 '본동': 118,
 '상도1동': 278,
 '동작동': 45,
 '상도로61가': 1,
 '제1상가동': 1,
 '401동': 2,
 '가동': 1,
 '노량진로14가': 1,
 '사당로16가': 3,
 '112동': 1,
 '만양로14가': 2,
 '여의대방로22가': 1,
 '동작대로27가': 3,
 '사당로17가': 2,
 '상도로41가': 1,
 '신대방1가': 1,
 '120동': 1,
 '433동': 1,
 '서달로14가': 1,
 '상가동동': 3,
 '동작대로33가': 1,
 '상가동': 1,
 '상암동': 1719,
 '연남동': 1199,
 '염리동': 480,
 '공덕동': 1037,
 '성산동': 1100,
 '도화동': 1174,
 '망원동': 1612,
 '창전동': 405,
 '대흥동': 580,
 '마포동': 91,
 '동교동': 1407,
 '용강동': 389,
 '합정동': 1211,
 '상수동': 891,
 '신수동': 514,
 '노고산동': 613,
 '아현동': 584,
 '신공덕동': 283,
 '중동': 120,
 '현석동': 27,
 '구수동': 81,
 '토정동': 16,
 '하중동': 8,
 '당인동': 20,
 '방배동': 3472,
 '서초동': 6467,
 '반포동': 3276,
 '양재동': 3011,
 '잠원동': 1503,
 '우면동': 295,
 '신원동': 118,
 '염곡동': 22,
 '원지동': 75,
 '내곡동': 65,
 '연희동': 1045,
 '홍제동': 1228,
 '창천동': 2344,
 '충정로3가': 299,
 '북가좌동': 860,
 '대현동': 1113,
 '남가좌동': 1379,
 '충정로2가': 239,
 '홍은동': 970,
 '신촌동': 201,
 '북아현동': 505,
 '미근동': 163,
 '냉천동': 189,
 '대신동': 125,
 '합동': 37,
 '영천동': 92,
 '옥천동': 25,
 '현저동': 26,
 '천연동': 39,
 '봉원동': 3,
 '204동': 1,
 '403동': 1,
 '길음동': 1003,
 '삼선동1가': 107,
 '동소문동3가': 37,
 '삼선동4가': 116,
 '장위동': 1320,
 '종암동': 755,
 '동선동3가': 102,
 '동소문동2가': 155,
 '동선동1가': 646,
 '정릉동': 1361,
 '석관동': 908,
 '삼선동2가': 222,
 '안암동5가': 843,
 '성북동1가': 75,
 '보문동4가': 56,
 '삼선동5가': 149,
 '하월곡동': 1149,
 '보문동2가': 61,
 '돈암동': 259,
 '성북동': 327,
 '동소문동5가': 136,
 '동소문동6가': 92,
 '상월곡동': 170,
 '보문동7가': 115,
 '삼선동3가': 36,
 '동선동4가': 119,
 '동선동2가': 280,
 '동소문동7가': 49,
 '보문동5가': 60,
 '동선동5가': 72,
 '안암동4가': 29,
 '보문동6가': 32,
 '동소문동1가': 64,
 '보문동1가': 80,
 '안암동2가': 33,
 '동소문동4가': 82,
 '안암동1가': 56,
 '안암동3가': 19,
 '보문동3가': 4,
 '행당동': 1806,
 '성수동1가': 1166,
 '금호동4가': 293,
 '하왕십리동': 447,
 '성수동2가': 1856,
 '용답동': 619,
 '금호동1가': 209,
 '금호동3가': 263,
 '금호동2가': 267,
 '마장동': 375,
 '상왕십리동': 189,
 '옥수동': 381,
 '홍익동': 184,
 '송정동': 171,
 '사근동': 116,
 '응봉동': 104,
 '221동': 2,
 '상가': 1,
 '121동': 1,
 '송월동': 2}

In [13]:
seoul = pd.DataFrame()

In [14]:
seoul['area'] = seoul_area.keys()

In [16]:
seoul.info

<bound method DataFrame.info of        area
0       신사동
1       수색동
2       대조동
3       갈현동
4       응암동
5       녹번동
6       역촌동
7       진관동
8       불광동
9       구산동
10      증산동
11      관훈동
12      부암동
13      창신동
14     명륜4가
15       계동
16      삼청동
17     명륜3가
18      익선동
19     종로3가
20      수송동
21     명륜2가
22      관철동
23      도렴동
24      숭인동
25      가회동
26      관수동
27      견지동
28      인사동
29      통의동
..      ...
467   동선동5가
468   안암동4가
469   보문동6가
470  동소문동1가
471   보문동1가
472   안암동2가
473  동소문동4가
474   안암동1가
475   안암동3가
476   보문동3가
477     행당동
478   성수동1가
479   금호동4가
480   하왕십리동
481   성수동2가
482     용답동
483   금호동1가
484   금호동3가
485   금호동2가
486     마장동
487   상왕십리동
488     옥수동
489     홍익동
490     송정동
491     사근동
492     응봉동
493    221동
494      상가
495    121동
496     송월동

[497 rows x 1 columns]>

In [47]:
year = 2007
df_2007 = df_seoul.loc[(df_seoul['영업자시작년도'] <= year) & ((df_seoul['폐업년도'] > year) | (df_seoul['폐업년도'].isnull()))]

In [48]:
df_2007.head()

,address,lat,lng,구,년도,업소명,업종명,업태명,영업자시작년도,영업자시작일,폐업년도,폐업일자,area
29,서울특별시 은평구 수색동 366번지 5호 1층,37.582849,126.894692,은평구,2000.0,왕냉면왕돈까스,일반음식점,경양식,2007.0,20070802.0,NaN,NaN,수색동
134,서울특별시 은평구 응암동 591번지 39호 1층,37.589626,126.915108,은평구,2007.0,부연참숯정육식당,일반음식점,한식,2007.0,20070530.0,NaN,NaN,응암동
136,서울특별시 은평구 신사동 7번지 24호 -,37.601684,126.910843,은평구,1999.0,퓨전대박이네,일반음식점,호프/통닭,2007.0,20070523.0,2008.0,20080529.0,신사동
139,서울특별시 은평구 응암동 593번지 31호 1층,37.587585,126.914198,은평구,1999.0,오대감연탄갈비,일반음식점,한식,2007.0,20071008.0,NaN,NaN,응암동
150,서울특별시 은평구 녹번동 79번지 42호 1층,37.602234,126.930281,은평구,2000.0,한솥도시락,일반음식점,분식,2007.0,20070109.0,NaN,NaN,녹번동

In [28]:
df_2007.columns

Index(['address', 'lat', 'lng', '구', '년도', '업소명', '업종명', '업태명', '영업자시작년도',
       '영업자시작일', '폐업년도', '폐업일자', 'area'],
      dtype='object')

In [49]:
df_2007 = df_2007.drop(['address', 'lat', 'lng', '구', '년도', '업소명', '업종명', '업태명'], axis=1)

In [57]:
area_counts = {}
for area in df_2007['area']:
    if area not in area_counts.keys():
        area_counts[area] = 1
    else:
        area_counts[area] += 1

In [58]:
area_counts

{'수색동': 11,
 '응암동': 82,
 '신사동': 698,
 '녹번동': 32,
 '갈현동': 75,
 '역촌동': 42,
 '불광동': 45,
 '대조동': 70,
 '구산동': 17,
 '증산동': 13,
 '진관동': 7,
 '인사동': 7,
 '계동': 4,
 '공평동': 6,
 '재동': 3,
 '혜화동': 9,
 '원남동': 2,
 '평창동': 17,
 '명륜4가': 16,
 '관훈동': 11,
 '연건동': 8,
 '창신동': 37,
 '종로3가': 3,
 '청진동': 24,
 '평동': 1,
 '연지동': 6,
 '수송동': 15,
 '낙원동': 12,
 '묘동': 9,
 '인의동': 13,
 '무악동': 6,
 '화동': 2,
 '봉익동': 8,
 '종로6가': 7,
 '동숭동': 21,
 '명륜2가': 20,
 '필운동': 5,
 '종로2가': 16,
 '삼청동': 14,
 '내수동': 19,
 '당주동': 8,
 '구기동': 12,
 '종로5가': 14,
 '운니동': 5,
 '와룡동': 4,
 '교남동': 5,
 '홍파동': 1,
 '적선동': 9,
 '중학동': 1,
 '통의동': 5,
 '신문로2가': 6,
 '장사동': 2,
 '숭인동': 20,
 '원서동': 2,
 '서린동': 2,
 '부암동': 9,
 '홍지동': 4,
 '돈의동': 7,
 '도렴동': 6,
 '소격동': 7,
 '종로4가': 4,
 '권농동': 2,
 '청운동': 2,
 '신문로1가': 6,
 '효제동': 9,
 '체부동': 3,
 '종로1가': 10,
 '관철동': 15,
 '관수동': 7,
 '교북동': 3,
 '명륜3가': 2,
 '안국동': 3,
 '견지동': 1,
 '명륜1가': 1,
 '문정동': 300,
 '방이동': 482,
 '석촌동': 354,
 '거여동': 245,
 '마천동': 284,
 '신천동': 182,
 '잠실동': 729,
 '송파동': 321,
 '가락동': 607,
 '오금동': 254,
 '풍납동': 220,
 '삼전동': 251,
 '장지동': 13,
 '신정동': 752,
 '목동': 815,
 '신월동': 604,
 '문래동3가': 97,
 '여의도동': 777,
 '양평동4가': 82,
 '신길동': 630,
 '영등포동': 134,
 '대림동': 545,
 '영등포동7가': 107,
 '당산동4가': 60,
 '양평동6가': 16,
 '영등포동3가': 163,
 '당산동5가': 41,
 '도림동': 151,
 '문래동1가': 28,
 '문래동6가': 29,
 '양평동1가': 92,
 '문래동4가': 35,
 '당산동6가': 70,
 '양평동2가': 47,
 '영등포동4가': 115,
 '당산동': 38,
 '당산동3가': 113,
 '양평동3가': 37,
 '영등포동6가': 69,
 '영등포동1가': 23,
 '당산동1가': 98,
 '영등포동2가': 119,
 '당산동2가': 46,
 '양평동5가': 17,
 '문래동5가': 11,
 '영등포동8가': 41,
 '영등포동5가': 95,
 '문래동2가': 46,
 '양평동': 1,
 '양화동': 3,
 '신영동': 3,
 '선유동': 1,
 '중화동': 65,
 '면목동': 197,
 '망우동': 66,
 '신내동': 41,
 '묵동': 37,
 '상봉동': 74,
 '도곡동': 229,
 '논현동': 564,
 '개포동': 238,
 '역삼동': 982,
 '청담동': 323,
 '대치동': 571,
 '일원동': 87,
 '삼성동': 488,
 '압구정동': 120,
 '수서동': 68,
 '율현동': 8,
 '세곡동': 6,
 '화곡동': 1192,
 '등촌동': 403,
 '공항동': 197,
 '내발산동': 190,
 '가양동': 130,
 '염창동': 101,
 '방화동': 449,
 '과해동': 11,
 '마곡동': 29,
 '외발산동': 18,
 '개화동': 2,
 '번동': 252,
 '수유동': 630,
 '미아동': 759,
 '우이동': 71,
 '도선동': 78,
 '둔촌동': 165,
 '명일동': 338,
 '상일동': 114,
 '길동': 422,
 '성내동': 757,
 '암사동': 326,
 '고덕동': 122,
 '천호동': 685,
 '강일동': 21,
 '신림동': 1669,
 '남현동': 114,
 '봉천동': 1235,
 '충무로2가': 13,
 '인현동1가': 6,
 '북창동': 10,
 '태평로2가': 10,
 '남대문로5가': 18,
 '다동': 16,
 '장충동2가': 19,
 '명동2가': 28,
 '저동2가': 9,
 '쌍림동': 5,
 '충무로3가': 7,
 '예관동': 4,
 '오장동': 6,
 '인현동2가': 5,
 '충무로4가': 5,
 '충무로1가': 31,
 '만리동1가': 3,
 '신당동': 94,
 '회현동1가': 9,
 '저동1가': 6,
 '광희동1가': 10,
 '을지로1가': 3,
 '장교동': 5,
 '황학동': 25,
 '순화동': 14,
 '수하동': 2,
 '남창동': 6,
 '서소문동': 5,
 '묵정동': 4,
 '장충동1가': 4,
 '무교동': 7,
 '을지로3가': 3,
 '회현동2가': 3,
 '필동1가': 4,
 '을지로2가': 11,
 '주교동': 7,
 '초동': 3,
 '무학동': 6,
 '남산동2가': 10,
 '수표동': 2,
 '남대문로3가': 2,
 '필동2가': 7,
 '을지로6가': 23,
 '흥인동': 7,
 '중림동': 30,
 '산림동': 3,
 '봉래동1가': 3,
 '태평로1가': 4,
 '정동': 4,
 '남산동1가': 3,
 '남대문로2가': 4,
 '충무로5가': 2,
 '만리동2가': 6,
 '소공동': 17,
 '예장동': 1,
 '회현동3가': 1,
 '을지로4가': 2,
 '필동3가': 4,
 '명동1가': 6,
 '남산동3가': 1,
 '광희동2가': 1,
 '남대문로4가': 3,
 '입정동': 2,
 '충정로1가': 1,
 '구로동': 1317,
 '신도림동': 150,
 '오류동': 242,
 '개봉동': 408,
 '천왕동': 6,
 '가리봉동': 175,
 '고척동': 323,
 '온수동': 52,
 '궁동': 52,
 '항동': 7,
 '창동': 609,
 '도봉동': 383,
 '방학동': 490,
 '쌍문동': 345,
 '독산동': 885,
 '가산동': 327,
 '시흥동': 806,
 '화양동': 284,
 '자양동': 551,
 '구의동': 468,
 '군자동': 146,
 '중곡동': 424,
 '능동': 48,
 '광장동': 99,
 '상계동': 923,
 '공릉동': 345,
 '하계동': 117,
 '월계동': 260,
 '중계동': 416,
 '갈월동': 12,
 '한남동': 40,
 '후암동': 7,
 '원효로3가': 5,
 '한강로2가': 34,
 '청파동2가': 10,
 '청파동3가': 8,
 '한강로3가': 42,
 '용산동2가': 11,
 '용산동3가': 3,
 '이촌동': 18,
 '이태원동': 41,
 '청파동1가': 2,
 '용문동': 9,
 '동빙고동': 2,
 '원효로2가': 8,
 '신계동': 10,
 '서계동': 6,
 '남영동': 15,
 '동자동': 18,
 '보광동': 12,
 '원효로1가': 5,
 '도원동': 2,
 '원효로4가': 1,
 '한강로1가': 7,
 '산천동': 3,
 '문배동': 2,
 '효창동': 1,
 '답십리동': 360,
 '회기동': 204,
 '용두동': 356,
 '청량리동': 212,
 '장안동': 665,
 '전농동': 389,
 '제기동': 357,
 '이문동': 279,
 '휘경동': 190,
 '신설동': 115,
 '노량진동': 325,
 '신대방동': 288,
 '흑석동': 197,
 '상도1동': 66,
 '사당동': 578,
 '동작동': 15,
 '상도동': 472,
 '대방동': 156,
 '본동': 45,
 '서교동': 533,
 '염리동': 132,
 '공덕동': 289,
 '도화동': 264,
 '망원동': 250,
 '창전동': 65,
 '연남동': 81,
 '마포동': 35,
 '동교동': 180,
 '용강동': 106,
 '합정동': 200,
 '신수동': 115,
 '성산동': 211,
 '상수동': 84,
 '대흥동': 155,
 '아현동': 191,
 '노고산동': 170,
 '상암동': 100,
 '신공덕동': 73,
 '중동': 25,
 '현석동': 8,
 '구수동': 14,
 '토정동': 2,
 '서초동': 1237,
 '방배동': 812,
 '반포동': 610,
 '양재동': 607,
 '잠원동': 335,
 '신원동': 22,
 '우면동': 46,
 '창천동': 422,
 '연희동': 174,
 '대현동': 238,
 '북아현동': 210,
 '홍제동': 299,
 '남가좌동': 499,
 '홍은동': 236,
 '북가좌동': 211,
 '미근동': 41,
 '냉천동': 40,
 '대신동': 38,
 '합동': 4,
 '영천동': 25,
 '충정로3가': 73,
 '충정로2가': 49,
 '신촌동': 39,
 '옥천동': 7,
 '현저동': 10,
 '천연동': 11,
 '봉원동': 1,
 '길음동': 222,
 '성북동': 57,
 '동선동4가': 38,
 '종암동': 183,
 '석관동': 223,
 '하월곡동': 269,
 '장위동': 408,
 '삼선동5가': 32,
 '동선동2가': 46,
 '동선동3가': 17,
 '정릉동': 321,
 '삼선동4가': 28,
 '삼선동2가': 52,
 '보문동4가': 22,
 '삼선동1가': 30,
 '상월곡동': 41,
 '안암동5가': 134,
 '동소문동3가': 10,
 '동소문동7가': 12,
 '보문동5가': 14,
 '성북동1가': 9,
 '동소문동5가': 37,
 '동선동5가': 14,
 '보문동2가': 10,
 '보문동7가': 24,
 '동선동1가': 106,
 '돈암동': 69,
 '안암동4가': 12,
 '보문동6가': 6,
 '동소문동1가': 12,
 '동소문동2가': 35,
 '보문동1가': 21,
 '안암동2가': 7,
 '동소문동4가': 9,
 '동소문동6가': 13,
 '안암동1가': 6,
 '삼선동3가': 6,
 '안암동3가': 5,
 '보문동3가': 2,
 '성수동2가': 353,
 '금호동3가': 59,
 '금호동2가': 78,
 '마장동': 110,
 '하왕십리동': 116,
 '용답동': 149,
 '옥수동': 90,
 '홍익동': 51,
 '금호동1가': 61,
 '행당동': 271,
 '성수동1가': 194,
 '금호동4가': 67,
 '상왕십리동': 70,
 '응봉동': 25,
 '송정동': 26,
 '사근동': 14,
 '당인동': 1,
 '원지동': 26,
 '내곡동': 25,
 '염곡동': 6,
 '가회동': 2,
 nan: 3,
 '경운동': 1,
 '익선동': 1,
 '옥인동': 2,
 '누하동': 1,
 '창성동': 1}

In [101]:
try_df = pd.DataFrame(index=None)

In [102]:
try_df['area'] = area_counts.keys()
try_df.head()

  area
0  수색동
1  응암동
2  신사동
3  녹번동
4  갈현동

In [103]:
try_df[2007] = area_counts.values()

In [104]:
try_df.head()

  area  2007
0  수색동    11
1  응암동    82
2  신사동   698
3  녹번동    32
4  갈현동    75

In [26]:
seoul_area = {}
for area in df_2007['area']:
    if area not in seoul_area.keys():
        seoul_area[area] = 1
    else:
        seoul_area[area] += 1

In [108]:
df_2007 = pd.DataFrame()
df_2007['area'] = area_counts.keys()
df_2007[2007] = area_counts.values()

In [109]:
df_2007.head()

  area  2007
0  수색동    11
1  응암동    82
2  신사동   698
3  녹번동    32
4  갈현동    75

In [110]:
seoul.merge(df_2007, on='area')

       area  2007
0       신사동   698
1       수색동    11
2       대조동    70
3       갈현동    75
4       응암동    82
5       녹번동    32
6       역촌동    42
7       진관동     7
8       불광동    45
9       구산동    17
10      증산동    13
11      관훈동    11
12      부암동     9
13      창신동    37
14     명륜4가    16
15       계동     4
16      삼청동    14
17     명륜3가     2
18      익선동     1
19     종로3가     3
20      수송동    15
21     명륜2가    20
22      관철동    15
23      도렴동     6
24      숭인동    20
25      가회동     2
26      관수동     7
27      견지동     1
28      인사동     7
29      통의동     5
..      ...   ...
398   동선동4가    38
399   동선동2가    46
400  동소문동7가    12
401   보문동5가    14
402   동선동5가    14
403   안암동4가    12
404   보문동6가     6
405  동소문동1가    12
406   보문동1가    21
407   안암동2가     7
408  동소문동4가     9
409   안암동1가     6
410   안암동3가     5
411   보문동3가     2
412     행당동   271
413   성수동1가   194
414   금호동4가    67
415   하왕십리동   116
416   성수동2가   353
417     용답동   149
418   금호동1가    61
419   금호동3가    59
420   금호동2가    78
421     마장동   110
422   상왕십리동    70
423     옥수동    90
424     홍익동    51
425     송정동    26
426     사근동    14
427     응봉동    25

[428 rows x 2 columns]

In [22]:
def seoul_shops(df, year, result):
    df_year = df.loc[(df['영업자시작년도'] <= year) & ((df['폐업년도'] > year) | (df['폐업년도'].isnull()))]
    
    seoul_area = {}
    for area in df_year['area']:
        if area not in seoul_area.keys():
            seoul_area[area] = 1
        else:
            seoul_area[area] += 1
            
    result2 = result.merge(df_year, on='area')
    
    return result2

In [23]:

for year in range(2007, 2008):
    result = seoul_shops(df_seoul, year, seoul)
    
result

,area,address,lat,lng,구,년도,업소명,업종명,업태명,영업자시작년도,영업자시작일,폐업년도,폐업일자
0,신사동,서울특별시 은평구 신사동 7번지 24호 -,37.601684,126.910843,은평구,1999.0,퓨전대박이네,일반음식점,호프/통닭,2007.0,20070523.0,2008.0,20080529.0
1,신사동,서울특별시 은평구 신사동 16번지 15호,37.600405,126.909677,은평구,1999.0,BBQ치킨(신사1동점),일반음식점,통닭(치킨),2007.0,20070626.0,2012.0,20120613.0
2,신사동,서울특별시 은평구 신사동 22번지 1호 (1층),37.598604,126.914486,은평구,2000.0,만선회,일반음식점,한식,2007.0,20070416.0,2009.0,20090406.0
3,신사동,서울특별시 은평구 신사동 2번지 20호 (지하1층),37.599353,126.914567,은평구,1998.0,베르사체,일반음식점,경양식,2007.0,20070611.0,2010.0,20100628.0
4,신사동,서울특별시 은평구 신사동 15번지 42호 (1층),37.599832,126.909423,은평구,2007.0,꼬지와친구들,일반음식점,정종/대포집/소주방,2007.0,20070523.0,2009.0,20091008.0
5,신사동,서울특별시 은평구 신사동 34번지 8호 2층,37.601454,126.903179,은평구,2002.0,효면옥,일반음식점,한식,2007.0,20070405.0,NaN,NaN
6,신사동,서울특별시 은평구 신사동 19번지 153호 (1층),37.599235,126.907658,은평구,2003.0,취하는건 바다,일반음식점,일식,2007.0,20070312.0,2009.0,20090420.0
7,신사동,서울특별시 은평구 신사동 337번지 3호 (지상2층),37.591577,126.913452,은평구,2004.0,주가박당,일반음식점,호프/통닭,2007.0,20071106.0,2009.0,20090202.0
8,신사동,서울특별시 은평구 신사동 228번지 7호 1층,37.596668,126.908554,은평구,2007.0,뚱땡이 해장국,일반음식점,한식,2007.0,20070803.0,2013.0,20130321.0
9,신사동,서울특별시 은평구 신사동 344번지 7호 (지하1층),37.590200,126.909013,은평구,2001.0,수흘스흘,일반음식점,통닭(치킨),2007.0,20070719.0,2008.0,20080714.0
10,신사동,서울특별시 은평구 신사동 9번지 21호 (지상1층),37.601892,126.910174,은평구,2004.0,참새 방앗간,일반음식점,한식,2007.0,20071210.0,2008.0,20081222.0
11,신사동,서울특별시 은평구 신사동 23번지 14호 1층,37.598833,126.915310,은평구,2005.0,좋은식당,일반음식점,한식,2007.0,20070201.0,NaN,NaN
12,신사동,서울특별시 은평구 신사동 193번지 4호 (지상1층),37.592196,126.906696,은평구,2005.0,임승아순대국,일반음식점,분식,2007.0,20070125.0,2009.0,20090715.0
13,신사동,서울특별시 은평구 신사동 29번지 122호 외 1필지 1층,37.598112,126.911831,은평구,2007.0,먹고나보자,일반음식점,한식,2007.0,20070914.0,2015.0,20151202.0
14,신사동,서울특별시 은평구 신사동 191번지 3호 외 1필지,37.592135,126.905701,은평구,2002.0,뱀골식당,일반음식점,분식,2007.0,20070511.0,2008.0,20080215.0
15,신사동,서울특별시 은평구 신사동 15번지 3호 1층,37.599832,126.909423,은평구,2004.0,미그래,일반음식점,한식,2007.0,20070328.0,2017.0,20170131.0
16,신사동,서울특별시 은평구 신사동 3번지 16호 (2층),37.599065,126.913680,은평구,2007.0,벽돌속두꺼비,일반음식점,호프/통닭,2007.0,20070112.0,2008.0,20080324.0
17,신사동,서울특별시 은평구 신사동 35번지 20호 (1층),37.601593,126.903637,은평구,2007.0,대부도조개구이,일반음식점,기타,2007.0,20070115.0,2009.0,20090728.0
18,신사동,서울특별시 은평구 신사동 29번지 120호 1층,37.598112,126.911831,은평구,2006.0,생선이랑,일반음식점,한식,2007.0,20070731.0,2008.0,20080618.0
19,신사동,서울특별시 은평구 신사동 341번지 31호 1층,37.590332,126.911744,은평구,2007.0,크림,일반음식점,호프/통닭,2007.0,20070418.0,2017.0,20170613.0
20,신사동,서울특별시 은평구 신사동 15번지 59호 (1층),37.599832,126.909423,은평구,2003.0,명숯불갈비,일반음식점,한식,2007.0,20070330.0,2009.0,20090410.0
21,신사동,서울특별시 은평구 신사동 19번지 145호 (지상2층),37.599235,126.907658,은평구,2003.0,신사촌,일반음식점,한식,2007.0,20070809.0,2010.0,20100511.0
22,신사동,서울특별시 은평구 신사동 345번지 2호,37.590284,126.908733,은평구,2007.0,보양집,일반음식점,한식,2007.0,20070502.0,2012.0,20121203.0
23,신사동,서울특별시 은평구 신사동 339번지 2호,37.589021,126.912784,은평구,1991.0,테이크아웃오후,일반음식점,한식,2007.0,20070917.0,2012.0,20120202.0
24,신사동,서울특별시 은평구 신사동 19번지 153호,37.599235,126.907658,은평구,1987.0,취하는건 바다,일반음식점,일식,2007.0,20070312.0,2011.0,20110401.0
25,신사동,서울특별시 은평구 신사동 335번지 29호,37.592681,126.913547,은평구,1992.0,미스터피자(은평신사점),일반음식점,패스트푸드,2007.0,20070612.0,2008.0,20080708.0
26,신사동,서울특별시 은평구 신사동 19번지 100호 지하 1층,37.599235,126.907658,은평구,2007.0,낙원,휴게음식점,다방,2007.0,20070323.0,2012.0,20120629.0
27,신사동,서울특별시 강남구 신사동 639번지 10호 지상1층,37.528697,127.035813,강남구,2007.0,디가든,일반음식점,경양식,2007.0,20070227.0,2008.0,20080115.0
28,신사동,서울특별시 강남구 신사동 629번지 19호 101호,37.521669,127.031546,강남구,2007.0,일씨에로,일반음식점,경양식,2007.0,20070228.0,2009.0,20090310.0
29,신사동,서울특별시 강남구 신사동 661번지 12호 지상1층,37.528020,127.038542,강남구,2007.0,울화통2060,일반음식점,한식,2007.0,20070221.0,2008.0,20081014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57397,사근동,서울특별시 성동구 사근동 176번지 41호,37.560732,127.046515,성동구,1994.0,멕시칸치킨,일반음식점,통닭(치킨),2001.0,20010828.0,2016.0,20160218.0
57398,사근동,서울특별시 성동구 사근동 204번지 2호,37.561326,127.047948,성동구,1997.0,고향칼국수,일반음식점,한식,1998.0,19980901.0,NaN,NaN
57399,사근동,서울특별시 성동구 사근동 179번지 2호 (지상1층),37.560718,127.047384,성동구,2002.0,자매식당,일반음식점,한식,2002.0,20020520.0,2017.0,20170220.0
57400,사근동,서울특별시 성동구 사근동 176번지 32호,37.560732,127.046515,성동구,1989.0,박가네숯불갈비,일반음식점,한식,2004.0,20041112.0,2015.0,20151228.0
57401,사근동,서울특별시 성동구 사근동 298번지,37.561022,127.045740,성동구,2001.0,해성식당,일반음식점,한식,2001.0,20010328.0,NaN,NaN
57402,응봉동,서울특별시 성동구 응봉동 191번지 24호 (지상1층),37.550324,127.033009,성동구,2004.0,우리들분식,일반음식점,분식,2004.0,20040930.0,2010.0,20101101.0
57403,응봉동,서울특별시 성동구 응봉동 193번지 120호 (지상1층),37.551029,127.034099,성동구,2005.0,비버스,일반음식점,패스트푸드,2005.0,20051229.0,2008.0,20080811.0
57404,응봉동,서울특별시 성동구 응봉동 275번지 신동아아파트상가 103호,37.550419,127.029561,성동구,1999.0,치킨더홈성동점,일반음식점,중국식,1999.0,19990605.0,2008.0,20080620.0
57405,응봉동,서울특별시 성동구 응봉동 228번지 28호,37.552129,127.035861,성동구,2002.0,쨍기네곱창,일반음식점,기타,2005.0,20051209.0,2011.0,20110930.0
57406,응봉동,서울특별시 성동구 응봉동 100번지 대림노선상가 302호,37.551618,127.033026,성동구,2001.0,명물왕만두,일반음식점,분식,2006.0,20060609.0,2013.0,20130125.0
57407,응봉동,서울특별시 성동구 응봉동 228번지 20호 (지상1층),37.552129,127.035861,성동구,2006.0,풍천장어마을,일반음식점,한식,2007.0,20071119.0,2015.0,20150331.0
57408,응봉동,서울특별시 성동구 응봉동 98번지 현대상가1층 106호,37.551199,127.031053,성동구,2002.0,두꺼비전쟁,일반음식점,호프/통닭,2005.0,20050708.0,2008.0,20080314.0
57409,응봉동,서울특별시 성동구 응봉동 228번지 28호,37.552129,127.035861,성동구,1998.0,오십구년왕십리갈비촌,일반음식점,한식,2002.0,20020510.0,2012.0,20120221.0
57410,응봉동,서울특별시 성동구 응봉동 100번지 (노선상가308호),37.551618,127.033026,성동구,2002.0,로터스,일반음식점,호프/통닭,2003.0,20030729.0,2008.0,20080730.0
57411,응봉동,서울특별시 성동구 응봉동 193번지 193호,37.551029,127.034099,성동구,2000.0,행복수산,일반음식점,일식,2001.0,20010404.0,NaN,NaN
57412,응봉동,서울특별시 성동구 응봉동 100번지 대림종합상가 2층2호,37.551618,127.033026,성동구,1999.0,B.B.Q치킨(응봉점),일반음식점,통닭(치킨),1999.0,19990906.0,2008.0,20080724.0
57413,응봉동,서울특별시 성동구 응봉동 228번지 35호 지상1층,37.552129,127.035861,성동구,2006.0,즉석김밥,휴게음식점,일반조리판매,2006.0,20060908.0,2008.0,20080808.0
57414,응봉동,서울특별시 성동구 응봉동 265번지 17호 지상1층,37.552896,127.031813,성동구,2006.0,알퐁소,휴게음식점,패스트푸드,2006.0,20061031.0,2008.0,20080108.0
57415,응봉동,서울특별시 성동구 응봉동 201번지 14호 지상1층,37.549790,127.032003,성동구,2007.0,썬더치킨,일반음식점,통닭(치킨),2007.0,20071015.0,2009.0,20090921.0
57416,응봉동,"서울특별시 성동구 응봉동 228번지 12호 ,13,18",37.552129,127.035861,성동구,1993.0,성수식당,일반음식점,한식,1999.0,19991220.0,2011.0,20110517.0
57417,응봉동,서울특별시 성동구 응봉동 100번지 대림상가 (지하23호),37.551618,127.033026,성동구,1989.0,대림분식,일반음식점,분식,2003.0,20030929.0,2008.0,20080125.0
57418,응봉동,서울특별시 성동구 응봉동 265번지 56호,37.552896,127.031813,성동구,1996.0,부여식당,일반음식점,한식,2003.0,20030714.0,2010.0,20100705.0
57419,응봉동,서울특별시 성동구 응봉동 228번지 15호,37.552129,127.035861,성동구,1993.0,민속마당,일반음식점,한식,2005.0,20051115.0,2008.0,20080812.0
57420,응봉동,서울특별시 성동구 응봉동 191번지 13호 (지상1층),37.550324,127.033009,성동구,2005.0,태양분식,휴게음식점,일반조리판매,2005.0,20050414.0,NaN,NaN
57421,응봉동,서울특별시 성동구 응봉동 228번지 25호,37.552129,127.035861,성동구,2001.0,치킨주막,일반음식점,호프/통닭,2007.0,20070702.0,NaN,NaN
57422,응봉동,서울특별시 성동구 응봉동 98번지 현대(아)상가 지1층14호,37.551199,127.031053,성동구,2001.0,북경,일반음식점,중국식,2007.0,20070409.0,2013.0,20130902.0
57423,응봉동,"서울특별시 성동구 응봉동 15번지 대림강변타운A상가306,307호",37.553475,127.035825,성동구,2001.0,태화루,일반음식점,중국식,2003.0,20030701.0,2013.0,20130902.0
57424,응봉동,서울특별시 성동구 응봉동 193번지 79호,37.551029,127.034099,성동구,1987.0,청기와,일반음식점,한식,1993.0,19930513.0,2016.0,20160824.0
57425,응봉동,서울특별시 성동구 응봉동 100번지 대림종합상가-209,37.551618,127.033026,성동구,1995.0,뺑드비제과(응봉점),제과점영업,제과점영업,1995.0,19950324.0,2014.0,20140527.0
57426,응봉동,서울특별시 성동구 응봉동 193번지 118호,37.551029,127.034099,성동구,1991.0,처갓집양념치킨 응봉점,일반음식점,통닭(치킨),2005.0,20050425.0,NaN,NaN

In [ ]:
for year in range(2008, 2009):
    seoul_shops(df_seoul, year, seoul)

In [ ]:
seoul.head()

In [ ]:
import seaborn as sns
import matplotlib as plt

sns.set(font="NanumGothic")
plt.pyplot.subplots(figsize=(80,600))
ax = sns.heatmap(seoul,  cmap='Blues')
ax.figure.savefig("output_increase.png")

In [ ]:
def seoul_dataframe(df, year):
    df_year = df.loc[(df['영업자시작년도'] <= year) & ((df['폐업년도'] > year) | df['폐업년도'].isnull())]

    seoul_area = {}
    for area in df_year['area']:
        if area not in seoul_area.keys():
            seoul_area[area] = 0
        else:
            seoul_area[area] += 1

    seoul = pd.DataFrame()
    seoul['area'] = seoul_area.keys()
    seoul[str(year)] = seoul_area.values()

    return seoul

In [ ]:
seoul_dataframe(df, 2008)

In [ ]:
df_seoul_2007 = seoul_map(df, 2007)

(ggplot(df_seoul_2007[['lng', 'lat']])
 + aes(x='lng', y='lat')
 + geom_point(size=0.01, alpha=0.01, color='red')
 + ggtitle('2007년 서울')
 + theme(text=element_text(family=font_name))
)

In [ ]:
df_seoul_2017 = seoul_map(df, 2017)

(ggplot(df_seoul_2017[['lng', 'lat']])
 + aes(x='lng', y='lat')
 + geom_point(size=0.01, alpha=0.01, color='red')
 + ggtitle('2017년 서울')
 + theme(text=element_text(family=font_name))

)

In [ ]:
df_dj_2007 = seoul_map(df, 2007, area='동작구')

(ggplot(df_dj_2007[['lng', 'lat']])
 + aes(x='lng', y='lat')
 + geom_point(size=0.01, alpha=0.1, color='red')
 + ggtitle('2007년 서울 동작구')
 + theme(text=element_text(family=font_name))
)

In [ ]:
df_dj_2017 = seoul_map(df, 2017, area='동작구')

(ggplot(df_dj_2017[['lng', 'lat']])
 + aes(x='lng', y='lat')
 + geom_point(size=0.01, alpha=0.1, color='red')
 + ggtitle('2017년 서울 동작구')
 + theme(text=element_text(family=font_name))
)

In [ ]:
df_yn_2007 = seoul_map(df, 2007, place='연남동')

(ggplot(df_yn_2007[['lng', 'lat']])
 + aes(x='lng', y='lat')
 + geom_point(size=0.01, alpha=0.1, color='red')
 + ggtitle('2007년 서울 연남동')
 + theme(text=element_text(family=font_name))
)

In [ ]:
df_yn_2017 = seoul_map(df, 2017, place='연남동')

(ggplot(df_yn_2017[['lng', 'lat']])
 + aes(x='lng', y='lat')
 + geom_point(size=0.01, alpha=0.1, color='red')
 + ggtitle('2017년 서울 연남동')
 + theme(text=element_text(family=font_name))
)