In [1]:
import pandas as pd

In [2]:
import numpy as np

In [31]:
sub = pd.read_csv('data/2008.csv', encoding = 'cp949')
sub.head()

,날짜,역번호,역명,구분,05~06,06~07,07~08,08~09,09~10,10~11,...,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,24~
0,2008-01-01,150,서울역(150),승차,379,287,371,876,965,"1,389",...,"2,520","3,078","3,495","3,055","2,952","2,726","3,307","2,584","1,059",264
1,2008-01-01,150,서울역(150),하차,145,707,689,"1,037","1,170","1,376",...,"1,955","2,304","2,203","2,128","1,747","1,593","1,078",744,406,558
2,2008-01-01,151,시청(151),승차,131,131,101,152,191,202,...,892,900,"1,154","1,706","1,444","1,267",928,531,233,974
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,"1,157","1,153","1,303","1,190",830,454,284,141,107,185
4,2008-01-01,152,종각(152),승차,"1,287",867,400,330,345,338,...,"1,867","2,269","2,777","2,834","2,646","2,784","2,920","2,290",802,"1,559"

In [33]:
sub['역명'] = sub['역명'].str.replace(' ','')
sub['구분'] = sub['구분'].str.replace(' ','')
sub.head()

,날짜,역번호,역명,구분,05~06,06~07,07~08,08~09,09~10,10~11,...,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,24~
0,2008-01-01,150,서울역(150),승차,379,287,371,876,965,"1,389",...,"2,520","3,078","3,495","3,055","2,952","2,726","3,307","2,584","1,059",264
1,2008-01-01,150,서울역(150),하차,145,707,689,"1,037","1,170","1,376",...,"1,955","2,304","2,203","2,128","1,747","1,593","1,078",744,406,558
2,2008-01-01,151,시청(151),승차,131,131,101,152,191,202,...,892,900,"1,154","1,706","1,444","1,267",928,531,233,974
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,"1,157","1,153","1,303","1,190",830,454,284,141,107,185
4,2008-01-01,152,종각(152),승차,"1,287",867,400,330,345,338,...,"1,867","2,269","2,777","2,834","2,646","2,784","2,920","2,290",802,"1,559"

In [34]:
sub['구분'].value_counts()

승차    96087
하차    96087
Name: 구분, dtype: int64

In [35]:
sub.to_csv('data/2008.csv', index=False)

In [32]:
sub.columns

Index(['날짜', '역번호', '역명', '구분', ' 05~06 ', ' 06~07 ', ' 07~08 ', ' 08~09 ',
       ' 09~10 ', ' 10~11 ', ' 11~12 ', ' 12~13 ', ' 13~14 ', ' 14~15 ',
       ' 15~16 ', ' 16~17 ', ' 17~18 ', ' 18~19 ', ' 19~20 ', ' 20~21 ',
       ' 21~22 ', ' 22~23 ', ' 23~24 ', ' 24~ '],
      dtype='object')

In [30]:
sub = sub.loc[sub['구분']=='하차']

In [7]:
sub.dtypes

 날짜        object
 역번호        int64
 역명        object
 구분        object
 05~06     object
 06~07     object
 07~08     object
 08~09     object
 09~10     object
 10~11     object
 11~12     object
 12~13     object
 13~14     object
 14~15     object
 15~16     object
 16~17     object
 17~18     object
 18~19     object
 19~20     object
 20~21     object
 21~22     object
 22~23     object
 23~24     object
 24~       object
dtype: object

In [97]:
sub

,날짜,역번호,역명,구분,05~06,06~07,07~08,08~09,09~10,10~11,...,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,24~
1,2008-01-01,150,서울역(150),하차,145,707,689,"1,037","1,170","1,376",...,"1,955","2,304","2,203","2,128","1,747","1,593","1,078",744,406,558
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,"1,157","1,153","1,303","1,190",830,454,284,141,107,185
5,2008-01-01,152,종각(152),하차,74,147,261,473,597,698,...,"2,161","2,298","2,360","1,997","1,217",799,461,271,134,210
7,2008-01-01,153,종로3가(153),하차,28,80,116,238,390,609,...,"1,991","1,896","1,543","1,160",926,431,324,190,127,384
9,2008-01-01,154,종로5가(154),하차,14,76,93,123,137,193,...,445,399,393,272,190,167,138,125,104,42
11,2008-01-01,155,동대문(155),하차,23,111,120,150,299,331,...,"1,061",987,891,757,578,451,500,426,231,221
13,2008-01-01,156,신설동(156),하차,15,98,81,112,166,202,...,324,347,394,397,321,297,332,279,186,89
15,2008-01-01,157,제기동(157),하차,16,84,84,175,256,384,...,747,561,434,373,333,268,247,236,148,85
17,2008-01-01,158,청량리(지하)(158),하차,56,428,510,522,872,"1,059",...,"1,848","1,698","1,777","1,410","1,254","1,147","1,068",900,546,403
19,2008-01-01,159,동묘앞(159),하차,3,45,54,84,96,132,...,371,309,184,158,101,128,106,117,86,61
21,2008-01-01,201,시청(201),하차,29,107,131,196,262,237,...,794,757,795,799,456,385,200,113,70,148
23,2008-01-01,202,을지로입구(202),하차,31,176,278,565,547,813,...,"1,712","1,621","1,448","1,080",521,335,206,112,48,219
25,2008-01-01,203,을지로3가(203),하차,12,81,79,251,428,470,...,240,203,204,189,105,87,60,48,30,34
27,2008-01-01,204,을지로4가(204),하차,8,45,34,85,60,77,...,137,95,86,78,75,48,52,37,24,32
29,2008-01-01,205,동대문운동장(205),하차,24,100,102,168,242,377,...,"1,010",973,895,729,636,448,380,298,232,151
31,2008-01-01,206,신당(206),하차,21,155,103,138,180,198,...,522,459,459,528,429,344,398,329,261,91
33,2008-01-01,207,상왕십리(207),하차,23,123,103,108,147,149,...,300,341,385,379,334,355,366,356,202,82
35,2008-01-01,208,왕십리(208),하차,28,145,102,125,169,167,...,369,444,468,498,450,438,480,488,339,125
37,2008-01-01,209,한양대(209),하차,10,82,58,75,170,162,...,294,226,258,245,196,208,229,198,141,35
39,2008-01-01,210,뚝섬(210),하차,18,139,98,170,183,174,...,321,412,410,417,463,370,424,465,272,115
41,2008-01-01,211,성수(211),하차,20,167,142,220,237,203,...,348,404,500,468,406,390,416,339,405,256
43,2008-01-01,212,건대입구(212),하차,37,341,280,434,653,645,...,"1,920","2,125","2,472","2,634","2,114","1,652","1,606","1,504",892,351
45,2008-01-01,213,구의(213),하차,29,226,159,205,277,314,...,515,680,739,825,711,671,746,743,493,93
47,2008-01-01,214,강변(214),하차,122,"1,125","1,009",913,"1,239","1,404",...,"2,930","3,607","3,299","2,668","2,564","1,835","1,416","1,144",755,132
49,2008-01-01,215,성내(215),하차,33,164,80,151,147,158,...,289,341,355,319,277,268,278,236,214,39
51,2008-01-01,216,잠실(216),하차,125,521,467,"1,040","1,266","1,475",...,"2,583","2,717","2,731","2,294","1,864","1,632","1,680","1,435","1,056",201
53,2008-01-01,217,신천(217),하차,31,137,144,148,285,242,...,569,651,822,915,759,646,585,488,340,95
55,2008-01-01,218,종합운동장(218),하차,18,123,80,151,203,174,...,194,278,288,303,313,282,258,277,181,29
57,2008-01-01,219,삼성(219),하차,42,427,528,"1,002","1,374","1,588",...,"4,318","3,552","3,018","2,159","1,220",883,634,420,234,392
59,2008-01-01,220,선릉(220),하차,33,384,333,558,768,506,...,553,574,659,616,571,531,571,525,403,118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192115,2008-12-31,2740,숭실대입구,하차,25,127,191,761,786,510,...,719,789,"1,013","1,383","1,202",846,688,673,495,340
192117,2008-12-31,2741,상도,하차,36,166,288,893,703,502,...,800,840,"1,028","1,259","1,089",833,664,636,503,305
192119,2008-12-31,2742,장승배기,하차,30,145,258,748,532,416,...,763,798,854,"1,244","1,065",750,664,610,470,284
192121,2008-12-31,2743,신대방삼거리,하차,30,170,290,"1,179",686,503,...,789,917,"1,095","1,482","1,349","1,040",815,803,525,346
192123,2008-12-31,2744,보라매,하차,34,137,509,"1,353",599,335,...,518,545,631,853,688,511,429,475,304,185
192125,2008-12-31,2745,신풍,하차,41,164,270,619,557,377,...,762,855,"1,041","1,222","1,298",915,873,916,561,350
192127,2008-12-31,2746,대림(7),하차,30,98,153,654,501,395,...,502,652,749,884,748,530,485,632,345,194
192129,2008-12-31,2747,남구로,하차,61,168,605,"3,115","1,182",655,...,834,927,"1,102","1,407","1,225",916,873,"1,038",587,329
192131,2008-12-31,2748,가산디지털단지(7),하차,99,534,"1,852","10,686","4,378","1,354",...,901,949,"1,020","1,046",856,463,320,288,217,174
192133,2008-12-31,2749,철산,하차,63,354,437,"1,258",845,617,...,"1,270","1,439","1,724","2,911","2,875","1,694","1,390","1,208",958,656
192135,2008-12-31,2750,광명사거리,하차,84,272,472,965,835,633,...,"1,570","1,774","2,367","2,917","3,062","1,939","1,587","1,456","1,089",669
192137,2008-12-31,2751,천왕,하차,9,60,128,153,77,67,...,156,215,228,330,304,165,184,149,104,81
192139,2008-12-31,2752,온수(7),하차,117,114,328,362,210,142,...,341,452,545,745,809,512,438,400,311,327
192141,2008-12-31,2811,암사,하차,127,152,291,698,424,389,...,924,"1,103","1,435","1,814","1,671","1,126",948,824,678,632
192143,2008-12-31,2812,천호(8),하차,99,229,435,940,816,637,...,"1,317","1,540","1,857","2,518","2,247","1,397","1,189","1,105",794,862
192145,2008-12-31,2813,강동구청,하차,26,154,328,"1,593",591,395,...,608,722,816,"1,086","1,025",636,435,467,293,341
192147,2008-12-31,2814,몽촌토성,하차,21,113,423,"2,522","1,209",468,...,341,349,423,690,668,477,376,437,295,332
192149,2008-12-31,2815,잠실(8),하차,25,111,486,"1,934",874,500,...,564,646,687,899,735,401,351,264,167,257
192151,2008-12-31,2816,석촌,하차,44,114,314,"1,361",779,461,...,534,568,698,822,838,529,393,376,321,300
192153,2008-12-31,2817,송파,하차,55,110,231,904,432,299,...,330,405,473,565,541,327,267,267,182,208
192155,2008-12-31,2818,가락시장(8),하차,312,490,622,"2,757","1,348",617,...,589,589,675,753,552,400,354,256,180,173
192157,2008-12-31,2819,문정,하차,14,80,189,838,351,253,...,265,369,433,521,495,312,251,250,172,160
192159,2008-12-31,2820,장지,하차,23,150,254,501,241,106,...,195,284,327,446,341,251,200,199,139,213
192161,2008-12-31,2821,복정(8),하차,33,133,280,479,251,159,...,184,171,228,284,268,205,213,198,155,125
192163,2008-12-31,2822,산성,하차,12,77,131,255,136,173,...,408,538,628,780,797,556,460,511,316,313
192165,2008-12-31,2823,남한산성입구,하차,31,154,343,908,454,333,...,577,803,914,"1,265","1,265",868,714,724,508,527
192167,2008-12-31,2824,단대오거리,하차,35,133,349,886,432,316,...,645,843,"1,008","1,316","1,220",911,783,773,538,543
192169,2008-12-31,2825,신흥,하차,33,60,100,214,191,192,...,473,455,559,730,601,579,386,429,298,314
192171,2008-12-31,2826,수진,하차,54,67,97,281,196,181,...,353,399,437,500,504,376,289,325,192,162
192173,2008-12-31,2827,모란(8),하차,91,47,220,263,121,100,...,147,184,218,216,211,167,163,99,81,393

In [8]:
def trans_int(dataframe):
    col = dataframe.columns[4:]
    for day in col:
        dataframe[day] = dataframe[day].str.replace(r'\D+', '').astype(int)
    return dataframe

In [9]:
sub = trans_int(sub)

In [11]:
df = pd.DataFrame(sub.groupby([' 역명 '], as_index=False).sum())
df

,역명,역번호,05~06,06~07,07~08,08~09,09~10,10~11,11~12,12~13,...,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,24~
0,강남(222),81252,142994,1048599,2654978,5193018,3822739,1900894,1624262,1580494,...,1721990,1843789,2278364,3374513,3005656,1466438,981546,833696,561539,186890
1,강변(214),78324,54133,532267,684486,1016146,1055536,924510,937517,998308,...,1377636,1511045,1644798,2113303,1930439,1323575,1154321,1073013,659711,147496
2,건대입구(212),77592,26716,292049,435845,1024277,747097,584703,566962,685491,...,831362,979780,1235326,2002837,2099856,1324211,1081938,1028923,666905,197732
3,경복궁(317),116022,13623,151504,601773,1562404,846727,494069,417355,409089,...,349599,332089,357300,422079,335630,212619,182195,179675,125934,35966
4,고속터미널(329),120414,58123,538552,753430,1207097,1423643,1156321,1284658,1400594,...,1688272,1749865,1820638,2047772,1653446,958878,713761,539655,304685,65310
5,교대(223),81618,67424,416669,1112026,2310420,2071137,1058824,856199,803675,...,815744,786167,847246,1062425,852006,479638,401090,375252,239588,71461
6,교대(330),120780,6979,79214,337007,727998,509603,222105,159491,157924,...,158785,150506,178193,221513,170554,94961,76628,68168,48524,15802
7,구로디지털단지(232),84912,80877,302321,881561,3305002,1476661,738697,652677,663732,...,827528,908216,1097466,1766397,1765822,1152863,1120993,1355256,859340,219723
8,구의(213),77958,16794,114749,215824,699148,465101,325427,312153,337935,...,438464,485836,561713,871825,895047,636276,612208,630166,412282,127088
9,구파발(310),113460,13766,220223,196820,210529,244589,206742,144201,106328,...,95139,100236,116698,154014,172060,124934,112312,111032,96586,55728
10,금호(324),118584,9546,46919,60290,115357,105465,101228,108466,125144,...,187729,227693,265975,380296,382731,291310,290581,300374,186342,49527
11,길음(417),152622,37594,209547,279405,673768,484816,424850,394138,374866,...,422821,492809,596521,836229,918819,657379,581084,588755,431784,105170
12,낙성대(227),83082,21437,134479,286851,719121,574516,441362,328975,373363,...,454831,507490,608245,952735,1058253,788954,805160,842056,607212,192094
13,남부터미널(331),121146,13756,321622,678365,2171940,1207718,721057,647335,615938,...,718891,764677,798359,902689,765840,418240,324567,245676,145560,40361
14,남태령(434),158844,627,13198,39090,61787,19048,17051,14673,15298,...,16443,18018,21635,26806,25236,15740,15971,16312,11099,4464
15,노원(411),150426,7697,109851,232615,404092,508157,333356,328289,386348,...,507814,585319,760120,1079464,1170875,849447,728578,691563,534096,188327
16,녹번(313),114558,8348,74339,119728,268067,168782,159505,151165,169577,...,243029,293322,353756,524829,605953,444627,404025,423236,300456,81544
17,당고개(409),149694,704,86941,119509,194169,188163,195255,169552,173207,...,217071,259411,304098,399184,453323,364057,315442,321059,267962,116647
18,당산(237),86742,55264,283491,592418,1416065,666056,443866,434480,475612,...,625342,716446,868801,1221480,1303465,919874,858519,909868,627352,157449
19,대림(233),85278,43025,169175,336472,1010799,521720,411004,401610,423181,...,521820,619409,765543,1245266,1188842,797526,813516,1025612,618582,168703
20,대청(337),123342,9245,70408,153297,323465,161582,110920,109603,118805,...,167109,199051,215107,286969,318129,241824,222955,255583,190294,63930
21,대치(335),122610,4767,99594,184709,281770,262683,176713,161526,186588,...,221149,261579,301409,322107,316193,219702,177029,181888,125573,44053
22,도곡(334),122244,3150,49846,220085,321153,269826,135802,116693,127093,...,132998,143358,166311,203224,209261,144609,130731,132744,92117,54245
23,도림천(247),90402,2537,16411,25093,53293,13131,10212,9018,9682,...,11457,13693,16489,18265,16084,12076,11519,9756,7457,3683
24,독립문(316),115656,9005,69540,225443,370133,224328,166444,140308,140665,...,164564,170686,194946,250262,224389,158294,143259,143641,101342,61429
25,동대문(155),56730,32078,115456,194391,456468,445851,421781,461129,495923,...,490862,450435,431442,476053,455432,375928,307654,274880,181072,62343
26,동대문(421),154086,24287,199581,606800,1227139,1048874,791514,649031,576444,...,553396,448273,368709,345458,374918,291631,206769,128582,81883,31341
27,동대문운동장(205),75030,11597,116325,293777,763331,447198,413708,419246,439227,...,508310,464531,451937,504397,590576,435267,344485,260575,169781,59124
28,동대문운동장(422),154452,16045,154425,295122,895367,619882,486370,434819,449276,...,508588,462474,439809,491156,583641,419393,317786,226207,147097,50655
29,동대입구(322),117852,15250,93395,204788,732896,497637,385873,324462,285835,...,232228,203527,248149,300957,224816,108524,90578,85351,54731,19305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,이태원,962946,10540,65068,146808,372870,322320,210157,194927,220612,...,268275,294904,338979,408468,400202,272461,220112,202269,142180,41927
234,잠실(8),1030290,11014,61967,201755,561122,254331,154472,165860,167024,...,170119,179250,194535,243640,190767,110338,95106,81053,55500,23835
235,장승배기,1003572,11846,58574,127828,259238,195504,155319,147827,165725,...,211068,240373,271743,396866,400310,278767,254271,268895,186706,57620
236,장암,992226,644,8338,8455,14059,36664,45389,33380,18020,...,9616,8472,8323,8859,8601,5665,4293,4152,4285,2545
237,장지,1032120,15872,232957,118483,162524,79514,44142,42931,53189,...,58429,69071,81771,105473,105762,75566,68421,70390,47340,16323
238,장한평,931104,12693,111877,268145,1042206,443356,317636,285257,260374,...,290401,319342,376667,525216,541389,357632,292368,282934,195865,64018
239,종로3가(5),927810,5916,68830,186787,641697,500718,368136,343529,347354,...,298833,272274,275464,326163,249385,119061,76446,58615,39248,14856
240,중계,994056,20464,74275,196484,333066,203308,165231,170691,190212,...,234427,274469,337929,473987,564440,390675,340026,337429,256385,103009
241,중곡,997716,7981,53977,131065,239624,132932,117637,106172,117590,...,155559,181014,212317,320111,345213,245179,233833,246683,181018,61567
242,중화,995886,14030,60017,114909,305177,173030,135077,134518,152210,...,212599,261000,303278,448023,503910,357623,317347,320097,234548,80583
243,증산,958188,6165,38753,55574,134295,97464,83544,87540,101505,...,146288,183398,229859,329880,370931,278578,228879,251165,163550,72394
244,창신,965508,2658,18515,98454,69602,47563,38571,32742,36865,...,46007,57128,62660,85914,93768,69390,60044,64013,41984,12533
245,천왕,1006866,5932,30744,63584,98953,34070,31853,32383,35159,...,49066,59119,71470,104641,119220,83400,79675,75122,56408,21957
246,천호(5),932568,29855,155403,274474,512302,547782,391842,393646,442846,...,527547,553885,610918,860236,850498,508577,433805,415760,284858,101516
247,천호(8),1029192,19231,106340,164842,314026,303166,226992,232085,261275,...,358781,403257,478084,776148,777152,455808,402363,377219,248636,94256
248,철산,1006134,59458,209746,214278,412611,289686,230815,226207,262554,...,329919,389993,488125,802623,950232,634799,539935,508117,389518,119052
249,청구(5),928908,3405,20793,44871,196445,103416,57345,53266,59366,...,68924,78321,86077,116655,107782,75949,70430,73953,50076,17107
250,청구(6),964410,3590,23131,51991,259829,144751,61558,47311,54604,...,63142,70389,74129,88032,76464,56237,49235,54330,34504,12095
251,청담,999546,38529,277165,925751,2683740,1434093,551732,424227,369911,...,371318,373819,408930,494716,395592,252308,210964,184742,123740,61471
252,충정로(5),926712,4337,22484,85415,283942,157699,53901,47584,44786,...,55203,63742,75851,99964,81603,56147,56966,57634,37543,14318
253,태릉입구(6),968436,9012,34489,53378,128559,104237,78674,72049,71329,...,90677,94202,115794,154425,185310,125575,109844,111826,90400,45212
254,태릉입구(7),995154,13580,62830,111451,333918,207078,145453,128859,126673,...,123463,131498,145207,184967,188952,138027,120639,119763,90961,87926
255,하계,994422,17817,118226,269892,364767,294235,249512,263201,324717,...,376873,415217,483128,649655,739259,520949,423256,416443,311306,117134
256,학동,1000278,27292,197245,681251,2702756,1535211,553629,391917,319980,...,287320,296031,309254,324975,278771,177209,139003,107456,83227,22072
257,한강진,963312,5067,50073,119612,308309,129802,56659,48438,58276,...,47618,51197,70848,70431,59251,40089,38570,30846,25200,18372
258,합정(6),960018,7783,46756,112331,243606,136720,78584,71339,75817,...,94198,109554,129948,178693,169326,113587,95594,95955,72819,21254
259,행당,929640,8993,43626,56374,114838,93391,75156,81514,99908,...,140659,164315,192931,282246,283037,193571,180223,183348,115499,41493
260,화곡,921588,25640,135368,203624,404554,347298,272060,280535,320192,...,437959,546528,688226,1092489,1240978,875212,750840,754797,551878,178093
261,화랑대,968802,11713,44806,121535,336881,240274,154611,138728,133564,...,137461,160232,198914,293149,367917,249163,232604,244918,174193,65301
262,효창공원앞,961848,7256,57973,128035,482130,251318,142685,117046,108214,...,120431,127079,148032,187220,179966,115772,111741,108500,80640,26957

In [20]:
df['2008'] = 0

for i in range(20):
    i = i+2
    df['2008'] += df.iloc[:,i]

df.head()

,역명,역번호,05~06,06~07,07~08,08~09,09~10,10~11,11~12,12~13,...,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,24~,2008
0,강남(222),81252,142994,1048599,2654978,5193018,3822739,1900894,1624262,1580494,...,1843789,2278364,3374513,3005656,1466438,981546,833696,561539,186890,37909104
1,강변(214),78324,54133,532267,684486,1016146,1055536,924510,937517,998308,...,1511045,1644798,2113303,1930439,1323575,1154321,1073013,659711,147496,21525660
2,건대입구(212),77592,26716,292049,435845,1024277,747097,584703,566962,685491,...,979780,1235326,2002837,2099856,1324211,1081938,1028923,666905,197732,17367674
3,경복궁(317),116022,13623,151504,601773,1562404,846727,494069,417355,409089,...,332089,357300,422079,335630,212619,182195,179675,125934,35966,7844340
4,고속터미널(329),120414,58123,538552,753430,1207097,1423643,1156321,1284658,1400594,...,1749865,1820638,2047772,1653446,958878,713761,539655,304685,65310,22469933

In [25]:
df.columns

Index([' 역명 ', ' 역번호 ', ' 05~06 ', ' 06~07 ', ' 07~08 ', ' 08~09 ', ' 09~10 ',
       ' 10~11 ', ' 11~12 ', ' 12~13 ', ' 13~14 ', ' 14~15 ', ' 15~16 ',
       ' 16~17 ', ' 17~18 ', ' 18~19 ', ' 19~20 ', ' 20~21 ', ' 21~22 ',
       ' 22~23 ', ' 23~24 ', ' 24~ ', '2008'],
      dtype='object')

In [26]:
df = df[['역명', '2008']]
df.head()

            역명       2008
0      강남(222)   37909104
1      강변(214)   21525660
2    건대입구(212)   17367674
3     경복궁(317)    7844340
4   고속터미널(329)   22469933

AttributeError: 'list' object has no attribute 'str'

In [ ]:
df['역명'].str.split('(')

In [54]:
def trans_int(dataframe):
    col = dataframe.columns[4:]
    for day in col:
        dataframe[day] = dataframe[day].str.replace(r'\D+', '').astype(int)
    return dataframe

def get_year(lst):
    table = pd.DataFrame(columns = ['역명'])
    for year in lst:
        year = str(year)
        route = "data/" + year + ".csv"
        if year == '2008' :  encoding = 'utf-8'
        else: encoding = 'cp949'
        df = pd.read_csv(route, encoding=encoding)
        
        df = df.loc[df['구분'] == '하차']
        df = trans_int(df)
        df['역명'] = df['역명'].str.split("(").str[0]
        df = pd.DataFrame(df.groupby(['역명'], as_index=False).sum())
        
        df[year] = 0
        for i in range(20):
            i = i+2
            df[year] += df.iloc[:,i]
        df = df[['역명', year]]
        table = pd.merge(table, df, how = 'outer')
    return table

In [53]:
lst = [2008, 2009, 2010, 2011, 2012, 2013, 2014]

get_year(lst)

data/2008.csv
data/2009.csv
data/2010.csv
data/2011.csv
data/2012.csv
data/2013.csv
data/2014.csv

,역명,2008,2009,2010,2011,2012,2013,2014
0,가락시장,4389199.0,4384741.0,5343649.0,5579928.0,5632240.0,5700899.0,5851848.0
1,가산디지털단지,9268331.0,10074929.0,11526034.0,12774742.0,13415609.0,14750376.0,15056189.0
2,강남,37909104.0,38280796.0,38126188.0,38683924.0,38667452.0,39729332.0,39354766.0
3,강남구청,8065646.0,8282891.0,8776929.0,8886651.0,9000832.0,7086649.0,7119547.0
4,강동,5267205.0,5262852.0,5528562.0,5878152.0,6115508.0,6066634.0,6123468.0
5,강동구청,3763761.0,3698219.0,3756136.0,3880061.0,3961027.0,4009250.0,4029414.0
6,강변,21525660.0,20657387.0,20846717.0,20091773.0,19588740.0,19255297.0,19351527.0
7,개롱,2418533.0,2444066.0,2536734.0,2547981.0,2568314.0,2550691.0,2572172.0
8,개화산,1880377.0,1934525.0,1908122.0,2036623.0,2110245.0,2164815.0,2163488.0
9,거여,2178661.0,2163535.0,2446109.0,2573936.0,2587478.0,2584751.0,2635774.0
10,건대입구,21514594.0,22469471.0,23834299.0,24802889.0,24861402.0,24836072.0,25336982.0
11,경복궁,7844340.0,8213276.0,8326839.0,8488621.0,8776183.0,8961666.0,9541699.0
12,고덕,2861480.0,2930586.0,3094891.0,3190876.0,3239765.0,3197760.0,3226375.0
13,고려대,3626953.0,3652672.0,3757803.0,3745413.0,3730077.0,3727408.0,3671412.0
14,고속터미널,28221877.0,27432515.0,27752236.0,27578938.0,28289062.0,29782427.0,30110533.0
15,공덕,9304860.0,9809644.0,9964867.0,10578082.0,11313964.0,11552572.0,11675289.0
16,공릉,4849322.0,4776894.0,4885941.0,4949393.0,4905195.0,4935442.0,4895079.0
17,광나루,4713232.0,4656374.0,4852679.0,4822893.0,5009821.0,5132683.0,5190679.0
18,광명사거리,8571029.0,8852924.0,9349851.0,9765210.0,10082494.0,10174631.0,10043108.0
19,광화문,12599216.0,12557155.0,12423325.0,12759298.0,13027727.0,13116877.0,13831225.0
20,광흥창,2974583.0,3108410.0,3236326.0,3279970.0,3289066.0,3308026.0,3370529.0
21,교대,20115791.0,20160800.0,21153020.0,21251688.0,20696076.0,20270480.0,20300393.0
22,구로디지털단지,20723548.0,20995694.0,21591978.0,22332578.0,22746229.0,22906339.0,23379422.0
23,구산,1960950.0,1929809.0,2009753.0,2039722.0,2121405.0,2223840.0,2187085.0
24,구의,8927841.0,8991578.0,8900253.0,8878710.0,8760655.0,8653824.0,8644132.0
25,구파발,2668947.0,3087527.0,3472809.0,4223465.0,4543023.0,4802094.0,5114098.0
26,군자,7441065.0,7716675.0,7843307.0,8075095.0,8252290.0,8378113.0,8480105.0
27,굽은다리,2993478.0,3206322.0,3308312.0,3465347.0,3506420.0,3510720.0,3494371.0
28,금호,3518654.0,3220405.0,3233492.0,3130863.0,2883813.0,2793986.0,2740103.0
29,길동,2837008.0,2758645.0,2877396.0,3031859.0,3097115.0,3058159.0,2983080.0
...,...,...,...,...,...,...,...,...
216,충정로,5799387.0,5978371.0,6100243.0,6058409.0,6537219.0,6746749.0,6567839.0
217,태릉입구,4547401.0,4662943.0,4686637.0,4751750.0,4898945.0,5155807.0,5357606.0
218,하계,7063047.0,6986243.0,7124710.0,7321597.0,7294992.0,7419784.0,7438736.0
219,학동,9097526.0,8946122.0,9525952.0,9946039.0,9962289.0,9685047.0,9587786.0
220,학여울,1115138.0,1006774.0,1101207.0,1085740.0,1101272.0,1141868.0,1171349.0
221,한강진,1324181.0,1432288.0,1617080.0,1913337.0,2512111.0,2742162.0,2777827.0
222,한성대입구,6147870.0,6061433.0,6128983.0,6105852.0,6119170.0,6123922.0,6021278.0
223,한양대,5778379.0,5680637.0,5573402.0,5453903.0,5273533.0,5111533.0,5053128.0
224,합정,10729650.0,11310054.0,11668978.0,12241335.0,13083462.0,15348231.0,17047205.0
225,행당,2577345.0,2548479.0,2630327.0,2673162.0,2772633.0,2804142.0,2783715.0
226,혜화,16739047.0,16495592.0,16432646.0,16917893.0,16920914.0,17234763.0,17489178.0
227,홍대입구,19603424.0,20161502.0,21316456.0,22997595.0,23473479.0,25596072.0,28224419.0
228,홍제,7832430.0,7714294.0,7673768.0,7424067.0,7255032.0,7095518.0,7168775.0
229,화곡,9850040.0,9779533.0,9662568.0,9846606.0,10021044.0,9929629.0,9813129.0
230,화랑대,3565132.0,3451037.0,3464322.0,3441522.0,3535543.0,3671149.0,3746744.0
231,회현,11952869.0,11985040.0,12373584.0,12684242.0,12390508.0,12147985.0,11841125.0
232,효창공원앞,2733475.0,2778332.0,2825553.0,2909302.0,2971009.0,2939499.0,2955141.0
233,경찰병원,NaN,NaN,1719406.0,2255250.0,2418732.0,2587771.0,2621484.0
234,동대문역사문화공원,NaN,NaN,14459590.0,14482675.0,14218162.0,13729709.0,15710694.0
235,잠실나루,NaN,NaN,6664075.0,6633240.0,6511820.0,6492532.0,6605787.0
236,굴포천,NaN,NaN,NaN,NaN,347364.0,2396601.0,2899223.0
237,까치울,NaN,NaN,NaN,NaN,215987.0,1411900.0,1724528.0
238,부천시청,NaN,NaN,NaN,NaN,640216.0,3830219.0,4325693.0
239,부천종합운동장,NaN,NaN,NaN,NaN,237126.0,1588172.0,1818646.0
240,부평구청,NaN,NaN,NaN,NaN,365011.0,2539292.0,3012076.0
241,삼산체육관,NaN,NaN,NaN,NaN,282480.0,1692949.0,1899615.0
242,상동,NaN,NaN,NaN,NaN,697378.0,4343771.0,4963725.0
243,신중동,NaN,NaN,NaN,NaN,658171.0,4230047.0,4855275.0
244,춘의,NaN,NaN,NaN,NaN,335076.0,2258605.0,2527427.0
245,미아사거리,NaN,NaN,NaN,NaN,NaN,NaN,12585695.0

In [55]:
get_year(lst).to_csv('data/2008-2014.csv', index=False)