In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/total_getoff.csv')
df.head()

,역명,요일,구분,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,Friday,하차,717150.0,723021.0,887844.0,933829.0,957651.0,937623.0,960174.0,935579.0,1041381.0,1120152.0,983790.0
1,가락시장,Monday,하차,724476.0,732550.0,881828.0,885470.0,907959.0,936266.0,947154.0,920500.0,968101.0,1034857.0,1055679.0
2,가락시장,Saturday,하차,445114.0,425004.0,554888.0,607688.0,603635.0,609464.0,637277.0,610629.0,679639.0,741996.0,671172.0
3,가락시장,Sunday,하차,301328.0,294400.0,390174.0,418100.0,428507.0,422364.0,438032.0,422121.0,453598.0,519055.0,490254.0
4,가락시장,Thursday,하차,714892.0,740238.0,882762.0,904308.0,931528.0,915736.0,938114.0,942747.0,1000944.0,1090970.0,994138.5

In [3]:
dow = ['Friday', 'Saturday', 'Sunday']

weekday = df.loc[~df['요일'].isin(dow)]
weekday.head()

,역명,요일,구분,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,가락시장,Monday,하차,724476.0,732550.0,881828.0,885470.0,907959.0,936266.0,947154.0,920500.0,968101.0,1034857.0,1055679.0
4,가락시장,Thursday,하차,714892.0,740238.0,882762.0,904308.0,931528.0,915736.0,938114.0,942747.0,1000944.0,1090970.0,994138.5
5,가락시장,Tuesday,하차,752432.0,726015.0,884697.0,908044.0,905830.0,958358.0,961711.0,933810.0,995399.0,1054639.0,988707.0
6,가락시장,Wednesday,하차,733807.0,743513.0,861456.0,922489.0,897130.0,921088.0,969386.0,939244.0,993765.0,1066429.0,994963.5
8,가산디지털단지,Monday,하차,1581373.0,1732379.0,2009397.0,2185139.0,2369650.0,2647237.0,2664954.0,2613736.0,2513793.0,2423578.0,2496702.0

In [4]:
#주말을 금요일만
weekend = df.loc[df['요일']=='Friday']
#주말을 토요일만
weekend3 = df.loc[df['요일']=='Saturday']

In [5]:
weekday = pd.DataFrame(weekday.groupby(['역명'], as_index=False).mean())
weekday

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,731401.75,735579.00,877685.75,905077.75,910611.75,932862.00,954091.25,934075.25,989552.25,1061723.75,1008372.000
1,가산디지털단지,1598667.00,1750833.75,2020131.75,2234879.00,2354174.00,2602166.00,2654008.50,2642195.75,2567111.25,2482383.25,2362275.750
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1117498.50,1139075.00,1146516.75,1072832.250
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63325.75,205646.625
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169272.50,230025.50,251691.50,249759.375
5,강남,6063843.75,6157642.50,6084055.50,6083890.25,6016084.00,6232449.00,6175811.50,5922804.00,5668877.75,5725471.00,5587099.875
6,강남구청,1354306.00,1378358.00,1444625.50,1447543.00,1463661.25,1160148.25,1152048.50,1648845.00,1579792.50,1536958.50,1473272.625
7,강동,820288.50,822360.50,859111.75,908333.25,944649.50,945669.25,956602.00,936891.25,928309.25,938517.00,933027.750
8,강동구청,615816.00,608846.50,615403.00,630943.00,645191.50,660556.50,662164.50,653146.00,631075.25,642728.50,626454.000
9,강변,3038638.50,2911353.00,2904871.00,2805972.00,2715882.75,2695825.25,2688467.50,2598348.25,2496361.50,2393213.50,2192209.875
10,개롱,383212.75,390808.75,404889.75,403287.25,409566.00,410326.75,412146.50,409851.00,401734.00,395162.75,374787.000
11,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229617.50,213789.00,206153.00,174592.875
12,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,232597.25,237979.00,252114.75,256322.250
13,개화산,299084.50,313275.00,307646.25,326022.00,337070.25,349469.75,348161.00,327785.75,322401.75,318757.50,306042.000
14,거여,341364.50,343176.75,386653.25,406742.25,411872.00,415347.00,422387.25,409111.00,385124.00,373600.00,355766.250
15,건대입구,3184339.50,3330031.00,3481109.50,3579354.75,3598372.00,3622461.75,3671772.25,3635706.25,3577689.50,3500800.75,3304881.750
16,경복궁,1271586.75,1326882.50,1329359.25,1340576.50,1370911.75,1400139.75,1465178.25,1459925.75,1464221.75,1428342.75,1317669.750
17,경찰병원,NaN,NaN,291026.25,381544.25,406942.00,440262.75,442889.25,453932.00,463258.50,455944.25,439926.000
18,고덕,457234.75,474540.25,498666.00,508535.50,519523.75,518112.00,520647.25,505029.00,490362.75,546621.25,518971.875
19,고려대,582348.25,586594.75,599333.75,594609.75,591054.75,600166.25,590326.25,585200.50,572001.50,549515.75,505231.500
20,고속터미널,3780230.25,3647596.00,3646823.50,3604124.00,3669891.75,3918023.50,3943223.75,4576576.00,4653042.75,4639702.00,4439809.125
21,공덕,1578519.75,1666375.75,1693249.50,1784141.00,1902939.25,1959083.50,1975614.25,2137040.50,2088134.25,2160271.50,2121012.375
22,공릉,784937.75,776131.75,787789.25,794236.00,785854.50,792585.00,780398.25,763053.50,748453.25,737394.50,691445.250
23,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193275.25,186935.25,185943.25,173674.125
24,광나루,718657.00,719913.00,744503.00,732536.25,768787.00,794096.50,799092.50,778760.25,735364.25,724058.50,695662.875
25,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,568615.25,564062.75,551014.75,501906.375
26,광화문,2065929.00,2033732.25,2003521.75,2052467.75,2106437.25,2123654.00,2240458.00,2248332.25,2242439.00,2257121.75,2086875.750
27,광흥창,498308.50,521528.25,536030.00,541327.25,542030.75,549575.25,555776.50,548120.50,547617.00,551091.50,516509.250
28,교대,3461898.25,3469933.75,3605330.00,3579778.50,3480779.25,3445617.00,3434368.50,3281272.50,3206930.00,3120899.75,2927253.375
29,구로디지털단지,3409937.75,3466909.00,3546867.75,3634308.50,3710280.25,3766421.50,3845158.00,3851575.25,3763988.75,3697147.25,3499600.875
...,...,...,...,...,...,...,...,...,...,...,...,...
254,창신,163317.75,175863.75,173061.00,166571.25,165172.75,165066.75,167884.75,170782.00,173309.00,175625.25,169170.000
255,천왕,177432.00,176879.50,194883.00,221491.00,328025.75,355741.00,413058.50,429529.00,438655.75,454373.25,446304.375
256,천호,2339519.25,2352226.00,2432723.50,2474910.75,2515542.50,2547399.25,2543689.50,2447703.25,2365098.50,2338659.25,2238615.750
257,청구,441807.00,432051.50,439967.75,437839.75,461295.50,473467.00,466688.50,466544.50,470509.00,466109.75,442071.375
258,청담,1723963.00,1733168.75,1774796.50,1824918.25,1816398.25,1735046.50,1688555.25,1546683.50,1474216.25,1412645.25,1286349.000
259,청량리,2119600.50,2047659.50,1944428.50,1821394.00,1793601.50,1749537.75,1711303.50,2565076.50,2522667.25,2410122.75,2230295.250
260,총신대입구,1607030.25,1614003.25,1542182.50,1503795.75,1468445.75,1464457.25,1444726.50,1446826.25,1412167.75,1377546.00,1293610.125
261,충무로,2234241.75,2222499.00,2207929.50,2224494.00,2201382.50,2184318.50,2181024.25,2142538.50,2075223.50,1984912.75,1849316.250
262,충정로,974868.00,1010559.00,1026635.75,1014860.50,1097189.75,1145874.50,1113591.50,1068890.75,1063782.50,1028254.50,957005.625
263,태릉입구,732726.25,757619.00,750438.50,757509.25,780937.25,824803.75,855370.00,847518.25,849658.50,858881.25,808104.000
264,하계,1102980.25,1101841.25,1117813.25,1142076.50,1142569.50,1166957.50,1162322.50,1135420.50,1114552.25,1093022.50,1026510.000
265,학동,1586756.50,1562597.25,1621150.75,1674341.75,1666625.00,1641305.00,1619446.25,1575524.00,1470002.50,1418678.50,1332502.125
266,학여울,138471.00,132403.00,145521.00,144053.75,145146.25,144465.50,143264.50,140768.00,135442.50,129136.75,117083.625
267,한강진,219298.00,238503.50,267694.25,304072.75,380156.00,416132.50,417444.00,390424.50,408985.75,433407.25,438843.000
268,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253568.75,257388.50,253987.50,230299.125
269,한성대입구,975082.50,964628.25,959725.50,952956.00,959291.25,965603.00,944502.50,951441.75,925463.25,900496.75,846083.250
270,한양대,982251.00,977037.00,946615.00,920808.25,895975.75,879999.25,872599.25,875487.50,850913.75,819349.50,722983.125
271,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,820394.25,836604.25,840731.25,818050.875
272,합정,1714599.25,1809914.50,1836283.25,1899092.25,2005265.00,2340388.00,2554904.75,2550738.75,2531960.75,2594381.75,2510026.500
273,행당,405227.75,402226.00,414307.50,419865.50,437617.75,446980.50,444435.50,432914.50,426863.25,425383.00,413175.750
274,혜화,2380969.00,2372058.00,2341959.25,2386044.25,2407735.50,2467419.50,2478678.25,2398404.25,2357616.50,2304763.00,2119717.500
275,홍대입구,2857508.75,2928743.25,3027379.25,3201967.50,3273640.50,3561771.75,3878711.50,4358266.50,4494562.50,4604507.75,4504846.125
276,홍제,1230127.00,1217741.00,1203500.00,1156549.25,1131724.75,1115892.75,1126070.75,1118073.00,1098923.25,1082184.50,1009566.375
277,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47365.25,154718.250
278,화곡,1546627.50,1546013.50,1518935.50,1538421.25,1571618.50,1570382.25,1548133.00,1551479.50,1548300.25,1565392.50,1496613.375
279,화랑대,577783.75,563731.75,559626.00,553370.00,569152.75,596902.75,608297.25,597316.75,589468.75,587937.50,543945.375
280,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1703728.00,1672374.75,1613001.00,1496008.500
281,회현,1929241.00,1945315.00,2002763.25,2050430.75,1996278.00,1969270.75,1901797.50,1833627.00,1850398.00,1842958.75,1753227.750
282,효창공원앞,447691.50,461098.00,465597.75,475356.50,488408.75,487012.00,489001.75,472660.25,506365.00,547894.50,526929.750
283,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,675008.25,647330.25,604720.75,539793.000

In [6]:
weekend = pd.DataFrame(weekend.groupby(['역명'], as_index=False).mean())
weekend.head()

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,717150.0,723021.0,887844.0,933829.0,957651.0,937623.0,960174.0,935579.0,1041381.0,1120152.0,983790.0
1,가산디지털단지,1547224.0,1696781.0,2023905.0,2279242.0,2444934.0,2549793.0,2573655.0,2539429.0,2616873.0,2496008.0,2223256.5
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1112452.0,1175849.0,1168986.0,1020931.5
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64700.0,190626.0
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167575.0,236758.0,257718.0,235758.0

In [7]:
#주중 대비 주말 비율 구하기
weekday_values = weekday.iloc[:, 1:].values
weekend_values = weekend.iloc[:, 1:].values

weekend_ratio = np.round((weekend_values/weekday_values)*100,2)
weekend_ratio

array([[ 98.05,  98.29, 101.16, ..., 105.24, 105.5 ,  97.56],
       [ 96.78,  96.91, 100.19, ..., 101.94, 100.55,  94.12],
       [   nan,    nan,    nan, ..., 103.23, 101.96,  95.16],
       ...,
       [100.18, 100.78, 103.38, ..., 103.02, 102.35,  94.87],
       [ 96.75,  95.66,  98.41, ..., 100.19,  98.98,  92.7 ],
       [   nan,    nan,    nan, ..., 101.93, 101.02,  96.05]])

In [8]:
ratio = weekend.copy()

In [9]:
ratio.iloc[:, 1:] = weekend_ratio
ratio

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,98.05,98.29,101.16,103.18,105.17,100.51,100.64,100.16,105.24,105.50,97.56
1,가산디지털단지,96.78,96.91,100.19,101.99,103.86,97.99,96.97,96.11,101.94,100.55,94.12
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.55,103.23,101.96,95.16
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.17,92.70
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.00,102.93,102.39,94.39
5,강남,105.09,105.90,108.56,111.41,113.83,108.96,108.51,108.10,113.32,111.27,103.21
6,강남구청,98.02,98.42,102.07,103.83,107.97,102.39,102.93,100.44,105.17,104.18,97.04
7,강동,96.57,97.10,99.56,100.87,101.90,98.18,98.02,97.45,102.15,100.89,93.85
8,강동구청,97.40,97.64,99.68,101.78,103.25,98.34,98.39,97.71,103.05,101.86,94.74
9,강변,110.82,113.11,116.99,114.49,118.15,113.95,113.63,115.01,118.42,116.33,108.11
10,개롱,98.03,97.24,99.44,101.26,102.31,97.76,97.84,96.77,101.74,100.42,93.36
11,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.80,105.62,105.41,98.87
12,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,105.51,104.15,96.00
13,개화산,97.99,97.37,99.21,100.12,102.04,97.88,97.55,97.85,101.99,100.58,93.38
14,거여,98.67,98.43,101.11,101.58,102.69,98.12,98.28,97.92,102.16,101.03,94.45
15,건대입구,105.89,107.23,111.72,112.09,113.30,110.48,111.12,112.22,115.96,113.17,104.88
16,경복궁,100.33,101.01,102.92,104.51,107.13,104.71,105.25,105.59,108.45,107.37,100.22
17,경찰병원,NaN,NaN,98.70,99.37,101.18,95.84,96.23,95.08,100.10,99.45,93.65
18,고덕,98.10,98.22,99.81,102.32,102.57,97.77,98.41,98.70,103.67,101.30,94.18
19,고려대,95.54,94.75,97.11,98.70,100.90,94.66,95.12,94.31,97.83,96.83,91.25
20,고속터미널,122.90,126.25,130.23,127.67,132.63,125.93,125.26,126.20,129.53,125.64,115.58
21,공덕,98.41,99.24,100.64,103.25,105.14,99.26,99.21,98.75,104.76,104.18,97.65
22,공릉,96.69,98.26,99.77,100.53,101.80,98.53,99.02,99.06,102.20,101.81,96.15
23,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.77,103.93,102.32,93.93
24,광나루,99.40,98.97,101.48,103.01,104.90,98.88,101.61,99.90,104.24,102.81,94.50
25,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.43,97.60,98.11,90.61
26,광화문,101.31,102.51,104.68,105.25,105.65,101.83,101.60,101.06,105.97,103.63,95.18
27,광흥창,97.39,98.04,101.57,102.23,103.83,98.97,99.35,98.29,103.45,102.95,95.13
28,교대,97.39,98.15,100.47,102.85,104.90,99.41,99.79,98.40,103.97,103.16,97.60
29,구로디지털단지,97.49,98.54,101.03,102.42,103.96,99.42,99.01,98.61,103.89,102.96,96.15
...,...,...,...,...,...,...,...,...,...,...,...,...
254,창신,95.48,95.71,99.00,99.90,100.59,95.92,96.32,95.42,98.74,96.90,90.50
255,천왕,98.68,99.90,103.12,103.35,104.33,99.99,99.53,99.09,103.36,101.91,94.51
256,천호,103.74,104.69,107.95,108.55,109.62,106.29,106.85,106.61,109.96,108.02,100.08
257,청구,98.21,98.54,100.79,102.05,103.39,98.78,99.64,99.06,102.93,101.64,94.02
258,청담,98.93,99.48,102.31,104.48,106.18,101.05,100.25,98.65,104.19,102.60,96.10
259,청량리,106.66,107.19,108.87,106.10,107.19,104.14,104.50,107.18,109.02,106.85,100.74
260,총신대입구,99.90,101.17,104.38,105.57,107.44,103.27,103.80,103.04,107.62,106.34,98.79
261,충무로,98.04,98.71,101.46,102.76,104.51,99.58,99.52,98.95,104.01,102.72,96.13
262,충정로,96.31,97.09,100.08,101.38,103.37,97.33,96.96,95.52,100.97,100.39,93.48
263,태릉입구,95.86,95.67,98.62,98.24,99.45,96.87,96.77,95.66,99.04,98.81,92.94
264,하계,97.56,97.61,99.60,100.24,101.68,98.31,98.87,98.12,101.14,100.14,93.06
265,학동,96.87,96.83,100.93,102.61,105.03,99.12,98.60,97.27,103.49,102.25,96.16
266,학여울,117.18,110.26,118.33,115.27,123.27,128.57,127.42,139.13,134.43,141.07,130.30
267,한강진,98.35,99.53,103.31,108.30,110.13,108.51,110.18,108.80,115.36,114.76,107.22
268,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.51,103.43,102.06,95.44
269,한성대입구,96.95,98.74,101.80,101.87,103.12,99.88,99.78,99.53,102.65,101.72,94.44
270,한양대,94.09,92.45,94.66,98.63,99.62,93.33,93.05,91.91,93.30,93.11,89.84
271,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.15,106.93,105.29,97.38
272,합정,99.40,100.39,103.37,105.76,108.47,106.76,108.63,109.68,114.55,113.66,105.14
273,행당,98.26,98.41,100.26,100.53,101.96,97.20,97.95,97.45,102.04,100.18,93.07
274,혜화,109.95,110.39,113.17,113.98,113.74,111.14,111.45,110.86,112.34,112.02,101.10
275,홍대입구,115.52,116.89,122.95,125.10,126.22,122.77,122.80,124.33,127.17,124.58,112.95
276,홍제,97.39,98.56,100.91,101.74,102.47,99.01,99.07,98.89,102.30,101.85,93.81
277,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.07,92.33
278,화곡,97.92,98.05,100.60,101.19,102.69,99.14,99.43,99.36,103.26,101.23,93.85
279,화랑대,93.24,93.22,95.73,96.83,98.49,94.72,95.59,95.48,99.28,98.21,92.32
280,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.52,101.50,100.58,92.28
281,회현,100.18,100.78,103.38,103.18,105.18,100.90,101.26,99.71,103.02,102.35,94.87
282,효창공원앞,96.75,95.66,98.41,100.02,101.15,97.74,97.26,95.85,100.19,98.98,92.70
283,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.62,101.93,101.02,96.05

In [10]:
weekend_copy = ratio.copy()

In [11]:
weekend_copy['평균'] = '평균'
weekend_copy.head()

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,평균
0,가락시장,98.05,98.29,101.16,103.18,105.17,100.51,100.64,100.16,105.24,105.50,97.56,평균
1,가산디지털단지,96.78,96.91,100.19,101.99,103.86,97.99,96.97,96.11,101.94,100.55,94.12,평균
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.55,103.23,101.96,95.16,평균
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.17,92.70,평균
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.00,102.93,102.39,94.39,평균

In [13]:
average = pd.DataFrame(weekend_copy.groupby(['평균'], as_index=False).mean())
mean = np.round(average.iloc[:, 1:].values,2)
average.iloc[:, 1:] = mean
average = average.rename(index=str, columns={"평균": "역명"})
average

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,99.73,100.15,102.75,103.61,105.14,101.08,101.56,100.85,105.0,103.76,96.51

In [80]:
hot = ['망원', '성수', '종로3가', '경복궁', '신사', '안국', '서울대입구', '낙성대', '명동', '이태원', '홍대입구', '상도', '상계', '사당', '강남', '가좌', '뚝섬', '혜화', '신촌']

hot_place = ratio.loc[ratio['역명'].isin(hot)]
hot_place

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34
5,강남,89.89,88.86,91.21,94.87,97.00,94.68,95.18,94.28,99.82,98.02,92.26
16,경복궁,84.62,85.89,87.82,90.55,92.36,91.99,94.97,96.23,105.83,100.36,92.89
45,낙성대,87.71,86.30,88.70,90.47,89.70,87.50,87.95,86.50,90.03,88.42,83.16
85,뚝섬,87.09,85.98,87.15,87.93,87.00,82.99,82.74,80.31,83.19,81.98,76.68
95,망원,86.62,85.92,86.99,88.31,87.86,85.33,86.45,86.21,93.29,96.86,91.86
99,명동,108.43,109.30,114.89,116.70,112.46,111.26,113.08,111.62,113.08,109.23,101.58
123,사당,91.28,91.06,94.01,97.06,97.35,95.94,97.95,96.49,100.86,99.98,94.10
129,상계,89.84,89.01,91.24,92.50,90.91,88.54,88.92,87.69,91.13,89.54,83.77
130,상도,85.12,82.87,85.60,86.41,85.80,83.99,84.53,82.75,85.85,84.16,79.63
141,서울대입구,91.84,91.41,93.55,94.37,93.06,90.67,90.27,89.99,93.59,92.44,87.36
151,성수,82.27,81.40,82.27,82.27,80.59,75.49,74.77,72.73,76.50,76.99,73.28
174,신사,83.62,85.65,92.25,97.82,102.77,102.45,105.22,102.84,106.03,102.87,96.05
181,신촌,109.17,108.35,109.58,110.88,108.00,105.15,106.26,105.76,110.13,107.84,99.98
186,안국,88.36,88.78,93.50,96.45,95.61,96.19,99.41,97.07,102.34,98.61,90.75
230,이태원,115.08,118.08,125.29,134.33,135.35,141.68,154.83,160.40,167.62,172.06,159.31
243,종로3가,99.42,98.29,100.12,101.61,100.53,97.96,98.81,97.71,104.96,101.61,96.22
274,혜화,110.92,109.39,111.93,115.00,112.12,110.32,111.88,110.32,112.25,111.74,102.46
275,홍대입구,111.53,112.56,118.62,123.70,122.57,122.19,124.64,125.72,132.23,131.19,122.17

In [81]:
hot_place = pd.concat([average, hot_place])
hot_place

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91.00,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34
5,강남,89.89,88.86,91.21,94.87,97.00,94.68,95.18,94.28,99.82,98.02,92.26
16,경복궁,84.62,85.89,87.82,90.55,92.36,91.99,94.97,96.23,105.83,100.36,92.89
45,낙성대,87.71,86.30,88.70,90.47,89.70,87.50,87.95,86.50,90.03,88.42,83.16
85,뚝섬,87.09,85.98,87.15,87.93,87.00,82.99,82.74,80.31,83.19,81.98,76.68
95,망원,86.62,85.92,86.99,88.31,87.86,85.33,86.45,86.21,93.29,96.86,91.86
99,명동,108.43,109.30,114.89,116.70,112.46,111.26,113.08,111.62,113.08,109.23,101.58
123,사당,91.28,91.06,94.01,97.06,97.35,95.94,97.95,96.49,100.86,99.98,94.10
129,상계,89.84,89.01,91.24,92.50,90.91,88.54,88.92,87.69,91.13,89.54,83.77
130,상도,85.12,82.87,85.60,86.41,85.80,83.99,84.53,82.75,85.85,84.16,79.63
141,서울대입구,91.84,91.41,93.55,94.37,93.06,90.67,90.27,89.99,93.59,92.44,87.36
151,성수,82.27,81.40,82.27,82.27,80.59,75.49,74.77,72.73,76.50,76.99,73.28
174,신사,83.62,85.65,92.25,97.82,102.77,102.45,105.22,102.84,106.03,102.87,96.05
181,신촌,109.17,108.35,109.58,110.88,108.00,105.15,106.26,105.76,110.13,107.84,99.98
186,안국,88.36,88.78,93.50,96.45,95.61,96.19,99.41,97.07,102.34,98.61,90.75
230,이태원,115.08,118.08,125.29,134.33,135.35,141.68,154.83,160.40,167.62,172.06,159.31
243,종로3가,99.42,98.29,100.12,101.61,100.53,97.96,98.81,97.71,104.96,101.61,96.22
274,혜화,110.92,109.39,111.93,115.00,112.12,110.32,111.88,110.32,112.25,111.74,102.46
275,홍대입구,111.53,112.56,118.62,123.70,122.57,122.19,124.64,125.72,132.23,131.19,122.17

In [14]:
ratio = pd.concat([average, ratio])
ratio = ratio.reset_index().drop(['index'], axis=1)
ratio

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,99.73,100.15,102.75,103.61,105.14,101.08,101.56,100.85,105.00,103.76,96.51
1,가락시장,98.05,98.29,101.16,103.18,105.17,100.51,100.64,100.16,105.24,105.50,97.56
2,가산디지털단지,96.78,96.91,100.19,101.99,103.86,97.99,96.97,96.11,101.94,100.55,94.12
3,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.55,103.23,101.96,95.16
4,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.17,92.70
5,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.00,102.93,102.39,94.39
6,강남,105.09,105.90,108.56,111.41,113.83,108.96,108.51,108.10,113.32,111.27,103.21
7,강남구청,98.02,98.42,102.07,103.83,107.97,102.39,102.93,100.44,105.17,104.18,97.04
8,강동,96.57,97.10,99.56,100.87,101.90,98.18,98.02,97.45,102.15,100.89,93.85
9,강동구청,97.40,97.64,99.68,101.78,103.25,98.34,98.39,97.71,103.05,101.86,94.74
10,강변,110.82,113.11,116.99,114.49,118.15,113.95,113.63,115.01,118.42,116.33,108.11
11,개롱,98.03,97.24,99.44,101.26,102.31,97.76,97.84,96.77,101.74,100.42,93.36
12,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.80,105.62,105.41,98.87
13,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,105.51,104.15,96.00
14,개화산,97.99,97.37,99.21,100.12,102.04,97.88,97.55,97.85,101.99,100.58,93.38
15,거여,98.67,98.43,101.11,101.58,102.69,98.12,98.28,97.92,102.16,101.03,94.45
16,건대입구,105.89,107.23,111.72,112.09,113.30,110.48,111.12,112.22,115.96,113.17,104.88
17,경복궁,100.33,101.01,102.92,104.51,107.13,104.71,105.25,105.59,108.45,107.37,100.22
18,경찰병원,NaN,NaN,98.70,99.37,101.18,95.84,96.23,95.08,100.10,99.45,93.65
19,고덕,98.10,98.22,99.81,102.32,102.57,97.77,98.41,98.70,103.67,101.30,94.18
20,고려대,95.54,94.75,97.11,98.70,100.90,94.66,95.12,94.31,97.83,96.83,91.25
21,고속터미널,122.90,126.25,130.23,127.67,132.63,125.93,125.26,126.20,129.53,125.64,115.58
22,공덕,98.41,99.24,100.64,103.25,105.14,99.26,99.21,98.75,104.76,104.18,97.65
23,공릉,96.69,98.26,99.77,100.53,101.80,98.53,99.02,99.06,102.20,101.81,96.15
24,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.77,103.93,102.32,93.93
25,광나루,99.40,98.97,101.48,103.01,104.90,98.88,101.61,99.90,104.24,102.81,94.50
26,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.43,97.60,98.11,90.61
27,광화문,101.31,102.51,104.68,105.25,105.65,101.83,101.60,101.06,105.97,103.63,95.18
28,광흥창,97.39,98.04,101.57,102.23,103.83,98.97,99.35,98.29,103.45,102.95,95.13
29,교대,97.39,98.15,100.47,102.85,104.90,99.41,99.79,98.40,103.97,103.16,97.60
...,...,...,...,...,...,...,...,...,...,...,...,...
255,창신,95.48,95.71,99.00,99.90,100.59,95.92,96.32,95.42,98.74,96.90,90.50
256,천왕,98.68,99.90,103.12,103.35,104.33,99.99,99.53,99.09,103.36,101.91,94.51
257,천호,103.74,104.69,107.95,108.55,109.62,106.29,106.85,106.61,109.96,108.02,100.08
258,청구,98.21,98.54,100.79,102.05,103.39,98.78,99.64,99.06,102.93,101.64,94.02
259,청담,98.93,99.48,102.31,104.48,106.18,101.05,100.25,98.65,104.19,102.60,96.10
260,청량리,106.66,107.19,108.87,106.10,107.19,104.14,104.50,107.18,109.02,106.85,100.74
261,총신대입구,99.90,101.17,104.38,105.57,107.44,103.27,103.80,103.04,107.62,106.34,98.79
262,충무로,98.04,98.71,101.46,102.76,104.51,99.58,99.52,98.95,104.01,102.72,96.13
263,충정로,96.31,97.09,100.08,101.38,103.37,97.33,96.96,95.52,100.97,100.39,93.48
264,태릉입구,95.86,95.67,98.62,98.24,99.45,96.87,96.77,95.66,99.04,98.81,92.94
265,하계,97.56,97.61,99.60,100.24,101.68,98.31,98.87,98.12,101.14,100.14,93.06
266,학동,96.87,96.83,100.93,102.61,105.03,99.12,98.60,97.27,103.49,102.25,96.16
267,학여울,117.18,110.26,118.33,115.27,123.27,128.57,127.42,139.13,134.43,141.07,130.30
268,한강진,98.35,99.53,103.31,108.30,110.13,108.51,110.18,108.80,115.36,114.76,107.22
269,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.51,103.43,102.06,95.44
270,한성대입구,96.95,98.74,101.80,101.87,103.12,99.88,99.78,99.53,102.65,101.72,94.44
271,한양대,94.09,92.45,94.66,98.63,99.62,93.33,93.05,91.91,93.30,93.11,89.84
272,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.15,106.93,105.29,97.38
273,합정,99.40,100.39,103.37,105.76,108.47,106.76,108.63,109.68,114.55,113.66,105.14
274,행당,98.26,98.41,100.26,100.53,101.96,97.20,97.95,97.45,102.04,100.18,93.07
275,혜화,109.95,110.39,113.17,113.98,113.74,111.14,111.45,110.86,112.34,112.02,101.10
276,홍대입구,115.52,116.89,122.95,125.10,126.22,122.77,122.80,124.33,127.17,124.58,112.95
277,홍제,97.39,98.56,100.91,101.74,102.47,99.01,99.07,98.89,102.30,101.85,93.81
278,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.07,92.33
279,화곡,97.92,98.05,100.60,101.19,102.69,99.14,99.43,99.36,103.26,101.23,93.85
280,화랑대,93.24,93.22,95.73,96.83,98.49,94.72,95.59,95.48,99.28,98.21,92.32
281,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.52,101.50,100.58,92.28
282,회현,100.18,100.78,103.38,103.18,105.18,100.90,101.26,99.71,103.02,102.35,94.87
283,효창공원앞,96.75,95.66,98.41,100.02,101.15,97.74,97.26,95.85,100.19,98.98,92.70
284,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.62,101.93,101.02,96.05

In [83]:
len(ratio)

285

In [15]:
#평균이랑 차이 구하기
def df_dif(dataframe):
    for i in range(len(dataframe)):
        if i > 0:
            dif = dataframe.iloc[i, 1:].values - dataframe.iloc[0, 1:].values
            dataframe.iloc[i, 1:] = dif
    return dataframe

dif = df_dif(ratio)

In [16]:
dif

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,99.73,100.15,102.75,103.61,105.14,101.08,101.56,100.85,105.00,103.76,96.51
1,가락시장,-1.68,-1.86,-1.59,-0.43,0.03,-0.57,-0.92,-0.69,0.24,1.74,1.05
2,가산디지털단지,-2.95,-3.24,-2.56,-1.62,-1.28,-3.09,-4.59,-4.74,-3.06,-3.21,-2.39
3,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.30,-1.77,-1.80,-1.35
4,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.59,-3.81
5,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.85,-2.07,-1.37,-2.12
6,강남,5.36,5.75,5.81,7.80,8.69,7.88,6.95,7.25,8.32,7.51,6.70
7,강남구청,-1.71,-1.73,-0.68,0.22,2.83,1.31,1.37,-0.41,0.17,0.42,0.53
8,강동,-3.16,-3.05,-3.19,-2.74,-3.24,-2.90,-3.54,-3.40,-2.85,-2.87,-2.66
9,강동구청,-2.33,-2.51,-3.07,-1.83,-1.89,-2.74,-3.17,-3.14,-1.95,-1.90,-1.77
10,강변,11.09,12.96,14.24,10.88,13.01,12.87,12.07,14.16,13.42,12.57,11.60
11,개롱,-1.70,-2.91,-3.31,-2.35,-2.83,-3.32,-3.72,-4.08,-3.26,-3.34,-3.15
12,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.05,0.62,1.65,2.36
13,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.85,0.51,0.39,-0.51
14,개화산,-1.74,-2.78,-3.54,-3.49,-3.10,-3.20,-4.01,-3.00,-3.01,-3.18,-3.13
15,거여,-1.06,-1.72,-1.64,-2.03,-2.45,-2.96,-3.28,-2.93,-2.84,-2.73,-2.06
16,건대입구,6.16,7.08,8.97,8.48,8.16,9.40,9.56,11.37,10.96,9.41,8.37
17,경복궁,0.60,0.86,0.17,0.90,1.99,3.63,3.69,4.74,3.45,3.61,3.71
18,경찰병원,NaN,NaN,-4.05,-4.24,-3.96,-5.24,-5.33,-5.77,-4.90,-4.31,-2.86
19,고덕,-1.63,-1.93,-2.94,-1.29,-2.57,-3.31,-3.15,-2.15,-1.33,-2.46,-2.33
20,고려대,-4.19,-5.40,-5.64,-4.91,-4.24,-6.42,-6.44,-6.54,-7.17,-6.93,-5.26
21,고속터미널,23.17,26.10,27.48,24.06,27.49,24.85,23.70,25.35,24.53,21.88,19.07
22,공덕,-1.32,-0.91,-2.11,-0.36,0.00,-1.82,-2.35,-2.10,-0.24,0.42,1.14
23,공릉,-3.04,-1.89,-2.98,-3.08,-3.34,-2.55,-2.54,-1.79,-2.80,-1.95,-0.36
24,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.08,-1.07,-1.44,-2.58
25,광나루,-0.33,-1.18,-1.27,-0.60,-0.24,-2.20,0.05,-0.95,-0.76,-0.95,-2.01
26,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.42,-7.40,-5.65,-5.90
27,광화문,1.58,2.36,1.93,1.64,0.51,0.75,0.04,0.21,0.97,-0.13,-1.33
28,광흥창,-2.34,-2.11,-1.18,-1.38,-1.31,-2.11,-2.21,-2.56,-1.55,-0.81,-1.38
29,교대,-2.34,-2.00,-2.28,-0.76,-0.24,-1.67,-1.77,-2.45,-1.03,-0.60,1.09
...,...,...,...,...,...,...,...,...,...,...,...,...
255,창신,-4.25,-4.44,-3.75,-3.71,-4.55,-5.16,-5.24,-5.43,-6.26,-6.86,-6.01
256,천왕,-1.05,-0.25,0.37,-0.26,-0.81,-1.09,-2.03,-1.76,-1.64,-1.85,-2.00
257,천호,4.01,4.54,5.20,4.94,4.48,5.21,5.29,5.76,4.96,4.26,3.57
258,청구,-1.52,-1.61,-1.96,-1.56,-1.75,-2.30,-1.92,-1.79,-2.07,-2.12,-2.49
259,청담,-0.80,-0.67,-0.44,0.87,1.04,-0.03,-1.31,-2.20,-0.81,-1.16,-0.41
260,청량리,6.93,7.04,6.12,2.49,2.05,3.06,2.94,6.33,4.02,3.09,4.23
261,총신대입구,0.17,1.02,1.63,1.96,2.30,2.19,2.24,2.19,2.62,2.58,2.28
262,충무로,-1.69,-1.44,-1.29,-0.85,-0.63,-1.50,-2.04,-1.90,-0.99,-1.04,-0.38
263,충정로,-3.42,-3.06,-2.67,-2.23,-1.77,-3.75,-4.60,-5.33,-4.03,-3.37,-3.03
264,태릉입구,-3.87,-4.48,-4.13,-5.37,-5.69,-4.21,-4.79,-5.19,-5.96,-4.95,-3.57
265,하계,-2.17,-2.54,-3.15,-3.37,-3.46,-2.77,-2.69,-2.73,-3.86,-3.62,-3.45
266,학동,-2.86,-3.32,-1.82,-1.00,-0.11,-1.96,-2.96,-3.58,-1.51,-1.51,-0.35
267,학여울,17.45,10.11,15.58,11.66,18.13,27.49,25.86,38.28,29.43,37.31,33.79
268,한강진,-1.38,-0.62,0.56,4.69,4.99,7.43,8.62,7.95,10.36,11.00,10.71
269,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.34,-1.57,-1.70,-1.07
270,한성대입구,-2.78,-1.41,-0.95,-1.74,-2.02,-1.20,-1.78,-1.32,-2.35,-2.04,-2.07
271,한양대,-5.64,-7.70,-8.09,-4.98,-5.52,-7.75,-8.51,-8.94,-11.70,-10.65,-6.67
272,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.30,1.93,1.53,0.87
273,합정,-0.33,0.24,0.62,2.15,3.33,5.68,7.07,8.83,9.55,9.90,8.63
274,행당,-1.47,-1.74,-2.49,-3.08,-3.18,-3.88,-3.61,-3.40,-2.96,-3.58,-3.44
275,혜화,10.22,10.24,10.42,10.37,8.60,10.06,9.89,10.01,7.34,8.26,4.59
276,홍대입구,15.79,16.74,20.20,21.49,21.08,21.69,21.24,23.48,22.17,20.82,16.44
277,홍제,-2.34,-1.59,-1.84,-1.87,-2.67,-2.07,-2.49,-1.96,-2.70,-1.91,-2.70
278,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.69,-4.18
279,화곡,-1.81,-2.10,-2.15,-2.42,-2.45,-1.94,-2.13,-1.49,-1.74,-2.53,-2.66
280,화랑대,-6.49,-6.93,-7.02,-6.78,-6.65,-6.36,-5.97,-5.37,-5.72,-5.55,-4.19
281,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.33,-3.50,-3.18,-4.23
282,회현,0.45,0.63,0.63,-0.43,0.04,-0.18,-0.30,-1.14,-1.98,-1.41,-1.64
283,효창공원앞,-2.98,-4.49,-4.34,-3.59,-3.99,-3.34,-4.30,-5.00,-4.81,-4.78,-3.81
284,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.23,-3.07,-2.74,-0.46

In [17]:
#0보다 큰 값(평균보다 큰 값) 구하기
def over_average(x):
    if x is not None:
        if x > 0:
            return x
        else:
            return False
    else:
        return x

for column in dif.iloc[:,1:].columns:
    dif[column] = dif[column].apply(lambda x : over_average(x))

In [18]:
dif

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,99.73,100.15,102.75,103.61,105.14,101.08,101.56,100.85,105,103.76,96.51
1,가락시장,False,False,False,False,0.03,False,False,False,0.24,1.74,1.05
2,가산디지털단지,False,False,False,False,False,False,False,False,False,False,False
3,가양,False,False,False,False,False,False,False,False,False,False,False
4,가오리,False,False,False,False,False,False,False,False,False,False,False
5,가좌,False,False,False,False,False,False,False,False,False,False,False
6,강남,5.36,5.75,5.81,7.8,8.69,7.88,6.95,7.25,8.32,7.51,6.7
7,강남구청,False,False,False,0.22,2.83,1.31,1.37,False,0.17,0.42,0.53
8,강동,False,False,False,False,False,False,False,False,False,False,False
9,강동구청,False,False,False,False,False,False,False,False,False,False,False
10,강변,11.09,12.96,14.24,10.88,13.01,12.87,12.07,14.16,13.42,12.57,11.6
11,개롱,False,False,False,False,False,False,False,False,False,False,False
12,개포동,False,False,False,False,False,False,False,False,0.62,1.65,2.36
13,개화,False,False,False,False,False,False,False,False,0.51,0.39,False
14,개화산,False,False,False,False,False,False,False,False,False,False,False
15,거여,False,False,False,False,False,False,False,False,False,False,False
16,건대입구,6.16,7.08,8.97,8.48,8.16,9.4,9.56,11.37,10.96,9.41,8.37
17,경복궁,0.6,0.86,0.17,0.9,1.99,3.63,3.69,4.74,3.45,3.61,3.71
18,경찰병원,False,False,False,False,False,False,False,False,False,False,False
19,고덕,False,False,False,False,False,False,False,False,False,False,False
20,고려대,False,False,False,False,False,False,False,False,False,False,False
21,고속터미널,23.17,26.1,27.48,24.06,27.49,24.85,23.7,25.35,24.53,21.88,19.07
22,공덕,False,False,False,False,False,False,False,False,False,0.42,1.14
23,공릉,False,False,False,False,False,False,False,False,False,False,False
24,공항시장,False,False,False,False,False,False,False,False,False,False,False
25,광나루,False,False,False,False,False,False,0.05,False,False,False,False
26,광운대,False,False,False,False,False,False,False,False,False,False,False
27,광화문,1.58,2.36,1.93,1.64,0.51,0.75,0.04,0.21,0.97,False,False
28,광흥창,False,False,False,False,False,False,False,False,False,False,False
29,교대,False,False,False,False,False,False,False,False,False,False,1.09
...,...,...,...,...,...,...,...,...,...,...,...,...
255,창신,False,False,False,False,False,False,False,False,False,False,False
256,천왕,False,False,0.37,False,False,False,False,False,False,False,False
257,천호,4.01,4.54,5.2,4.94,4.48,5.21,5.29,5.76,4.96,4.26,3.57
258,청구,False,False,False,False,False,False,False,False,False,False,False
259,청담,False,False,False,0.87,1.04,False,False,False,False,False,False
260,청량리,6.93,7.04,6.12,2.49,2.05,3.06,2.94,6.33,4.02,3.09,4.23
261,총신대입구,0.17,1.02,1.63,1.96,2.3,2.19,2.24,2.19,2.62,2.58,2.28
262,충무로,False,False,False,False,False,False,False,False,False,False,False
263,충정로,False,False,False,False,False,False,False,False,False,False,False
264,태릉입구,False,False,False,False,False,False,False,False,False,False,False
265,하계,False,False,False,False,False,False,False,False,False,False,False
266,학동,False,False,False,False,False,False,False,False,False,False,False
267,학여울,17.45,10.11,15.58,11.66,18.13,27.49,25.86,38.28,29.43,37.31,33.79
268,한강진,False,False,0.56,4.69,4.99,7.43,8.62,7.95,10.36,11,10.71
269,한남,False,False,False,False,False,False,False,False,False,False,False
270,한성대입구,False,False,False,False,False,False,False,False,False,False,False
271,한양대,False,False,False,False,False,False,False,False,False,False,False
272,한티,False,False,False,False,False,False,False,1.3,1.93,1.53,0.87
273,합정,False,0.24,0.62,2.15,3.33,5.68,7.07,8.83,9.55,9.9,8.63
274,행당,False,False,False,False,False,False,False,False,False,False,False
275,혜화,10.22,10.24,10.42,10.37,8.6,10.06,9.89,10.01,7.34,8.26,4.59
276,홍대입구,15.79,16.74,20.2,21.49,21.08,21.69,21.24,23.48,22.17,20.82,16.44
277,홍제,False,False,False,False,False,False,False,False,False,False,False
278,화계,False,False,False,False,False,False,False,False,False,False,False
279,화곡,False,False,False,False,False,False,False,False,False,False,False
280,화랑대,False,False,False,False,False,False,False,False,False,False,False
281,회기,False,False,False,False,False,False,False,False,False,False,False
282,회현,0.45,0.63,0.63,False,0.04,False,False,False,False,False,False
283,효창공원앞,False,False,False,False,False,False,False,False,False,False,False
284,흑석,False,False,False,False,False,False,False,False,False,False,False

In [19]:
#2년 연속 평균보다 큰 역 구하기
dif2 = dif.copy()
for index, row in dif2.iterrows():
    for index_c, column in enumerate(dif2.columns):
        if (row[index_c] != False) and (isinstance(row[index_c], str) == False):
            if (index_c == 1) and (row[index_c+1] == False):
                row[index_c] = False
            elif (index_c == len(dif2.columns)-1) and (row[index_c-1] == False):
                row[index_c] = False
            elif (index_c > 1) and (index_c < len(dif2.columns)-1) and (row[index_c - 1] == False) and (row[index_c + 1] == False):
                row[index_c] = False
                
for index, row in dif2.iterrows():
    hasTrue = False
    for index_c, column in enumerate(dif2.columns):
        if (isinstance(row[index_c], str) == False) and (row[index_c] != False):
            hasTrue = True
            break
    
    if hasTrue == False:
        dif2 = dif2.drop(index)

In [20]:
dif2

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,99.73,100.15,102.75,103.61,105.14,101.08,101.56,100.85,105,103.76,96.51
1,가락시장,False,False,False,False,False,False,False,False,0.24,1.74,1.05
6,강남,5.36,5.75,5.81,7.8,8.69,7.88,6.95,7.25,8.32,7.51,6.7
7,강남구청,False,False,False,0.22,2.83,1.31,1.37,False,0.17,0.42,0.53
10,강변,11.09,12.96,14.24,10.88,13.01,12.87,12.07,14.16,13.42,12.57,11.6
12,개포동,False,False,False,False,False,False,False,False,0.62,1.65,2.36
13,개화,False,False,False,False,False,False,False,False,0.51,0.39,False
16,건대입구,6.16,7.08,8.97,8.48,8.16,9.4,9.56,11.37,10.96,9.41,8.37
17,경복궁,0.6,0.86,0.17,0.9,1.99,3.63,3.69,4.74,3.45,3.61,3.71
21,고속터미널,23.17,26.1,27.48,24.06,27.49,24.85,23.7,25.35,24.53,21.88,19.07
22,공덕,False,False,False,False,False,False,False,False,False,0.42,1.14
27,광화문,1.58,2.36,1.93,1.64,0.51,0.75,0.04,0.21,0.97,False,False
37,국회의사당,False,False,False,False,False,False,False,1.24,2.05,1.81,2.51
43,김포공항,7.26,8.55,2.74,5.8,3.85,7.65,7.47,7.49,5.9,3.54,1.57
48,남부터미널,5.78,7.6,8.36,7.45,9.07,7.68,7.18,7.03,8.22,8.74,7.87
50,남태령,False,False,False,False,False,False,False,False,False,1.21,0.11
54,노량진,False,False,False,False,False,False,False,6.08,3.33,2.6,2.02
55,노원,3.52,4.04,4.58,4.4,4.66,5.35,4.64,6.13,5.78,4.93,4.61
57,녹사평,5.39,3.22,2.76,5.05,5.26,9.61,20.01,25.7,23.91,23.57,18.77
59,논현,False,False,0.25,1.42,2.2,0.94,0.42,0.08,1.83,2.01,2.19
62,당산,0.09,1.1,1.45,1.28,1.15,False,False,False,False,0.34,1.09
66,대치,False,1.11,0.72,1.1,0.83,False,False,False,1.22,1.45,0.95
68,도곡,False,False,0.18,0.21,0.37,False,False,False,False,False,False
72,독립문,False,False,False,False,False,0.81,1.37,1.15,False,False,False
75,동대문,4.27,3.45,3.61,2.47,1.59,3.66,4.23,4.22,2.29,1.04,0.18
76,동대문역사문화공원,False,False,8.94,7.21,6.02,7.02,8.19,8.29,7.7,5.83,4.98
78,동대문운동장,10.22,9.16,False,False,False,False,False,False,False,False,False
79,동대입구,False,1.19,0.36,False,False,False,False,False,False,False,False
81,동묘앞,2.38,1.94,3.22,1.57,0.54,2.44,2.15,2.92,0.07,0.3,0.51
82,동작,17.18,4.15,4.69,1.08,2.35,0.68,16.81,6.31,2.64,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
213,왕십리,1.84,3.76,4.72,4.28,4.22,4.76,5.46,6.59,6.56,5.72,4.58
216,용두,0.51,0.13,0.61,False,False,False,False,False,False,False,False
221,월드컵경기장,13.73,20.54,6.5,17.34,2.32,10.77,19.01,19.55,6.66,2.27,7.24
222,을지로3가,False,False,False,0.7,0.67,False,False,False,False,False,False
224,을지로입구,4.06,4.53,6.11,4.48,3.47,3.6,3.02,2.97,3.16,2.39,2.14
227,의정부,False,False,False,False,False,False,False,11.75,9.6,8.23,6.92
228,이대,2.48,2.91,3.02,1.16,False,0.31,0.06,0.54,0.17,False,False
229,이수,False,False,0.72,0.99,1.32,1.68,1.32,1.64,2.48,1.74,2.11
230,이촌,10.07,6.15,4.78,5.36,5.9,6.95,8.06,6.01,4.48,2.62,0.31
231,이태원,14.46,16.73,21.24,23.62,24.92,33.09,43.32,45.43,47.81,51.06,45.35
234,잠실,3.87,3.66,5.27,3.84,2.71,4.27,4.45,5.92,6.34,4.71,3.4
236,잠실새내,False,False,False,False,False,False,False,False,6.6,7.73,6.78
239,장지,False,False,1.67,2.82,2.14,1.28,0.39,0.17,0.38,1.3,False
240,장한평,False,False,False,False,False,False,False,0.56,1.12,0.67,0.57
243,종각,4.58,5.22,7.12,6.16,6.09,5.75,4.16,4.46,4.66,3.41,2.65
244,종로3가,3.05,4.5,4.38,3.52,2.8,4.14,4.25,5.45,5.05,4.04,3.1
245,종로5가,False,False,0.25,0.77,0.57,0.63,1.17,1.16,0.83,0.08,False
246,종합운동장,16.34,9.78,14.05,9.76,13.33,15.14,17.71,9.52,7.52,19.26,22.52
254,창동,1.31,1.66,2.02,1.83,1.84,1.75,1.73,1.29,1.19,1,1.05
257,천호,4.01,4.54,5.2,4.94,4.48,5.21,5.29,5.76,4.96,4.26,3.57
259,청담,False,False,False,0.87,1.04,False,False,False,False,False,False
260,청량리,6.93,7.04,6.12,2.49,2.05,3.06,2.94,6.33,4.02,3.09,4.23
261,총신대입구,0.17,1.02,1.63,1.96,2.3,2.19,2.24,2.19,2.62,2.58,2.28
267,학여울,17.45,10.11,15.58,11.66,18.13,27.49,25.86,38.28,29.43,37.31,33.79
268,한강진,False,False,0.56,4.69,4.99,7.43,8.62,7.95,10.36,11,10.71
272,한티,False,False,False,False,False,False,False,1.3,1.93,1.53,0.87
273,합정,False,0.24,0.62,2.15,3.33,5.68,7.07,8.83,9.55,9.9,8.63
275,혜화,10.22,10.24,10.42,10.37,8.6,10.06,9.89,10.01,7.34,8.26,4.59
276,홍대입구,15.79,16.74,20.2,21.49,21.08,21.69,21.24,23.48,22.17,20.82,16.44
282,회현,0.45,0.63,0.63,False,False,False,False,False,False,False,False

In [21]:
test = ['망원', '성수', '종로3가', '경복궁', '신사', '안국', '서울대입구', '낙성대', '명동', '이태원', '홍대입구', '상도', '상계', '사당', '강남', '가좌', '뚝섬', '혜화', '신촌']

dif2.loc[dif2['역명'].isin(test)]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
6,강남,5.36,5.75,5.81,7.8,8.69,7.88,6.95,7.25,8.32,7.51,6.7
17,경복궁,0.6,0.86,0.17,0.9,1.99,3.63,3.69,4.74,3.45,3.61,3.71
96,망원,False,False,False,False,False,False,False,False,False,1.48,0.98
100,명동,7.53,8.98,10.18,6.94,4.07,7.66,8.13,10.8,7.08,5.02,3.12
124,사당,2.45,2.15,2.6,3.2,3.18,3.46,3.92,4.03,4.78,5.31,4.6
175,신사,1.23,2.75,4.84,7.82,10.37,9.88,10.45,10.01,10.42,9.69,8.77
182,신촌,9.28,10.03,9.92,9.22,7.69,7.59,7.7,9.7,8.6,7.96,6.15
187,안국,False,0.24,0.87,0.18,0.41,3.12,3.74,4,2.51,2.88,1.02
231,이태원,14.46,16.73,21.24,23.62,24.92,33.09,43.32,45.43,47.81,51.06,45.35
244,종로3가,3.05,4.5,4.38,3.52,2.8,4.14,4.25,5.45,5.05,4.04,3.1
275,혜화,10.22,10.24,10.42,10.37,8.6,10.06,9.89,10.01,7.34,8.26,4.59
276,홍대입구,15.79,16.74,20.2,21.49,21.08,21.69,21.24,23.48,22.17,20.82,16.44