In [21]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/total_getoff.csv')
df.head()

,역명,요일,구분,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,Friday,승차,661504.0,660001.0,865189.0,915944.0,945293.0,926408.0,944054.0,909651.0,996546.0,1052211.0,934932.0
1,가락시장,Friday,하차,717150.0,723021.0,887844.0,933829.0,957651.0,937623.0,960174.0,935579.0,1041381.0,1120152.0,983790.0
2,가락시장,Monday,승차,668113.0,666447.0,850399.0,867283.0,894556.0,925457.0,930298.0,893244.0,923066.0,975340.0,1004461.5
3,가락시장,Monday,하차,724476.0,732550.0,881828.0,885470.0,907959.0,936266.0,947154.0,920500.0,968101.0,1034857.0,1055679.0
4,가락시장,Saturday,승차,444874.0,417456.0,574125.0,635574.0,640854.0,648734.0,676844.0,645399.0,700815.0,746265.0,681147.0

In [8]:
dow = ['Friday', 'Saturday', 'Sunday']

weekday = df.loc[~df['요일'].isin(dow)]
weekday.head()

,역명,요일,구분,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,가락시장,Monday,하차,724476.0,732550.0,881828.0,885470.0,907959.0,936266.0,947154.0,920500.0,968101.0,1034857.0,1055679.0
9,가락시장,Thursday,하차,714892.0,740238.0,882762.0,904308.0,931528.0,915736.0,938114.0,942747.0,1000944.0,1090970.0,994138.5
11,가락시장,Tuesday,하차,752432.0,726015.0,884697.0,908044.0,905830.0,958358.0,961711.0,933810.0,995399.0,1054639.0,988707.0
13,가락시장,Wednesday,하차,733807.0,743513.0,861456.0,922489.0,897130.0,921088.0,969386.0,939244.0,993765.0,1066429.0,994963.5
17,가산디지털단지,Monday,하차,1581373.0,1732379.0,2009397.0,2185139.0,2369650.0,2647237.0,2664954.0,2613736.0,2513793.0,2423578.0,2496702.0

In [9]:
#주말을 금요일, 토요일로 보기
weekend = df.loc[(df['요일']=='Saturday')|(df['요일']=='Friday')]
#주말을 금요일만
weekend2 = df.loc[df['요일']=='Friday']
#주말을 토요일만
weekend3 = df.loc[df['요일']=='Saturday']

,역명,요일,구분,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,가락시장,Friday,하차,717150.0,723021.0,887844.0,933829.0,957651.0,937623.0,960174.0,935579.0,1041381.0,1120152.0,983790.0
5,가락시장,Saturday,하차,445114.0,425004.0,554888.0,607688.0,603635.0,609464.0,637277.0,610629.0,679639.0,741996.0,671172.0
15,가산디지털단지,Friday,하차,1547224.0,1696781.0,2023905.0,2279242.0,2444934.0,2549793.0,2573655.0,2539429.0,2616873.0,2496008.0,2223256.5
19,가산디지털단지,Saturday,하차,823368.0,845921.0,881504.0,965292.0,939466.0,1064485.0,1092919.0,1041952.0,1025710.0,929053.0,834207.0
29,강남,Friday,하차,6372749.0,6520980.0,6604881.0,6777899.0,6848093.0,6790572.0,6701271.0,6402744.0,6424044.0,6370882.0,5766693.0

In [10]:
weekday = pd.DataFrame(weekday.groupby(['역명'], as_index=False).mean())
weekday

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,731401.75,735579.00,877685.75,905077.75,910611.75,932862.00,954091.25,934075.25,989552.25,1061723.75,1008372.000
1,가산디지털단지,1598667.00,1750833.75,2020131.75,2234879.00,2354174.00,2602166.00,2654008.50,2642195.75,2567111.25,2482383.25,2362275.750
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1117498.50,1139075.00,1146516.75,1072832.250
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63325.75,205646.625
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169272.50,230025.50,251691.50,249759.375
5,강남,6063843.75,6157642.50,6084055.50,6083890.25,6016084.00,6232449.00,6175811.50,5922804.00,5668877.75,5725471.00,5587099.875
6,강남구청,1354306.00,1378358.00,1444625.50,1447543.00,1463661.25,1160148.25,1152048.50,1648845.00,1579792.50,1536958.50,1473272.625
7,강동,820288.50,822360.50,859111.75,908333.25,944649.50,945669.25,956602.00,936891.25,928309.25,938517.00,933027.750
8,강동구청,615816.00,608846.50,615403.00,630943.00,645191.50,660556.50,662164.50,653146.00,631075.25,642728.50,626454.000
9,강변,3038638.50,2911353.00,2904871.00,2805972.00,2715882.75,2695825.25,2688467.50,2598348.25,2496361.50,2393213.50,2192209.875
10,개롱,383212.75,390808.75,404889.75,403287.25,409566.00,410326.75,412146.50,409851.00,401734.00,395162.75,374787.000
11,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229617.50,213789.00,206153.00,174592.875
12,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,232597.25,237979.00,252114.75,256322.250
13,개화산,299084.50,313275.00,307646.25,326022.00,337070.25,349469.75,348161.00,327785.75,322401.75,318757.50,306042.000
14,거여,341364.50,343176.75,386653.25,406742.25,411872.00,415347.00,422387.25,409111.00,385124.00,373600.00,355766.250
15,건대입구,3184339.50,3330031.00,3481109.50,3579354.75,3598372.00,3622461.75,3671772.25,3635706.25,3577689.50,3500800.75,3304881.750
16,경복궁,1271586.75,1326882.50,1329359.25,1340576.50,1370911.75,1400139.75,1465178.25,1459925.75,1464221.75,1428342.75,1317669.750
17,경찰병원,NaN,NaN,291026.25,381544.25,406942.00,440262.75,442889.25,453932.00,463258.50,455944.25,439926.000
18,고덕,457234.75,474540.25,498666.00,508535.50,519523.75,518112.00,520647.25,505029.00,490362.75,546621.25,518971.875
19,고려대,582348.25,586594.75,599333.75,594609.75,591054.75,600166.25,590326.25,585200.50,572001.50,549515.75,505231.500
20,고속터미널,3780230.25,3647596.00,3646823.50,3604124.00,3669891.75,3918023.50,3943223.75,4576576.00,4653042.75,4639702.00,4439809.125
21,공덕,1578519.75,1666375.75,1693249.50,1784141.00,1902939.25,1959083.50,1975614.25,2137040.50,2088134.25,2160271.50,2121012.375
22,공릉,784937.75,776131.75,787789.25,794236.00,785854.50,792585.00,780398.25,763053.50,748453.25,737394.50,691445.250
23,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193275.25,186935.25,185943.25,173674.125
24,광나루,718657.00,719913.00,744503.00,732536.25,768787.00,794096.50,799092.50,778760.25,735364.25,724058.50,695662.875
25,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,568615.25,564062.75,551014.75,501906.375
26,광화문,2065929.00,2033732.25,2003521.75,2052467.75,2106437.25,2123654.00,2240458.00,2248332.25,2242439.00,2257121.75,2086875.750
27,광흥창,498308.50,521528.25,536030.00,541327.25,542030.75,549575.25,555776.50,548120.50,547617.00,551091.50,516509.250
28,교대,3461898.25,3469933.75,3605330.00,3579778.50,3480779.25,3445617.00,3434368.50,3281272.50,3206930.00,3120899.75,2927253.375
29,구로디지털단지,3409937.75,3466909.00,3546867.75,3634308.50,3710280.25,3766421.50,3845158.00,3851575.25,3763988.75,3697147.25,3499600.875
...,...,...,...,...,...,...,...,...,...,...,...,...
254,창신,163317.75,175863.75,173061.00,166571.25,165172.75,165066.75,167884.75,170782.00,173309.00,175625.25,169170.000
255,천왕,177432.00,176879.50,194883.00,221491.00,328025.75,355741.00,413058.50,429529.00,438655.75,454373.25,446304.375
256,천호,2339519.25,2352226.00,2432723.50,2474910.75,2515542.50,2547399.25,2543689.50,2447703.25,2365098.50,2338659.25,2238615.750
257,청구,441807.00,432051.50,439967.75,437839.75,461295.50,473467.00,466688.50,466544.50,470509.00,466109.75,442071.375
258,청담,1723963.00,1733168.75,1774796.50,1824918.25,1816398.25,1735046.50,1688555.25,1546683.50,1474216.25,1412645.25,1286349.000
259,청량리,2119600.50,2047659.50,1944428.50,1821394.00,1793601.50,1749537.75,1711303.50,2565076.50,2522667.25,2410122.75,2230295.250
260,총신대입구,1607030.25,1614003.25,1542182.50,1503795.75,1468445.75,1464457.25,1444726.50,1446826.25,1412167.75,1377546.00,1293610.125
261,충무로,2234241.75,2222499.00,2207929.50,2224494.00,2201382.50,2184318.50,2181024.25,2142538.50,2075223.50,1984912.75,1849316.250
262,충정로,974868.00,1010559.00,1026635.75,1014860.50,1097189.75,1145874.50,1113591.50,1068890.75,1063782.50,1028254.50,957005.625
263,태릉입구,732726.25,757619.00,750438.50,757509.25,780937.25,824803.75,855370.00,847518.25,849658.50,858881.25,808104.000
264,하계,1102980.25,1101841.25,1117813.25,1142076.50,1142569.50,1166957.50,1162322.50,1135420.50,1114552.25,1093022.50,1026510.000
265,학동,1586756.50,1562597.25,1621150.75,1674341.75,1666625.00,1641305.00,1619446.25,1575524.00,1470002.50,1418678.50,1332502.125
266,학여울,138471.00,132403.00,145521.00,144053.75,145146.25,144465.50,143264.50,140768.00,135442.50,129136.75,117083.625
267,한강진,219298.00,238503.50,267694.25,304072.75,380156.00,416132.50,417444.00,390424.50,408985.75,433407.25,438843.000
268,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253568.75,257388.50,253987.50,230299.125
269,한성대입구,975082.50,964628.25,959725.50,952956.00,959291.25,965603.00,944502.50,951441.75,925463.25,900496.75,846083.250
270,한양대,982251.00,977037.00,946615.00,920808.25,895975.75,879999.25,872599.25,875487.50,850913.75,819349.50,722983.125
271,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,820394.25,836604.25,840731.25,818050.875
272,합정,1714599.25,1809914.50,1836283.25,1899092.25,2005265.00,2340388.00,2554904.75,2550738.75,2531960.75,2594381.75,2510026.500
273,행당,405227.75,402226.00,414307.50,419865.50,437617.75,446980.50,444435.50,432914.50,426863.25,425383.00,413175.750
274,혜화,2380969.00,2372058.00,2341959.25,2386044.25,2407735.50,2467419.50,2478678.25,2398404.25,2357616.50,2304763.00,2119717.500
275,홍대입구,2857508.75,2928743.25,3027379.25,3201967.50,3273640.50,3561771.75,3878711.50,4358266.50,4494562.50,4604507.75,4504846.125
276,홍제,1230127.00,1217741.00,1203500.00,1156549.25,1131724.75,1115892.75,1126070.75,1118073.00,1098923.25,1082184.50,1009566.375
277,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47365.25,154718.250
278,화곡,1546627.50,1546013.50,1518935.50,1538421.25,1571618.50,1570382.25,1548133.00,1551479.50,1548300.25,1565392.50,1496613.375
279,화랑대,577783.75,563731.75,559626.00,553370.00,569152.75,596902.75,608297.25,597316.75,589468.75,587937.50,543945.375
280,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1703728.00,1672374.75,1613001.00,1496008.500
281,회현,1929241.00,1945315.00,2002763.25,2050430.75,1996278.00,1969270.75,1901797.50,1833627.00,1850398.00,1842958.75,1753227.750
282,효창공원앞,447691.50,461098.00,465597.75,475356.50,488408.75,487012.00,489001.75,472660.25,506365.00,547894.50,526929.750
283,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,675008.25,647330.25,604720.75,539793.000

In [11]:
weekend = pd.DataFrame(weekend.groupby(['역명'], as_index=False).mean())
weekend.head()

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,581132.0,574012.5,721366.0,770758.5,780643.0,773543.5,798725.5,773104.0,860510.0,931074.0,827481.00
1,가산디지털단지,1185296.0,1271351.0,1452704.5,1622267.0,1692200.0,1807139.0,1833287.0,1790690.5,1821291.5,1712530.5,1528731.75
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,968780.0,1025924.5,1014142.0,888978.75
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58848.5,167465.25
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156569.0,216846.0,234136.5,215637.75

In [22]:
#주중 대비 주말 비율 구하기
weekday_values = weekday.iloc[:, 1:].values
weekend_values = weekend1.iloc[:, 1:].values

weekend_ratio = np.round((weekend_values/weekday_values)*100,2)
weekend_ratio

array([[79.45, 78.04, 82.19, ..., 86.96, 87.69, 82.06],
       [74.14, 72.61, 71.91, ..., 70.95, 68.99, 64.71],
       [  nan,   nan,   nan, ..., 90.07, 88.45, 82.86],
       ...,
       [91.71, 90.86, 91.75, ..., 95.33, 95.41, 89.35],
       [82.1 , 79.86, 81.79, ..., 83.52, 82.22, 77.81],
       [  nan,   nan,   nan, ..., 87.31, 87.06, 82.22]])

In [75]:
ratio = weekend.copy()

In [76]:
ratio.iloc[:, 1:] = weekend_ratio
ratio

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,가락시장,79.45,78.04,82.19,85.16,85.73,82.92,83.72,82.77,86.96,87.69,82.06
1,가산디지털단지,74.14,72.61,71.91,72.59,71.88,69.45,69.08,67.77,70.95,68.99,64.71
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.69,90.07,88.45,82.86
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.93,81.43
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34
5,강남,89.89,88.86,91.21,94.87,97.00,94.68,95.18,94.28,99.82,98.02,92.26
6,강남구청,80.70,81.54,84.09,86.94,87.57,84.95,87.39,84.57,87.34,86.43,80.11
7,강동,90.78,90.54,92.01,93.73,93.36,91.21,90.72,89.52,93.34,91.40,83.95
8,강동구청,82.55,81.67,82.94,85.04,84.45,81.20,81.53,79.95,83.62,82.19,76.25
9,강변,109.95,110.92,114.26,113.76,115.34,112.37,113.71,113.95,117.95,116.06,109.45
10,개롱,87.71,85.79,86.78,89.22,87.16,84.31,85.01,83.35,88.01,85.85,80.63
11,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.37,88.73,88.61,83.48
12,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.69,90.57,88.63,81.07
13,개화산,86.93,83.22,84.45,86.15,85.96,83.18,83.68,84.17,87.94,86.62,80.71
14,거여,90.29,88.15,89.43,89.81,87.43,84.38,84.96,83.78,87.20,85.84,81.06
15,건대입구,103.33,103.05,106.83,109.66,108.52,106.57,107.84,108.67,112.43,110.18,104.58
16,경복궁,84.62,85.89,87.82,90.55,92.36,91.99,94.97,96.23,105.83,100.36,92.89
17,경찰병원,NaN,NaN,76.46,77.13,77.71,74.78,75.96,74.31,77.56,76.97,72.62
18,고덕,85.89,84.29,85.39,88.35,86.74,84.08,85.44,84.81,88.56,85.28,79.41
19,고려대,85.22,85.53,87.24,88.31,88.49,84.43,84.38,83.96,86.15,84.65,79.94
20,고속터미널,125.25,127.21,130.74,132.36,134.33,129.61,130.08,129.68,134.69,130.50,121.52
21,공덕,76.73,76.46,77.18,79.30,79.73,77.39,77.60,77.96,83.68,82.62,77.26
22,공릉,82.94,82.55,84.43,85.75,85.26,84.15,85.32,84.83,87.40,87.24,83.63
23,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.27,92.02,90.02,83.98
24,광나루,94.78,92.68,94.75,97.51,94.15,91.17,92.88,91.49,95.63,94.15,86.94
25,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.26,84.71,84.09,78.47
26,광화문,83.42,85.01,85.98,87.19,85.77,84.21,84.15,81.68,97.37,87.00,76.16
27,광흥창,78.24,77.73,80.46,81.26,81.03,78.81,80.24,79.23,83.64,82.43,76.06
28,교대,76.11,76.10,78.14,80.93,81.21,78.16,78.83,77.46,80.68,79.75,75.64
29,구로디지털단지,81.74,81.02,82.35,84.31,83.49,81.17,80.97,80.05,84.47,83.40,78.56
...,...,...,...,...,...,...,...,...,...,...,...,...
254,창신,84.82,82.41,84.81,84.74,81.48,78.83,79.22,77.63,81.14,79.65,75.07
255,천왕,90.14,89.60,91.70,93.07,89.53,86.61,87.41,85.95,89.53,87.27,80.92
256,천호,98.31,98.51,101.53,103.65,102.23,100.11,100.66,99.36,102.03,99.09,92.76
257,청구,87.62,86.25,87.43,88.92,87.24,83.88,84.67,83.45,86.09,84.86,78.28
258,청담,81.70,80.85,82.36,84.92,84.12,80.48,79.74,78.99,82.85,81.87,76.72
259,청량리,107.16,105.53,105.84,103.89,103.23,101.45,101.66,105.05,108.31,106.06,102.23
260,총신대입구,90.92,90.27,92.99,96.15,96.06,93.50,93.89,92.40,96.24,94.64,88.59
261,충무로,80.10,79.00,80.51,81.45,80.73,78.46,79.75,78.34,83.56,82.61,77.53
262,충정로,78.45,77.33,78.50,79.91,79.56,76.38,76.48,74.89,79.17,78.62,72.98
263,태릉입구,83.52,82.04,85.10,86.46,85.97,84.67,84.91,83.91,86.95,86.55,83.04
264,하계,90.77,88.99,90.22,91.75,90.33,88.67,89.73,88.78,90.64,88.86,82.62
265,학동,74.11,73.61,79.35,81.93,83.25,79.74,80.23,78.87,82.33,80.80,73.59
266,학여울,139.06,122.44,125.95,128.34,131.32,143.86,147.84,161.71,167.30,161.51,143.67
267,한강진,80.19,79.61,81.85,91.29,98.60,99.48,101.91,101.24,112.18,115.11,110.27
268,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.78,90.15,88.50,84.40
269,한성대입구,87.85,87.62,91.03,91.73,90.40,88.25,89.04,88.27,91.95,91.68,85.40
270,한양대,75.53,73.22,76.94,79.01,77.72,74.32,73.45,72.04,73.49,74.44,69.69
271,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.92,95.86,94.32,88.40
272,합정,87.53,87.08,90.45,93.95,95.90,96.80,100.77,101.93,107.18,106.21,100.00
273,행당,88.38,87.52,88.23,89.09,88.07,85.23,85.42,83.84,88.21,86.10,80.36
274,혜화,110.92,109.39,111.93,115.00,112.12,110.32,111.88,110.32,112.25,111.74,102.46
275,홍대입구,111.53,112.56,118.62,123.70,122.57,122.19,124.64,125.72,132.23,131.19,122.17
276,홍제,89.76,88.90,90.51,92.47,91.30,89.16,89.35,88.20,92.83,91.76,84.31
277,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.99,82.34
278,화곡,89.97,88.52,90.09,91.66,90.42,88.16,88.68,87.55,91.28,88.78,82.76
279,화랑대,82.59,80.91,83.30,84.98,84.05,81.64,82.39,81.76,85.18,83.81,79.17
280,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.30,93.61,93.26,86.61
281,회현,91.71,90.86,91.75,92.29,93.24,91.28,93.35,90.79,95.33,95.41,89.35
282,효창공원앞,82.10,79.86,81.79,84.15,82.04,79.73,79.70,78.30,83.52,82.22,77.81
283,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.96,87.31,87.06,82.22

In [77]:
weekend_copy = ratio.copy()

In [78]:
weekend_copy['평균'] = '평균'
weekend_copy.head()

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,평균
0,가락시장,79.45,78.04,82.19,85.16,85.73,82.92,83.72,82.77,86.96,87.69,82.06,평균
1,가산디지털단지,74.14,72.61,71.91,72.59,71.88,69.45,69.08,67.77,70.95,68.99,64.71,평균
2,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.69,90.07,88.45,82.86,평균
3,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.93,81.43,평균
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34,평균

In [79]:
average = pd.DataFrame(weekend_copy.groupby(['평균'], as_index=False).mean())
mean = np.round(average.iloc[:, 1:].values,2)
average.iloc[:, 1:] = mean
average = average.rename(index=str, columns={"평균": "역명"})
average

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91.0,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41

In [80]:
hot = ['망원', '성수', '종로3가', '경복궁', '신사', '안국', '서울대입구', '낙성대', '명동', '이태원', '홍대입구', '상도', '상계', '사당', '강남', '가좌', '뚝섬', '혜화', '신촌']

hot_place = ratio.loc[ratio['역명'].isin(hot)]
hot_place

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34
5,강남,89.89,88.86,91.21,94.87,97.00,94.68,95.18,94.28,99.82,98.02,92.26
16,경복궁,84.62,85.89,87.82,90.55,92.36,91.99,94.97,96.23,105.83,100.36,92.89
45,낙성대,87.71,86.30,88.70,90.47,89.70,87.50,87.95,86.50,90.03,88.42,83.16
85,뚝섬,87.09,85.98,87.15,87.93,87.00,82.99,82.74,80.31,83.19,81.98,76.68
95,망원,86.62,85.92,86.99,88.31,87.86,85.33,86.45,86.21,93.29,96.86,91.86
99,명동,108.43,109.30,114.89,116.70,112.46,111.26,113.08,111.62,113.08,109.23,101.58
123,사당,91.28,91.06,94.01,97.06,97.35,95.94,97.95,96.49,100.86,99.98,94.10
129,상계,89.84,89.01,91.24,92.50,90.91,88.54,88.92,87.69,91.13,89.54,83.77
130,상도,85.12,82.87,85.60,86.41,85.80,83.99,84.53,82.75,85.85,84.16,79.63
141,서울대입구,91.84,91.41,93.55,94.37,93.06,90.67,90.27,89.99,93.59,92.44,87.36
151,성수,82.27,81.40,82.27,82.27,80.59,75.49,74.77,72.73,76.50,76.99,73.28
174,신사,83.62,85.65,92.25,97.82,102.77,102.45,105.22,102.84,106.03,102.87,96.05
181,신촌,109.17,108.35,109.58,110.88,108.00,105.15,106.26,105.76,110.13,107.84,99.98
186,안국,88.36,88.78,93.50,96.45,95.61,96.19,99.41,97.07,102.34,98.61,90.75
230,이태원,115.08,118.08,125.29,134.33,135.35,141.68,154.83,160.40,167.62,172.06,159.31
243,종로3가,99.42,98.29,100.12,101.61,100.53,97.96,98.81,97.71,104.96,101.61,96.22
274,혜화,110.92,109.39,111.93,115.00,112.12,110.32,111.88,110.32,112.25,111.74,102.46
275,홍대입구,111.53,112.56,118.62,123.70,122.57,122.19,124.64,125.72,132.23,131.19,122.17

In [81]:
hot_place = pd.concat([average, hot_place])
hot_place

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91.00,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
4,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34
5,강남,89.89,88.86,91.21,94.87,97.00,94.68,95.18,94.28,99.82,98.02,92.26
16,경복궁,84.62,85.89,87.82,90.55,92.36,91.99,94.97,96.23,105.83,100.36,92.89
45,낙성대,87.71,86.30,88.70,90.47,89.70,87.50,87.95,86.50,90.03,88.42,83.16
85,뚝섬,87.09,85.98,87.15,87.93,87.00,82.99,82.74,80.31,83.19,81.98,76.68
95,망원,86.62,85.92,86.99,88.31,87.86,85.33,86.45,86.21,93.29,96.86,91.86
99,명동,108.43,109.30,114.89,116.70,112.46,111.26,113.08,111.62,113.08,109.23,101.58
123,사당,91.28,91.06,94.01,97.06,97.35,95.94,97.95,96.49,100.86,99.98,94.10
129,상계,89.84,89.01,91.24,92.50,90.91,88.54,88.92,87.69,91.13,89.54,83.77
130,상도,85.12,82.87,85.60,86.41,85.80,83.99,84.53,82.75,85.85,84.16,79.63
141,서울대입구,91.84,91.41,93.55,94.37,93.06,90.67,90.27,89.99,93.59,92.44,87.36
151,성수,82.27,81.40,82.27,82.27,80.59,75.49,74.77,72.73,76.50,76.99,73.28
174,신사,83.62,85.65,92.25,97.82,102.77,102.45,105.22,102.84,106.03,102.87,96.05
181,신촌,109.17,108.35,109.58,110.88,108.00,105.15,106.26,105.76,110.13,107.84,99.98
186,안국,88.36,88.78,93.50,96.45,95.61,96.19,99.41,97.07,102.34,98.61,90.75
230,이태원,115.08,118.08,125.29,134.33,135.35,141.68,154.83,160.40,167.62,172.06,159.31
243,종로3가,99.42,98.29,100.12,101.61,100.53,97.96,98.81,97.71,104.96,101.61,96.22
274,혜화,110.92,109.39,111.93,115.00,112.12,110.32,111.88,110.32,112.25,111.74,102.46
275,홍대입구,111.53,112.56,118.62,123.70,122.57,122.19,124.64,125.72,132.23,131.19,122.17

In [82]:
ratio = pd.concat([average, ratio])
ratio = ratio.reset_index().drop(['index'], axis=1)
ratio

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91.00,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
1,가락시장,79.45,78.04,82.19,85.16,85.73,82.92,83.72,82.77,86.96,87.69,82.06
2,가산디지털단지,74.14,72.61,71.91,72.59,71.88,69.45,69.08,67.77,70.95,68.99,64.71
3,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.69,90.07,88.45,82.86
4,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.93,81.43
5,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.50,94.27,93.03,86.34
6,강남,89.89,88.86,91.21,94.87,97.00,94.68,95.18,94.28,99.82,98.02,92.26
7,강남구청,80.70,81.54,84.09,86.94,87.57,84.95,87.39,84.57,87.34,86.43,80.11
8,강동,90.78,90.54,92.01,93.73,93.36,91.21,90.72,89.52,93.34,91.40,83.95
9,강동구청,82.55,81.67,82.94,85.04,84.45,81.20,81.53,79.95,83.62,82.19,76.25
10,강변,109.95,110.92,114.26,113.76,115.34,112.37,113.71,113.95,117.95,116.06,109.45
11,개롱,87.71,85.79,86.78,89.22,87.16,84.31,85.01,83.35,88.01,85.85,80.63
12,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.37,88.73,88.61,83.48
13,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.69,90.57,88.63,81.07
14,개화산,86.93,83.22,84.45,86.15,85.96,83.18,83.68,84.17,87.94,86.62,80.71
15,거여,90.29,88.15,89.43,89.81,87.43,84.38,84.96,83.78,87.20,85.84,81.06
16,건대입구,103.33,103.05,106.83,109.66,108.52,106.57,107.84,108.67,112.43,110.18,104.58
17,경복궁,84.62,85.89,87.82,90.55,92.36,91.99,94.97,96.23,105.83,100.36,92.89
18,경찰병원,NaN,NaN,76.46,77.13,77.71,74.78,75.96,74.31,77.56,76.97,72.62
19,고덕,85.89,84.29,85.39,88.35,86.74,84.08,85.44,84.81,88.56,85.28,79.41
20,고려대,85.22,85.53,87.24,88.31,88.49,84.43,84.38,83.96,86.15,84.65,79.94
21,고속터미널,125.25,127.21,130.74,132.36,134.33,129.61,130.08,129.68,134.69,130.50,121.52
22,공덕,76.73,76.46,77.18,79.30,79.73,77.39,77.60,77.96,83.68,82.62,77.26
23,공릉,82.94,82.55,84.43,85.75,85.26,84.15,85.32,84.83,87.40,87.24,83.63
24,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.27,92.02,90.02,83.98
25,광나루,94.78,92.68,94.75,97.51,94.15,91.17,92.88,91.49,95.63,94.15,86.94
26,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.26,84.71,84.09,78.47
27,광화문,83.42,85.01,85.98,87.19,85.77,84.21,84.15,81.68,97.37,87.00,76.16
28,광흥창,78.24,77.73,80.46,81.26,81.03,78.81,80.24,79.23,83.64,82.43,76.06
29,교대,76.11,76.10,78.14,80.93,81.21,78.16,78.83,77.46,80.68,79.75,75.64
...,...,...,...,...,...,...,...,...,...,...,...,...
255,창신,84.82,82.41,84.81,84.74,81.48,78.83,79.22,77.63,81.14,79.65,75.07
256,천왕,90.14,89.60,91.70,93.07,89.53,86.61,87.41,85.95,89.53,87.27,80.92
257,천호,98.31,98.51,101.53,103.65,102.23,100.11,100.66,99.36,102.03,99.09,92.76
258,청구,87.62,86.25,87.43,88.92,87.24,83.88,84.67,83.45,86.09,84.86,78.28
259,청담,81.70,80.85,82.36,84.92,84.12,80.48,79.74,78.99,82.85,81.87,76.72
260,청량리,107.16,105.53,105.84,103.89,103.23,101.45,101.66,105.05,108.31,106.06,102.23
261,총신대입구,90.92,90.27,92.99,96.15,96.06,93.50,93.89,92.40,96.24,94.64,88.59
262,충무로,80.10,79.00,80.51,81.45,80.73,78.46,79.75,78.34,83.56,82.61,77.53
263,충정로,78.45,77.33,78.50,79.91,79.56,76.38,76.48,74.89,79.17,78.62,72.98
264,태릉입구,83.52,82.04,85.10,86.46,85.97,84.67,84.91,83.91,86.95,86.55,83.04
265,하계,90.77,88.99,90.22,91.75,90.33,88.67,89.73,88.78,90.64,88.86,82.62
266,학동,74.11,73.61,79.35,81.93,83.25,79.74,80.23,78.87,82.33,80.80,73.59
267,학여울,139.06,122.44,125.95,128.34,131.32,143.86,147.84,161.71,167.30,161.51,143.67
268,한강진,80.19,79.61,81.85,91.29,98.60,99.48,101.91,101.24,112.18,115.11,110.27
269,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.78,90.15,88.50,84.40
270,한성대입구,87.85,87.62,91.03,91.73,90.40,88.25,89.04,88.27,91.95,91.68,85.40
271,한양대,75.53,73.22,76.94,79.01,77.72,74.32,73.45,72.04,73.49,74.44,69.69
272,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.92,95.86,94.32,88.40
273,합정,87.53,87.08,90.45,93.95,95.90,96.80,100.77,101.93,107.18,106.21,100.00
274,행당,88.38,87.52,88.23,89.09,88.07,85.23,85.42,83.84,88.21,86.10,80.36
275,혜화,110.92,109.39,111.93,115.00,112.12,110.32,111.88,110.32,112.25,111.74,102.46
276,홍대입구,111.53,112.56,118.62,123.70,122.57,122.19,124.64,125.72,132.23,131.19,122.17
277,홍제,89.76,88.90,90.51,92.47,91.30,89.16,89.35,88.20,92.83,91.76,84.31
278,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.99,82.34
279,화곡,89.97,88.52,90.09,91.66,90.42,88.16,88.68,87.55,91.28,88.78,82.76
280,화랑대,82.59,80.91,83.30,84.98,84.05,81.64,82.39,81.76,85.18,83.81,79.17
281,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.30,93.61,93.26,86.61
282,회현,91.71,90.86,91.75,92.29,93.24,91.28,93.35,90.79,95.33,95.41,89.35
283,효창공원앞,82.10,79.86,81.79,84.15,82.04,79.73,79.70,78.30,83.52,82.22,77.81
284,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.96,87.31,87.06,82.22

In [83]:
len(ratio)

285

In [85]:
#평균이랑 차이 구하기
def df_dif(dataframe):
    for i in range(len(dataframe)):
        if i > 0:
            dif = dataframe.iloc[i, 1:].values - dataframe.iloc[0, 1:].values
            dataframe.iloc[i, 1:] = dif
    return dataframe

dif = df_dif(ratio)

In [86]:
dif

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91.00,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
1,가락시장,-10.54,-11.00,-8.81,-7.63,-6.16,-6.66,-6.72,-6.37,-5.95,-3.73,-3.35
2,가산디지털단지,-15.85,-16.43,-19.09,-20.20,-20.01,-20.13,-21.36,-21.37,-21.96,-22.43,-20.70
3,가양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.45,-2.84,-2.97,-2.55
4,가오리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.51,-3.98
5,가좌,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.36,1.36,1.61,0.93
6,강남,-0.10,-0.18,0.21,2.08,5.11,5.10,4.74,5.14,6.91,6.60,6.85
7,강남구청,-9.29,-7.50,-6.91,-5.85,-4.32,-4.63,-3.05,-4.57,-5.57,-4.99,-5.30
8,강동,0.79,1.50,1.01,0.94,1.47,1.63,0.28,0.38,0.43,-0.02,-1.46
9,강동구청,-7.44,-7.37,-8.06,-7.75,-7.44,-8.38,-8.91,-9.19,-9.29,-9.23,-9.16
10,강변,19.96,21.88,23.26,20.97,23.45,22.79,23.27,24.81,25.04,24.64,24.04
11,개롱,-2.28,-3.25,-4.22,-3.57,-4.73,-5.27,-5.43,-5.79,-4.90,-5.57,-4.78
12,개포동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.77,-4.18,-2.81,-1.93
13,개화,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.45,-2.34,-2.79,-4.34
14,개화산,-3.06,-5.82,-6.55,-6.64,-5.93,-6.40,-6.76,-4.97,-4.97,-4.80,-4.70
15,거여,0.30,-0.89,-1.57,-2.98,-4.46,-5.20,-5.48,-5.36,-5.71,-5.58,-4.35
16,건대입구,13.34,14.01,15.83,16.87,16.63,16.99,17.40,19.53,19.52,18.76,19.17
17,경복궁,-5.37,-3.15,-3.18,-2.24,0.47,2.41,4.53,7.09,12.92,8.94,7.48
18,경찰병원,NaN,NaN,-14.54,-15.66,-14.18,-14.80,-14.48,-14.83,-15.35,-14.45,-12.79
19,고덕,-4.10,-4.75,-5.61,-4.44,-5.15,-5.50,-5.00,-4.33,-4.35,-6.14,-6.00
20,고려대,-4.77,-3.51,-3.76,-4.48,-3.40,-5.15,-6.06,-5.18,-6.76,-6.77,-5.47
21,고속터미널,35.26,38.17,39.74,39.57,42.44,40.03,39.64,40.54,41.78,39.08,36.11
22,공덕,-13.26,-12.58,-13.82,-13.49,-12.16,-12.19,-12.84,-11.18,-9.23,-8.80,-8.15
23,공릉,-7.05,-6.49,-6.57,-7.04,-6.63,-5.43,-5.12,-4.31,-5.51,-4.18,-1.78
24,공항시장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.87,-0.89,-1.40,-1.43
25,광나루,4.79,3.64,3.75,4.72,2.26,1.59,2.44,2.35,2.72,2.73,1.53
26,광운대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.88,-8.20,-7.33,-6.94
27,광화문,-6.57,-4.03,-5.02,-5.60,-6.12,-5.37,-6.29,-7.46,4.46,-4.42,-9.25
28,광흥창,-11.75,-11.31,-10.54,-11.53,-10.86,-10.77,-10.20,-9.91,-9.27,-8.99,-9.35
29,교대,-13.88,-12.94,-12.86,-11.86,-10.68,-11.42,-11.61,-11.68,-12.23,-11.67,-9.77
...,...,...,...,...,...,...,...,...,...,...,...,...
255,창신,-5.17,-6.63,-6.19,-8.05,-10.41,-10.75,-11.22,-11.51,-11.77,-11.77,-10.34
256,천왕,0.15,0.56,0.70,0.28,-2.36,-2.97,-3.03,-3.19,-3.38,-4.15,-4.49
257,천호,8.32,9.47,10.53,10.86,10.34,10.53,10.22,10.22,9.12,7.67,7.35
258,청구,-2.37,-2.79,-3.57,-3.87,-4.65,-5.70,-5.77,-5.69,-6.82,-6.56,-7.13
259,청담,-8.29,-8.19,-8.64,-7.87,-7.77,-9.10,-10.70,-10.15,-10.06,-9.55,-8.69
260,청량리,17.17,16.49,14.84,11.10,11.34,11.87,11.22,15.91,15.40,14.64,16.82
261,총신대입구,0.93,1.23,1.99,3.36,4.17,3.92,3.45,3.26,3.33,3.22,3.18
262,충무로,-9.89,-10.04,-10.49,-11.34,-11.16,-11.12,-10.69,-10.80,-9.35,-8.81,-7.88
263,충정로,-11.54,-11.71,-12.50,-12.88,-12.33,-13.20,-13.96,-14.25,-13.74,-12.80,-12.43
264,태릉입구,-6.47,-7.00,-5.90,-6.33,-5.92,-4.91,-5.53,-5.23,-5.96,-4.87,-2.37
265,하계,0.78,-0.05,-0.78,-1.04,-1.56,-0.91,-0.71,-0.36,-2.27,-2.56,-2.79
266,학동,-15.88,-15.43,-11.65,-10.86,-8.64,-9.84,-10.21,-10.27,-10.58,-10.62,-11.82
267,학여울,49.07,33.40,34.95,35.55,39.43,54.28,57.40,72.57,74.39,70.09,58.26
268,한강진,-9.80,-9.43,-9.15,-1.50,6.71,9.90,11.47,12.10,19.27,23.69,24.86
269,한남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.36,-2.76,-2.92,-1.01
270,한성대입구,-2.14,-1.42,0.03,-1.06,-1.49,-1.33,-1.40,-0.87,-0.96,0.26,-0.01
271,한양대,-14.46,-15.82,-14.06,-13.78,-14.17,-15.26,-16.99,-17.10,-19.42,-16.98,-15.72
272,한티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.78,2.95,2.90,2.99
273,합정,-2.46,-1.96,-0.55,1.16,4.01,7.22,10.33,12.79,14.27,14.79,14.59
274,행당,-1.61,-1.52,-2.77,-3.70,-3.82,-4.35,-5.02,-5.30,-4.70,-5.32,-5.05
275,혜화,20.93,20.35,20.93,22.21,20.23,20.74,21.44,21.18,19.34,20.32,17.05
276,홍대입구,21.54,23.52,27.62,30.91,30.68,32.61,34.20,36.58,39.32,39.77,36.76
277,홍제,-0.23,-0.14,-0.49,-0.32,-0.59,-0.42,-1.09,-0.94,-0.08,0.34,-1.10
278,화계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.57,-3.07
279,화곡,-0.02,-0.52,-0.91,-1.13,-1.47,-1.42,-1.76,-1.59,-1.63,-2.64,-2.65
280,화랑대,-7.40,-8.13,-7.70,-7.81,-7.84,-7.94,-8.05,-7.38,-7.73,-7.61,-6.24
281,회기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.16,0.70,1.84,1.20
282,회현,1.72,1.82,0.75,-0.50,1.35,1.70,2.91,1.65,2.42,3.99,3.94
283,효창공원앞,-7.89,-9.18,-9.21,-8.64,-9.85,-9.85,-10.74,-10.84,-9.39,-9.20,-7.60
284,흑석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.18,-5.60,-4.36,-3.19

In [87]:
#0보다 큰 값(평균보다 큰 값) 구하기
def over_average(x):
    if x is not None:
        if x > 0:
            return x
        else:
            return False
    else:
        return x

for column in dif.iloc[:,1:].columns:
    dif[column] = dif[column].apply(lambda x : over_average(x))

In [88]:
dif

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
1,가락시장,False,False,False,False,False,False,False,False,False,False,False
2,가산디지털단지,False,False,False,False,False,False,False,False,False,False,False
3,가양,False,False,False,False,False,False,False,False,False,False,False
4,가오리,False,False,False,False,False,False,False,False,False,1.51,False
5,가좌,False,False,False,False,False,False,False,3.36,1.36,1.61,0.93
6,강남,False,False,0.21,2.08,5.11,5.1,4.74,5.14,6.91,6.6,6.85
7,강남구청,False,False,False,False,False,False,False,False,False,False,False
8,강동,0.79,1.5,1.01,0.94,1.47,1.63,0.28,0.38,0.43,False,False
9,강동구청,False,False,False,False,False,False,False,False,False,False,False
10,강변,19.96,21.88,23.26,20.97,23.45,22.79,23.27,24.81,25.04,24.64,24.04
11,개롱,False,False,False,False,False,False,False,False,False,False,False
12,개포동,False,False,False,False,False,False,False,False,False,False,False
13,개화,False,False,False,False,False,False,False,False,False,False,False
14,개화산,False,False,False,False,False,False,False,False,False,False,False
15,거여,0.3,False,False,False,False,False,False,False,False,False,False
16,건대입구,13.34,14.01,15.83,16.87,16.63,16.99,17.4,19.53,19.52,18.76,19.17
17,경복궁,False,False,False,False,0.47,2.41,4.53,7.09,12.92,8.94,7.48
18,경찰병원,False,False,False,False,False,False,False,False,False,False,False
19,고덕,False,False,False,False,False,False,False,False,False,False,False
20,고려대,False,False,False,False,False,False,False,False,False,False,False
21,고속터미널,35.26,38.17,39.74,39.57,42.44,40.03,39.64,40.54,41.78,39.08,36.11
22,공덕,False,False,False,False,False,False,False,False,False,False,False
23,공릉,False,False,False,False,False,False,False,False,False,False,False
24,공항시장,False,False,False,False,False,False,False,False,False,False,False
25,광나루,4.79,3.64,3.75,4.72,2.26,1.59,2.44,2.35,2.72,2.73,1.53
26,광운대,False,False,False,False,False,False,False,False,False,False,False
27,광화문,False,False,False,False,False,False,False,False,4.46,False,False
28,광흥창,False,False,False,False,False,False,False,False,False,False,False
29,교대,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
255,창신,False,False,False,False,False,False,False,False,False,False,False
256,천왕,0.15,0.56,0.7,0.28,False,False,False,False,False,False,False
257,천호,8.32,9.47,10.53,10.86,10.34,10.53,10.22,10.22,9.12,7.67,7.35
258,청구,False,False,False,False,False,False,False,False,False,False,False
259,청담,False,False,False,False,False,False,False,False,False,False,False
260,청량리,17.17,16.49,14.84,11.1,11.34,11.87,11.22,15.91,15.4,14.64,16.82
261,총신대입구,0.93,1.23,1.99,3.36,4.17,3.92,3.45,3.26,3.33,3.22,3.18
262,충무로,False,False,False,False,False,False,False,False,False,False,False
263,충정로,False,False,False,False,False,False,False,False,False,False,False
264,태릉입구,False,False,False,False,False,False,False,False,False,False,False
265,하계,0.78,False,False,False,False,False,False,False,False,False,False
266,학동,False,False,False,False,False,False,False,False,False,False,False
267,학여울,49.07,33.4,34.95,35.55,39.43,54.28,57.4,72.57,74.39,70.09,58.26
268,한강진,False,False,False,False,6.71,9.9,11.47,12.1,19.27,23.69,24.86
269,한남,False,False,False,False,False,False,False,False,False,False,False
270,한성대입구,False,False,0.03,False,False,False,False,False,False,0.26,False
271,한양대,False,False,False,False,False,False,False,False,False,False,False
272,한티,False,False,False,False,False,False,False,1.78,2.95,2.9,2.99
273,합정,False,False,False,1.16,4.01,7.22,10.33,12.79,14.27,14.79,14.59
274,행당,False,False,False,False,False,False,False,False,False,False,False
275,혜화,20.93,20.35,20.93,22.21,20.23,20.74,21.44,21.18,19.34,20.32,17.05
276,홍대입구,21.54,23.52,27.62,30.91,30.68,32.61,34.2,36.58,39.32,39.77,36.76
277,홍제,False,False,False,False,False,False,False,False,False,0.34,False
278,화계,False,False,False,False,False,False,False,False,False,3.57,False
279,화곡,False,False,False,False,False,False,False,False,False,False,False
280,화랑대,False,False,False,False,False,False,False,False,False,False,False
281,회기,False,False,False,False,False,False,False,1.16,0.7,1.84,1.2
282,회현,1.72,1.82,0.75,False,1.35,1.7,2.91,1.65,2.42,3.99,3.94
283,효창공원앞,False,False,False,False,False,False,False,False,False,False,False
284,흑석,False,False,False,False,False,False,False,False,False,False,False

In [89]:
#2년 연속 평균보다 큰 역 구하기
dif2 = dif.copy()
for index, row in dif2.iterrows():
    for index_c, column in enumerate(dif2.columns):
        if (row[index_c] != False) and (isinstance(row[index_c], str) == False):
            if (index_c == 1) and (row[index_c+1] == False):
                row[index_c] = False
            elif (index_c == len(dif2.columns)-1) and (row[index_c-1] == False):
                row[index_c] = False
            elif (index_c > 1) and (index_c < len(dif2.columns)-1) and (row[index_c - 1] == False) and (row[index_c + 1] == False):
                row[index_c] = False
                
for index, row in dif2.iterrows():
    hasTrue = False
    for index_c, column in enumerate(dif2.columns):
        if (isinstance(row[index_c], str) == False) and (row[index_c] != False):
            hasTrue = True
            break
    
    if hasTrue == False:
        dif2 = dif2.drop(index)

In [90]:
dif2

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
5,가좌,False,False,False,False,False,False,False,3.36,1.36,1.61,0.93
6,강남,False,False,0.21,2.08,5.11,5.1,4.74,5.14,6.91,6.6,6.85
8,강동,0.79,1.5,1.01,0.94,1.47,1.63,0.28,0.38,0.43,False,False
10,강변,19.96,21.88,23.26,20.97,23.45,22.79,23.27,24.81,25.04,24.64,24.04
16,건대입구,13.34,14.01,15.83,16.87,16.63,16.99,17.4,19.53,19.52,18.76,19.17
17,경복궁,False,False,False,False,0.47,2.41,4.53,7.09,12.92,8.94,7.48
21,고속터미널,35.26,38.17,39.74,39.57,42.44,40.03,39.64,40.54,41.78,39.08,36.11
25,광나루,4.79,3.64,3.75,4.72,2.26,1.59,2.44,2.35,2.72,2.73,1.53
32,구반포,False,False,False,False,False,False,False,8.22,8.7,6.18,4.38
33,구산,0.64,1.34,0.71,False,False,False,False,False,False,False,False
36,구파발,22.43,14.93,9.99,5.21,4.71,5.19,4.39,3.09,3.74,6.47,4.44
38,군자,False,False,0.32,0.21,False,False,0.12,0.43,0.22,False,False
39,굽은다리,False,0.96,1.35,0.56,False,False,False,0.67,0.77,False,False
40,금호,0.41,0.96,0.04,False,False,False,False,False,False,False,False
43,김포공항,12.49,15.28,11.4,17.8,22.92,23.28,21.54,16.04,14.5,12.7,11.76
44,까치산,1.92,1.56,1.32,0.78,0.31,False,False,False,False,False,False
45,까치울,False,False,False,False,8.25,2.13,2.5,2.63,1.01,False,False
48,남부터미널,7.41,8.29,9.35,8.97,10.42,8.91,9,8.58,8.68,9.44,8.18
50,남태령,5.17,3.7,6.9,5.45,False,False,False,False,False,False,False
54,노량진,False,False,False,False,False,False,False,10.87,10.41,10.17,9.78
55,노원,7.76,8.02,8.28,8.13,8.1,7.93,7.07,8.07,7.96,7.13,7.33
57,녹사평,10.48,8.18,6.51,9.04,11.4,18.29,38.67,50.9,48.01,48.69,43.18
61,당고개,3.5,4.74,3.63,2.51,2.54,2.23,1.79,2.66,2.44,1.83,3.31
63,대림,0.32,0.71,1.22,3.21,2.22,2.5,2.3,3.16,3.62,3.56,4.1
66,대치,0.39,1.28,1.63,1.46,2.06,0.45,False,False,0.72,1.08,1.42
71,도봉산,9.19,8.79,7.31,5.74,5.32,7.15,5.97,11.13,8.95,8.93,9.54
72,독립문,False,False,False,False,0.43,2.98,6.27,6.59,5.79,7.61,5.5
73,독바위,18.74,19.23,17.18,10.59,7.47,8,6.67,4.96,2.47,2.6,1.38
75,동대문,12.52,11.85,12.32,11.64,11.06,10.58,11.13,9.81,9.02,7.81,7.29
...,...,...,...,...,...,...,...,...,...,...,...,...
227,의정부,False,False,False,False,False,False,False,25.75,25.43,23.49,23.06
228,이대,7.43,7.16,6.48,6.68,5.34,5.71,5.46,3.4,4.15,3.15,5.3
229,이수,False,False,False,0.06,1.66,2.74,1.96,2.08,2.35,1.89,2.64
230,이촌,16.32,15.82,17.96,19.86,18.97,18.01,20.41,15.18,12.23,11.56,9.03
231,이태원,25.09,29.04,34.29,41.54,43.46,52.1,64.39,71.26,74.71,80.64,73.9
234,잠실,6.84,6.72,8.7,7.87,8.3,8.43,9.45,11.79,13.91,12.93,12.06
236,잠실새내,False,False,False,False,False,False,False,False,3.89,10.03,10.66
239,장지,False,False,4.63,7.71,6.5,4.13,1.63,1.26,False,0.44,0.45
242,제기동,6.88,7.24,7.41,6.08,7.54,6.6,7.56,6.32,6.25,4.74,5.86
243,종각,0.02,1.01,2.19,1.33,1.9,1.22,False,False,False,False,False
244,종로3가,9.43,9.25,9.12,8.82,8.64,8.38,8.37,8.57,12.05,10.19,10.81
245,종로5가,False,0.47,3.08,3.01,3.58,4.17,6.16,5.97,5.15,7.21,5.75
246,종합운동장,23.73,21.11,24.95,22.82,24.43,28.91,34.3,24.42,20.6,34.27,39.78
249,중랑,False,False,False,False,False,False,False,3.6,3.19,3.14,3.14
250,중화,0.78,0.02,False,False,False,False,False,False,False,False,False
252,증산,False,0.42,1.06,False,False,False,False,False,False,False,False
253,지축,3.45,3.28,4.36,4.75,6.2,4,3.17,0.76,0.65,False,False
254,창동,3.39,3.87,3.73,3.06,3.27,2.87,2.73,1.77,1.87,1.52,1.73
256,천왕,0.15,0.56,0.7,0.28,False,False,False,False,False,False,False
257,천호,8.32,9.47,10.53,10.86,10.34,10.53,10.22,10.22,9.12,7.67,7.35
260,청량리,17.17,16.49,14.84,11.1,11.34,11.87,11.22,15.91,15.4,14.64,16.82
261,총신대입구,0.93,1.23,1.99,3.36,4.17,3.92,3.45,3.26,3.33,3.22,3.18
267,학여울,49.07,33.4,34.95,35.55,39.43,54.28,57.4,72.57,74.39,70.09,58.26
268,한강진,False,False,False,False,6.71,9.9,11.47,12.1,19.27,23.69,24.86
272,한티,False,False,False,False,False,False,False,1.78,2.95,2.9,2.99
273,합정,False,False,False,1.16,4.01,7.22,10.33,12.79,14.27,14.79,14.59
275,혜화,20.93,20.35,20.93,22.21,20.23,20.74,21.44,21.18,19.34,20.32,17.05
276,홍대입구,21.54,23.52,27.62,30.91,30.68,32.61,34.2,36.58,39.32,39.77,36.76
281,회기,False,False,False,False,False,False,False,1.16,0.7,1.84,1.2
282,회현,1.72,1.82,0.75,False,1.35,1.7,2.91,1.65,2.42,3.99,3.94

In [94]:
test = ['망원', '성수', '종로3가', '경복궁', '신사', '안국', '서울대입구', '낙성대', '명동', '이태원', '홍대입구', '상도', '상계', '사당', '강남', '가좌', '뚝섬', '혜화', '신촌']

dif2.loc[dif2['역명'].isin(test)]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
5,가좌,False,False,False,False,False,False,False,3.36,1.36,1.61,0.93
6,강남,False,False,0.21,2.08,5.11,5.1,4.74,5.14,6.91,6.6,6.85
17,경복궁,False,False,False,False,0.47,2.41,4.53,7.09,12.92,8.94,7.48
96,망원,False,False,False,False,False,False,False,False,0.38,5.44,6.45
100,명동,18.44,20.26,23.89,23.91,20.57,21.68,22.64,22.48,20.17,17.81,16.17
124,사당,1.29,2.02,3.01,4.27,5.46,6.36,7.51,7.35,7.95,8.56,8.69
142,서울대입구,1.85,2.37,2.55,1.58,1.17,1.09,False,0.85,0.68,1.02,1.95
175,신사,False,False,1.25,5.03,10.88,12.87,14.78,13.7,13.12,11.45,10.64
182,신촌,19.18,19.31,18.58,18.09,16.11,15.57,15.82,16.62,17.22,16.42,14.57
187,안국,False,False,2.5,3.66,3.72,6.61,8.97,7.93,9.43,7.19,5.34
231,이태원,25.09,29.04,34.29,41.54,43.46,52.1,64.39,71.26,74.71,80.64,73.9
244,종로3가,9.43,9.25,9.12,8.82,8.64,8.38,8.37,8.57,12.05,10.19,10.81
275,혜화,20.93,20.35,20.93,22.21,20.23,20.74,21.44,21.18,19.34,20.32,17.05
276,홍대입구,21.54,23.52,27.62,30.91,30.68,32.61,34.2,36.58,39.32,39.77,36.76

In [95]:
maybe_hot = dif2['역명'].unique().tolist()
dif2.loc[dif2['역명'].isin(maybe_hot[:20])]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,평균,89.99,89.04,91,92.79,91.89,89.58,90.44,89.14,92.91,91.42,85.41
5,가좌,False,False,False,False,False,False,False,3.36,1.36,1.61,0.93
6,강남,False,False,0.21,2.08,5.11,5.1,4.74,5.14,6.91,6.6,6.85
8,강동,0.79,1.5,1.01,0.94,1.47,1.63,0.28,0.38,0.43,False,False
10,강변,19.96,21.88,23.26,20.97,23.45,22.79,23.27,24.81,25.04,24.64,24.04
16,건대입구,13.34,14.01,15.83,16.87,16.63,16.99,17.4,19.53,19.52,18.76,19.17
17,경복궁,False,False,False,False,0.47,2.41,4.53,7.09,12.92,8.94,7.48
21,고속터미널,35.26,38.17,39.74,39.57,42.44,40.03,39.64,40.54,41.78,39.08,36.11
25,광나루,4.79,3.64,3.75,4.72,2.26,1.59,2.44,2.35,2.72,2.73,1.53
32,구반포,False,False,False,False,False,False,False,8.22,8.7,6.18,4.38
33,구산,0.64,1.34,0.71,False,False,False,False,False,False,False,False
36,구파발,22.43,14.93,9.99,5.21,4.71,5.19,4.39,3.09,3.74,6.47,4.44
38,군자,False,False,0.32,0.21,False,False,0.12,0.43,0.22,False,False
39,굽은다리,False,0.96,1.35,0.56,False,False,False,0.67,0.77,False,False
40,금호,0.41,0.96,0.04,False,False,False,False,False,False,False,False
43,김포공항,12.49,15.28,11.4,17.8,22.92,23.28,21.54,16.04,14.5,12.7,11.76
44,까치산,1.92,1.56,1.32,0.78,0.31,False,False,False,False,False,False
45,까치울,False,False,False,False,8.25,2.13,2.5,2.63,1.01,False,False
48,남부터미널,7.41,8.29,9.35,8.97,10.42,8.91,9,8.58,8.68,9.44,8.18
50,남태령,5.17,3.7,6.9,5.45,False,False,False,False,False,False,False

In [96]:
dif2.loc[dif2['역명'].isin(maybe_hot[20:40])]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
54,노량진,False,False,False,False,False,False,False,10.87,10.41,10.17,9.78
55,노원,7.76,8.02,8.28,8.13,8.1,7.93,7.07,8.07,7.96,7.13,7.33
57,녹사평,10.48,8.18,6.51,9.04,11.4,18.29,38.67,50.9,48.01,48.69,43.18
61,당고개,3.5,4.74,3.63,2.51,2.54,2.23,1.79,2.66,2.44,1.83,3.31
63,대림,0.32,0.71,1.22,3.21,2.22,2.5,2.3,3.16,3.62,3.56,4.1
66,대치,0.39,1.28,1.63,1.46,2.06,0.45,False,False,0.72,1.08,1.42
71,도봉산,9.19,8.79,7.31,5.74,5.32,7.15,5.97,11.13,8.95,8.93,9.54
72,독립문,False,False,False,False,0.43,2.98,6.27,6.59,5.79,7.61,5.5
73,독바위,18.74,19.23,17.18,10.59,7.47,8,6.67,4.96,2.47,2.6,1.38
75,동대문,12.52,11.85,12.32,11.64,11.06,10.58,11.13,9.81,9.02,7.81,7.29
76,동대문역사문화공원,False,False,14.45,12.84,10.77,10.24,15.08,10.96,10.27,10.03,9.46
78,동대문운동장,17.26,15.37,False,False,False,False,False,False,False,False,False
79,동대입구,0.12,4.35,3.86,3.47,2.88,1.93,7.22,4.52,4.46,5.14,7.46
80,동두천 중앙,False,False,False,False,False,False,False,7.06,6.6,False,False
81,동묘앞,6.94,8.03,9.15,8.76,9.46,11.08,13.16,15.5,15.45,17.47,18.89
82,동작,10.49,10.71,9.51,8.28,5.38,5.05,13.13,12.92,6.33,4.23,4.7
87,뚝섬유원지,15.71,14.35,15.84,16.04,17.84,18.82,22.24,21.18,22.22,22.52,26.74
88,마곡,0.86,1.36,0.7,False,False,False,False,False,False,False,False
92,마천,7.28,7.18,5.62,3.83,2.34,2.84,3.02,3.41,2.18,1.53,1.93
95,망우,False,False,False,False,False,False,False,8.56,9,8.79,9.01

In [97]:
dif2.loc[dif2['역명'].isin(maybe_hot[40:60])]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
96,망원,False,False,False,False,False,False,False,False,0.38,5.44,6.45
98,먹골,1.8,6.59,6.36,5.99,6.48,5.09,4.28,3.51,2.05,2.69,1.7
100,명동,18.44,20.26,23.89,23.91,20.57,21.68,22.64,22.48,20.17,17.81,16.17
103,몽촌토성,4.4,3.12,7.54,6.03,3.99,3.75,5.08,8.7,3.52,3.07,False
107,미아,5.25,5.84,5.91,3.62,3.21,1.12,0.3,0.17,False,False,False
108,미아사거리,False,False,False,False,False,False,5.05,6.34,6.3,5.64,5.45
109,미아삼거리,6.78,7.29,7.45,6.57,5.21,5.76,False,False,False,False,False
111,발산,5.19,4.66,4.65,6.71,6.57,4.28,8.1,11.03,9.91,7.88,0.96
114,방학,False,False,False,False,False,False,False,1.09,0.95,0.64,1.18
119,봉은사,False,False,False,False,False,False,False,3.15,6.74,6.9,5.5
122,불광,7.29,7.23,7.61,8.47,7.13,6.74,5.88,6.68,6.06,4.82,4.27
123,사가정,2.04,2.24,1.78,1.17,0.93,1.01,0.94,1.51,1.1,0.44,0.51
124,사당,1.29,2.02,3.01,4.27,5.46,6.36,7.51,7.35,7.95,8.56,8.69
126,산성,False,False,False,False,False,False,0.65,0.82,0.16,2.68,2.19
127,삼각지,5.57,4.35,3.21,4.21,5.59,6.34,7.2,7.49,5.13,5.14,4.29
128,삼성,0.86,2.65,2.54,3.23,2.91,False,False,0.17,0.32,0.43,1.65
132,상봉,8.27,7.47,5.57,7.34,6.11,6.14,6.03,8.02,7.01,5.99,7.29
133,상수,2.15,6.34,9.34,13.09,14.38,17.42,21.99,24.15,27.68,26,23.09
139,서강대,False,False,False,False,False,False,False,4.55,4.95,4.6,4.48
142,서울대입구,1.85,2.37,2.55,1.58,1.17,1.09,False,0.85,0.68,1.02,1.95

In [98]:
dif2.loc[dif2['역명'].isin(maybe_hot[60:80])]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
143,서울숲,False,False,False,False,False,False,False,7.83,3.88,7.69,6.99
144,서울역,12.83,15,13.41,12.52,13.69,13.39,13.33,14.71,14.31,14.1,12.89
153,성신여대입구,False,False,0.45,0.97,1.34,0.55,0.72,1.84,2.75,3.49,4.81
154,송정,2.96,4.16,4.34,4.21,3.71,3.74,3.07,2.89,2.3,1.78,1.58
156,수락산,8.94,8.17,5.95,4.26,3.62,4.46,3.46,3.63,2.29,1.7,2.1
158,수서,False,False,False,False,False,False,False,False,False,5.31,4.5
159,수유,3.95,4.07,4.43,3.61,2.81,2.68,2.21,1.63,1.75,1.51,3.03
163,신금호,0.97,0.5,False,False,False,False,False,False,False,False,False
165,신논현,False,False,False,False,False,False,False,5.91,9.46,9.17,9.56
166,신답,3.95,1.3,1.76,False,False,False,False,False,False,False,False
167,신당,1.95,2.57,1.95,1.7,0.69,1.09,False,False,False,False,False
168,신대방,0.69,0.08,False,False,False,False,False,False,False,False,False
170,신도림,3.8,5.04,4.53,6.82,6.94,6.94,7.95,9.04,9.92,10.25,10.9
171,신림,4.69,5.75,6.19,5.99,5.44,5.92,5.53,5.79,5.89,4.88,4.36
173,신반포,False,False,False,False,False,False,False,0.44,1.36,1.72,1.04
175,신사,False,False,1.25,5.03,10.88,12.87,14.78,13.7,13.12,11.45,10.64
176,신설동,False,False,False,False,False,False,False,False,False,1.31,1.89
177,신용산,2.77,1.73,1.46,0.43,1.35,1.55,0.33,0.34,False,False,False
180,신정네거리,1.08,1.75,1.11,1.35,0.83,0.76,0.66,0.84,0.61,False,False
181,신천,10.77,7.33,7.41,8.27,8.22,7.74,8.29,8.57,10.27,False,False

In [99]:
dif2.loc[dif2['역명'].isin(maybe_hot[80:100])]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
182,신촌,19.18,19.31,18.58,18.09,16.11,15.57,15.82,16.62,17.22,16.42,14.57
183,신풍,4.15,4.27,4.19,3.52,2.87,2.74,2.44,2.61,1.25,0.8,0.26
185,아차산,10.5,8.82,9.62,9.15,6.79,6.2,5.08,4.68,4.08,3.85,3.68
187,안국,False,False,2.5,3.66,3.72,6.61,8.97,7.93,9.43,7.19,5.34
190,압구정,4.53,5.72,6.74,6.85,7.53,5.99,5.17,4.15,4.72,3.9,3.59
191,압구정로데오,False,False,False,False,False,False,False,9.77,10.07,11.81,12.73
198,어린이대공원,2.37,0.99,1.8,1.91,4.07,4.27,3.23,4.63,1.12,2.97,5.69
200,여의나루,6.7,2.15,16.7,22.97,22.58,31.32,33.45,45.28,59.05,61.74,55.44
204,연신내,4.28,4.2,4.3,3.78,3.37,3.44,3.33,3.59,3.84,3.44,3.17
207,영등포시장,1.07,1.33,2.93,3.33,3.87,3.15,2.94,2.07,5.98,7.12,5.37
209,오목교,6.19,6.09,6.68,7.61,4.62,3.95,3.83,4.77,3.52,2.71,1.94
210,옥수,False,False,False,False,False,False,False,0.45,2.13,1.68,1.04
212,올림픽공원,29.79,33.74,26.53,35.73,31.78,37.87,32.69,49.9,52.43,28.8,28.44
213,왕십리,4.81,8.28,10.6,11.52,10.88,10.8,10.02,12.01,12.05,11.73,11.01
215,용답,0.16,0.01,False,0.46,0.65,0.46,False,False,False,False,False
216,용두,6.2,0.6,False,False,False,False,False,False,False,False,False
221,월드컵경기장,49.39,52.9,46.59,55.83,45.2,55.71,49.29,60.67,55.21,49.16,33.5
225,응봉,False,False,False,False,False,False,False,2.44,2.5,1.33,2.29
227,의정부,False,False,False,False,False,False,False,25.75,25.43,23.49,23.06
228,이대,7.43,7.16,6.48,6.68,5.34,5.71,5.46,3.4,4.15,3.15,5.3

In [100]:
dif2.loc[dif2['역명'].isin(maybe_hot[100:])]

,역명,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
229,이수,False,False,False,0.06,1.66,2.74,1.96,2.08,2.35,1.89,2.64
230,이촌,16.32,15.82,17.96,19.86,18.97,18.01,20.41,15.18,12.23,11.56,9.03
231,이태원,25.09,29.04,34.29,41.54,43.46,52.1,64.39,71.26,74.71,80.64,73.9
234,잠실,6.84,6.72,8.7,7.87,8.3,8.43,9.45,11.79,13.91,12.93,12.06
236,잠실새내,False,False,False,False,False,False,False,False,3.89,10.03,10.66
239,장지,False,False,4.63,7.71,6.5,4.13,1.63,1.26,False,0.44,0.45
242,제기동,6.88,7.24,7.41,6.08,7.54,6.6,7.56,6.32,6.25,4.74,5.86
243,종각,0.02,1.01,2.19,1.33,1.9,1.22,False,False,False,False,False
244,종로3가,9.43,9.25,9.12,8.82,8.64,8.38,8.37,8.57,12.05,10.19,10.81
245,종로5가,False,0.47,3.08,3.01,3.58,4.17,6.16,5.97,5.15,7.21,5.75
246,종합운동장,23.73,21.11,24.95,22.82,24.43,28.91,34.3,24.42,20.6,34.27,39.78
249,중랑,False,False,False,False,False,False,False,3.6,3.19,3.14,3.14
250,중화,0.78,0.02,False,False,False,False,False,False,False,False,False
252,증산,False,0.42,1.06,False,False,False,False,False,False,False,False
253,지축,3.45,3.28,4.36,4.75,6.2,4,3.17,0.76,0.65,False,False
254,창동,3.39,3.87,3.73,3.06,3.27,2.87,2.73,1.77,1.87,1.52,1.73
256,천왕,0.15,0.56,0.7,0.28,False,False,False,False,False,False,False
257,천호,8.32,9.47,10.53,10.86,10.34,10.53,10.22,10.22,9.12,7.67,7.35
260,청량리,17.17,16.49,14.84,11.1,11.34,11.87,11.22,15.91,15.4,14.64,16.82
261,총신대입구,0.93,1.23,1.99,3.36,4.17,3.92,3.45,3.26,3.33,3.22,3.18
267,학여울,49.07,33.4,34.95,35.55,39.43,54.28,57.4,72.57,74.39,70.09,58.26
268,한강진,False,False,False,False,6.71,9.9,11.47,12.1,19.27,23.69,24.86
272,한티,False,False,False,False,False,False,False,1.78,2.95,2.9,2.99
273,합정,False,False,False,1.16,4.01,7.22,10.33,12.79,14.27,14.79,14.59
275,혜화,20.93,20.35,20.93,22.21,20.23,20.74,21.44,21.18,19.34,20.32,17.05
276,홍대입구,21.54,23.52,27.62,30.91,30.68,32.61,34.2,36.58,39.32,39.77,36.76
281,회기,False,False,False,False,False,False,False,1.16,0.7,1.84,1.2
282,회현,1.72,1.82,0.75,False,1.35,1.7,2.91,1.65,2.42,3.99,3.94

평균과 10%p 이상 차이 나는 곳들을 봤더니 대충 4개로 분류할 수 있음
터미널 : 강변, 고속터미널, 김포공항, 서울역, 청량리
대학가 : 건대입구, 신촌, 왕십리, 혜화, 홍대입구, 상수
원래 핫플 : 녹사평, 명동, 신사, 압구정로데오, 이태원, 한강진, 합정
공원, 경기장(경기 및 공연) : 뚝섬유원지, 여의나루, 올림픽공원, 월드컵경기장, 종합운동장, 학여울
왜 높은지 잘 모르겠는 곳 : 의정부, 이촌, 천호

확실히 최근 10미만에서 10으로 증가한 역들을 최근 핫플이 포함되는 것 같음